In [ ]:
# 1. Install dependencies
!apt-get update -y && apt-get install -y build-essential git cmake libboost-system-dev libprotobuf-dev protobuf-compiler libssl-dev libgoogle-perftools-dev

# 2. Clone marian-dev if not already present
!git clone https://github.com/marian-nmt/marian-dev.git /kaggle/working/marian-dev

# 3. Clean and build with warnings disabled
%cd /kaggle/working/marian-dev
!mkdir -p build

# 1. Patch the deprecated thrust inheritance in cumsum.cu
!sed -i 's/: public thrust::unary_function<int, int>//g' src/tensors/gpu/cumsum.cu

# 2. Re-configure build directory
%cd /kaggle/working/marian-dev/build
!rm -rf *

!cmake .. \
  -DCOMPILE_CUDA=ON \
  -DCOMPILE_CPU=ON \
  -DCMAKE_CXX_FLAGS="-Wno-error"

# 3. Compile Marian
!make -j$(nproc)

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/ InRelease [3,631 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64  InRelease [1,578 B]
Get:4 https://r2u.stat.illinois.edu/ubuntu noble InRelease [9,161 B]
Hit:5 http://archive.ubuntu.com/ubuntu noble InRelease
Get:6 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64  Packages [1,919 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble InRelease [17.8 kB]
Get:10 https://r2u.stat.illinois.edu/ubuntu noble/main amd64 Packages [3,058 kB]
Get:11 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu noble InRelease
Get:13 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [2,231 kB]
Get:14 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [1,409 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu noble/main amd64 Packages [60.1 kB]
Get:16 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1,729 kB]
Get:17 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Packages [61.7 kB]
Get:18 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [2,166 kB]
Get:19 http://archive.ubuntu.com/ubuntu noble-backports/multiverse amd64 Packages [669 B]
Get:20 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Packages [2,122 kB]
Get:21 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [1,548 kB]
Get:22 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Packages [55.6 kB]
Get:23 https://r2u.stat.illinois.edu/ubuntu noble/main all Packages [10.4 MB]
Fetched 27.1 MB in 5s (5,521 kB/s)
Reading package lists... Done
W: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.10ubuntu1).
git is already the newest version (1:2.43.0-1ubuntu7.3).
cmake is already the newest version (3.28.3-1build7).
libboost-system-dev is already the newest version (1.83.0.1ubuntu2).
protobuf-compiler is already the newest version (3.21.12-8.2ubuntu0.3).
The following additional packages will be installed:
  libprotobuf-lite32t64 libssl3t64 libunwind-dev openssl
Suggested packages:
  libssl-doc
The following NEW packages will be installed:
  libgoogle-perftools-dev libprotobuf-dev libprotobuf-lite32t64 libunwind-dev
The following packages will be upgraded:
  libssl-dev libssl3t64 openssl
3 upgraded, 4 newly installed, 0 to remove and 170 not upgraded.
Need to get 9,385 kB of archives.
After this operation, 23.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libssl-dev amd64 3.0.13-0ubuntu3.16 [2,409 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libssl3t64 amd64 3.0.13-0ubuntu3.16 [1,945 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 openssl amd64 3.0.13-0ubuntu3.16 [1,004 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libunwind-dev amd64 1.6.2-3build1.1 [1,906 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 libgoogle-perftools-dev amd64 2.15-3build1 [470 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libprotobuf-lite32t64 amd64 3.21.12-8.2ubuntu0.3 [238 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libprotobuf-dev amd64 3.21.12-8.2ubuntu0.3 [1,413 kB]
Fetched 9,385 kB in 2s (6,184 kB/s)
(Reading database ... 129802 files and directories currently installed.)
Preparing to unpack .../libssl-dev_3.0.13-0ubuntu3.16_amd64.deb ...
Unpacking libssl-dev:amd64 (3.0.13-0ubuntu3.16) over (3.0.13-0ubuntu3.15) ...
Preparing to unpack .../libssl3t64_3.0.13-0ubuntu3.16_amd64.deb ...
Unpacking libssl3t64:amd64 (3.0.13-0ubuntu3.16) over (3.0.13-0ubuntu3.15) ...
Setting up libssl3t64:amd64 (3.0.13-0ubuntu3.16) ...
(Reading database ... 129802 files and directories currently installed.)
Preparing to unpack .../openssl_3.0.13-0ubuntu3.16_amd64.deb ...
Unpacking openssl (3.0.13-0ubuntu3.16) over (3.0.13-0ubuntu3.15) ...
Selecting previously unselected package libunwind-dev:amd64.
Preparing to unpack .../libunwind-dev_1.6.2-3build1.1_amd64.deb ...
Unpacking libunwind-dev:amd64 (1.6.2-3build1.1) ...
Selecting previously unselected package libgoogle-perftools-dev:amd64.
Preparing to unpack .../libgoogle-perftools-dev_2.15-3build1_amd64.deb ...
Unpacking libgoogle-perftools-dev:amd64 (2.15-3build1) ...
Selecting previously unselected package libprotobuf-lite32t64:amd64.
Preparing to unpack .../libprotobuf-lite32t64_3.21.12-8.2ubuntu0.3_amd64.deb ...
Unpacking libprotobuf-lite32t64:amd64 (3.21.12-8.2ubuntu0.3) ...
Selecting previously unselected package libprotobuf-dev:amd64.
Preparing to unpack .../libprotobuf-dev_3.21.12-8.2ubuntu0.3_amd64.deb ...
Unpacking libprotobuf-dev:amd64 (3.21.12-8.2ubuntu0.3) ...
Setting up libprotobuf-lite32t64:amd64 (3.21.12-8.2ubuntu0.3) ...
Setting up libunwind-dev:amd64 (1.6.2-3build1.1) ...
Setting up libgoogle-perftools-dev:amd64 (2.15-3build1) ...
Setting up libprotobuf-dev:amd64 (3.21.12-8.2ubuntu0.3) ...
Setting up libssl-dev:amd64 (3.0.13-0ubuntu3.16) ...
Setting up openssl (3.0.13-0ubuntu3.16) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Cloning into '/kaggle/working/marian-dev'...
remote: Enumerating objects: 52052, done.
remote: Counting objects: 100% (935/935), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 52052 (delta 748), reused 650 (delta 650), pack-reused 51117 (from 2)
Receiving objects: 100% (52052/52052), 19.16 MiB | 19.38 MiB/s, done.
Resolving deltas: 100% (40953/40953), done.
/kaggle/working/marian-dev
/kaggle/working/marian-dev/build
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- The CXX compiler identification is GNU 13.3.0
-- The C compiler identification is GNU 13.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Project name: marian
-- Project version: v1.12.43+c9f287db
Submodule 'examples' (https://github.com/marian-nmt/marian-examples) registered for path 'examples'
Submodule 'regression-tests' (https://github.com/marian-nmt/marian-regression-tests) registered for path 'regression-tests'
Submodule 'src/3rd_party/fbgemm' (https://github.com/marian-nmt/FBGEMM) registered for path 'src/3rd_party/fbgemm'
Submodule 'src/3rd_party/intgemm' (https://github.com/marian-nmt/intgemm/) registered for path 'src/3rd_party/intgemm'
Submodule 'src/3rd_party/nccl' (https://github.com/marian-nmt/nccl) registered for path 'src/3rd_party/nccl'
Submodule 'src/3rd_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'src/3rd_party/pybind11'
Submodule 'src/3rd_party/ruy' (https://github.com/marian-nmt/ruy.git) registered for path 'src/3rd_party/ruy'
Submodule 'src/3rd_party/sentencepiece' (https://github.com/marian-nmt/sentencepiece) registered for path 'src/3rd_party/sentencepiece'
Submodule 'src/3rd_party/simd_utils' (https://github.com/marian-nmt/simd_utils.git) registered for path 'src/3rd_party/simd_utils'
Submodule 'src/3rd_party/simple-websocket-server' (https://github.com/marian-nmt/Simple-WebSocket-Server) registered for path 'src/3rd_party/simple-websocket-server'
Cloning into '/kaggle/working/marian-dev/examples'...
Cloning into '/kaggle/working/marian-dev/regression-tests'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/fbgemm'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/intgemm'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/nccl'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/pybind11'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/ruy'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/sentencepiece'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/simd_utils'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/simple-websocket-server'...
Submodule path 'examples': checked out '6c40475a9cbdcc219d0b6a8347ae43902204eedc'
Submodule path 'regression-tests': checked out 'ab6fd7365f1b40633a1164dd35c6a15b55f2d4d9'
Submodule path 'src/3rd_party/fbgemm': checked out 'be8a7641ef6a9c61ed86214f8cea378cbb3339ea'
Submodule 'third_party/asmjit' (https://github.com/asmjit/asmjit.git) registered for path 'src/3rd_party/fbgemm/third_party/asmjit'
Submodule 'third_party/cpuinfo' (https://github.com/marian-nmt/cpuinfo) registered for path 'src/3rd_party/fbgemm/third_party/cpuinfo'
Submodule 'third_party/googletest' (https://github.com/google/googletest) registered for path 'src/3rd_party/fbgemm/third_party/googletest'
Cloning into '/kaggle/working/marian-dev/src/3rd_party/fbgemm/third_party/asmjit'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/fbgemm/third_party/cpuinfo'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/fbgemm/third_party/googletest'...
Submodule path 'src/3rd_party/fbgemm/third_party/asmjit': checked out '4da474ac9aa2689e88d5e40a2f37628f302d7e3c'
Submodule path 'src/3rd_party/fbgemm/third_party/cpuinfo': checked out '7e52081076e6dd2179ef88aed8872303996babfc'
Submodule path 'src/3rd_party/fbgemm/third_party/googletest': checked out '0fc5466dbb9e623029b1ada539717d10bd45e99e'
Submodule path 'src/3rd_party/intgemm': checked out '0eda93a95a4472af0a50c78b5df58e7fc459ac7a'
Submodule path 'src/3rd_party/nccl': checked out '5dcf7751494f9d04057bfc6b4a2b64611bc12253'
Submodule path 'src/3rd_party/pybind11': checked out '869cc1ff085dd405635b00eb46e5c84f50f26099'
Submodule path 'src/3rd_party/ruy': checked out 'c04e5e52ae6b144f74ac032652e3c538bda15c9b'
Submodule 'cpuinfo' (https://github.com/pytorch/cpuinfo) registered for path 'src/3rd_party/ruy/third_party/cpuinfo'
Submodule 'googletest' (https://github.com/google/googletest) registered for path 'src/3rd_party/ruy/third_party/googletest'
Cloning into '/kaggle/working/marian-dev/src/3rd_party/ruy/third_party/cpuinfo'...
Cloning into '/kaggle/working/marian-dev/src/3rd_party/ruy/third_party/googletest'...
Submodule path 'src/3rd_party/ruy/third_party/cpuinfo': checked out '082deffc80ce517f81dc2f3aebe6ba671fcd09c9'
Submodule path 'src/3rd_party/ruy/third_party/googletest': checked out '6c58c11d5497b6ee1df3cb400ce30deb72fc28c0'
Submodule path 'src/3rd_party/sentencepiece': checked out 'aef9e2bd0dd1f18d9ac8555a5fef38669e0d3609'
Submodule path 'src/3rd_party/simd_utils': checked out 'fe9fa82c9d7e6297913bc6c98fe079acc6e157e9'
Submodule path 'src/3rd_party/simple-websocket-server': checked out '8909c57b5473cb95e197fa7f034edabb474535ba'
CMake Warning at CMakeLists.txt:89 (message):
  CMAKE_BUILD_TYPE not set; setting to Release


-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Building with -march=native and intrinsics will be chosen automatically by the compiler to match the current machine.
-- Checking support for CPU intrinsics
CMake Warning (dev) at CMakeLists.txt:386 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found CUDA: /usr/local/cuda (found suitable version "12.8", minimum required is "9.0")
-- CUDA_VERSION=12.8; CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
-- Compiling code for Pascal GPUs
-- Compiling code for Volta GPUs
-- Compiling code for Turing GPUs
-- Compiling code for Ampere GPUs
-- Compiling code for Ampere RTX GPUs
-- Found CUDA libraries: /usr/local/cuda/lib64/libcurand.so;/usr/local/cuda/lib64/libcusparse.so;/usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublasLt.so
-- Found TCMalloc: /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so
-- Found MKL: -Wl,--start-group;/usr/lib/x86_64-linux-gnu/libmkl_intel_ilp64.a;/usr/lib/x86_64-linux-gnu/libmkl_sequential.a;/usr/lib/x86_64-linux-gnu/libmkl_core.a;-Wl,--end-group
CMake Deprecation Warning at src/3rd_party/intgemm/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- VERSION: 0.1.94
-- Found TCMalloc: /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done (24.5s)
-- Generating done (0.1s)
-- Build files have been written to: /kaggle/working/marian-dev/build
[  0%] Building CXX object src/CMakeFiles/marian_avx2.dir/tensors/cpu/mjdgemm/mjdgemm_avx2.cpp.o
[  0%] Building CXX object src/3rd_party/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o
[  0%] Building CXX object src/CMakeFiles/marian_sse4_2.dir/tensors/cpu/mjdgemm/mjdgemm_sse4_2.cpp.o
[  1%] Building CXX object src/CMakeFiles/marian_avx512.dir/tensors/cpu/mjdgemm/mjdgemm_avx512.cpp.o
[  2%] Building CXX object src/3rd_party/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/unicode_script.cc.o
[  2%] Built target marian_sse4_2
[  2%] Building CXX object src/3rd_party/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/trainer_factory.cc.o
[  2%] Building CXX object src/CMakeFiles/marian_avx512.dir/layers/lsh_avx512popcnt.cpp.o
[  2%] Built target marian_avx2
[  2%] Building CXX object src/3rd_party/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/trainer_interface.cc.o
[  2%] Generating /kaggle/working/marian-dev/src/common/git_revision.h
[  2%] Built target marian_version
[  3%] Building CXX object src/3rd_party/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/unigram_model_trainer.cc.o
[  3%] Creating directories for 'nccl_install'
[  3%] No download step for 'nccl_install'
[  3%] No update step for 'nccl_install'
[  4%] No patch step for 'nccl_install'
[  4%] No configure step for 'nccl_install'
[  5%] Performing build step for 'nccl_install'
Generating nccl.h.in                           > /kaggle/working/marian-dev/build/local/include/nccl.h
Grabbing   include/nccl_net.h                  > /kaggle/working/marian-dev/build/local/include/nccl_net.h
Generating nccl.pc.in                          > /kaggle/working/marian-dev/build/local/lib/pkgconfig/nccl.pc
Compiling  init.cc                             > /kaggle/working/marian-dev/build/local/obj/init.o
Compiling  channel.cc                          > /kaggle/working/marian-dev/build/local/obj/channel.o
Compiling  bootstrap.cc                        > /kaggle/working/marian-dev/build/local/obj/bootstrap.o
Compiling  transport.cc                        > /kaggle/working/marian-dev/build/local/obj/transport.o
Compiling  enqueue.cc                          > /kaggle/working/marian-dev/build/local/obj/enqueue.o
[  5%] Building CXX object src/3rd_party/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/word_model_trainer.cc.o
In file included from include/core.h:54,
                 from include/transport.h:13,
                 from include/comm.h:10,
                 from include/enqueue.h:10,
                 from enqueue.cc:7:
enqueue.cc: In function ‘ncclResult_t ncclLaunchCooperativeKernelMultiDevice(cudaLaunchParams*, int*, int, int)’:
enqueue.cc:73:53: warning: ‘cudaError_t cudaLaunchCooperativeKernelMultiDevice(cudaLaunchParams*, unsigned int, unsigned int)’ is deprecated []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
   73 |     CUDACHECK(cudaLaunchCooperativeKernelMultiDevice(paramsList, numDevices,
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
   74 |             // These flags are to reduce the latency of using this API
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   75 |             cudaCooperativeLaunchMultiDeviceNoPreSync|cudaCooperativeLaunchMultiDeviceNoPostSync));
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/checks.h:14:23: note: in definition of macro ‘CUDACHECK’
   14 |     cudaError_t err = cmd;                                  \
      |                       ^~~
In file included from /usr/local/cuda/include/channel_descriptor.h:61,
                 from /usr/local/cuda/include/cuda_runtime.h:94,
                 from /kaggle/working/marian-dev/build/local/include/nccl.h:10,
                 from include/devcomm.h:10,
                 from include/transport.h:10:
/usr/local/cuda/include/cuda_runtime_api.h:4733:57: note: declared here
 4733 | extern __CUDA_DEPRECATED __host__ cudaError_t CUDARTAPI cudaLaunchCooperativeKernelMultiDevice(struct cudaLaunchParams *launchParamsList, unsigned int numDevices, unsigned int flags  __dv(0));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
enqueue.cc: In function ‘ncclResult_t ncclCpuBarrierOut(ncclComm*)’:
enqueue.cc:178:48: warning: ‘int pthread_yield()’ is deprecated: pthread_yield is deprecated, use sched_yield instead []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  178 |   while (*ptr < comm->intraRanks) pthread_yield();
      |                                   ~~~~~~~~~~~~~^~
In file included from /usr/include/features.h:502,

In [2]:
!/kaggle/working/marian-dev/build/marian --version
!/kaggle/working/marian-dev/build/marian-decoder --version

v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
v1.12.43 c9f287db 2025-06-23 19:47:45 +0000

In [3]:
import os

# Define Marian paths
MARIAN_BUILD = "/kaggle/working/marian-dev/build"
MARIAN = f"{MARIAN_BUILD}/marian"
MARIAN_DECODER = f"{MARIAN_BUILD}/marian-decoder"
MARIAN_VOCAB = f"{MARIAN_BUILD}/marian-vocab"

# Install sacrebleu and sentencepiece for evaluation & tokenization
!pip install -q sacrebleu sentencepiece

# Create directories for models and vocabularies
!mkdir -p /kaggle/working/models/seq2seq
!mkdir -p /kaggle/working/models/transformer
!mkdir -p /kaggle/working/models/ensemble
!mkdir -p /kaggle/working/data
!mkdir -p /kaggle/working/output/seq2seq
!mkdir -p /kaggle/working/output/transformer
!mkdir -p /kaggle/working/output/ensemble
!mkdir -p /kaggle/working/config/seq2seq/hi2my
!mkdir -p /kaggle/working/config/seq2seq/my2hi
!mkdir -p /kaggle/working/config/transformer/hi2my
!mkdir -p /kaggle/working/config/transformer/my2hi
!mkdir -p /kaggle/working/config/ensemble/hi2my
!mkdir -p /kaggle/working/config/ensemble/my2hi

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 5.6 MB/s eta 0:00:00

In [4]:
%cd /kaggle/working/data

!wget https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/test.hi
!wget https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/test.my
!wget https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/train.hi
!wget https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/train.my
!wget https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/valid.hi
!wget https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/valid.my
!wget https://raw.githubusercontent.com/ye-kyaw-thu/sylbreak4all/refs/heads/main/python/sylbreak4all.py

/kaggle/working/data
--2026-10-15 14:23:27--  https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/test.hi
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24117 (24K) [text/plain]
Saving to: ‘test.hi’

test.hi             100%[===================>]  23.55K  --.-KB/s    in 0.003s

2026-10-15 14:23:28 (8.84 MB/s) - ‘test.hi’ saved [24117/24117]

--2026-10-15 14:23:28--  https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/test.my
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29994 (29K) [text/plain]
Saving to: ‘test.my’

test.my             100%[===================>]  29.29K  --.-KB/s    in 0.003s

2026-10-15 14:23:28 (8.64 MB/s) - ‘test.my’ saved [29994/29994]

--2026-10-15 14:23:28--  https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/train.hi
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 412919 (403K) [text/plain]
Saving to: ‘train.hi’

train.hi            100%[===================>] 403.24K  --.-KB/s    in 0.04s

2026-10-15 14:23:28 (10.3 MB/s) - ‘train.hi’ saved [412919/412919]

--2026-10-15 14:23:28--  https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/train.my
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 502978 (491K) [text/plain]
Saving to: ‘train.my’

train.my            100%[===================>] 491.19K  --.-KB/s    in 0.04s

2026-10-15 14:23:29 (13.5 MB/s) - ‘train.my’ saved [502978/502978]

--2026-10-15 14:23:29--  https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/valid.hi
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48906 (48K) [text/plain]
Saving to: ‘valid.hi’

valid.hi            100%[===================>]  47.76K  --.-KB/s    in 0.01s

2026-10-15 14:23:29 (4.48 MB/s) - ‘valid.hi’ saved [48906/48906]

--2026-10-15 14:23:29--  https://raw.githubusercontent.com/ye-kyaw-thu/AIE-F-B2/main/assignment/assignment-6/myhi_data/valid.my
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 57890 (57K) [text/plain]
Saving to: ‘valid.my’

valid.my            100%[===================>]  56.53K  --.-KB/s    in 0.01s

2026-10-15 14:23:30 (4.33 MB/s) - ‘valid.my’ saved [57890/57890]

--2026-10-15 14:23:30--  https://raw.githubusercontent.com/ye-kyaw-thu/sylbreak4all/refs/heads/main/python/sylbreak4all.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4796 (4.7K) [text/plain]
Saving to: ‘sylbreak4all.py’

sylbreak4all.py     100%[===================>]   4.68K  --.-KB/s    in 0s

2026-10-15 14:23:30 (64.2 MB/s) - ‘sylbreak4all.py’ saved [4796/4796]

In [5]:
import sentencepiece as spm
# Train Hieroglyph tokenizer
spm.SentencePieceTrainer.train(
  input='/kaggle/working/data/train.hi',
  model_prefix='hi_spm',
  vocab_size=4000,
  character_coverage=1.0,
  model_type='bpe'
)

# Train Burmese tokenizer
spm.SentencePieceTrainer.train(
  input='/kaggle/working/data/train.my',
  model_prefix='my_spm',
  vocab_size=8000,
  character_coverage=0.999,
  model_type='bpe'
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1792074218.513300      49 sentencepiece_trainer.cc:105] Starts training with :
trainer_spec {
  input: /kaggle/working/data/train.hi
  input_format:
  model_prefix: hi_spm
  model_type: BPE
  vocab_size: 4000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
I0000 00:00:1792074218.514670      49 trainer_interface.cc:364] SentenceIterator is not specified. Using MultiFileSentenceIterator.
I0000 00:00:1792074218.514709      49 trainer_interface.cc:193] Loading corpus: /kaggle/working/data/train.hi
I0000 00:00:1792074218.518150      49 trainer_interface.cc:422] Loaded all 8500 sentences
I0000 00:00:1792074218.518427      49 trainer_interface.cc:440] Adding meta_piece: <unk>
I0000 00:00:1792074218.518441      49 trainer_interface.cc:440] Adding meta_piece: <s>
I0000 00:00:1792074218.518448      49 trainer_interface.cc:440] Adding meta_piece: </s>
I0000 00:00:1792074218.518463      49 trainer_interface.cc:445] Normalizing sentences...
I0000 00:00:1792074218.530703      49 trainer_interface.cc:555] all chars count=123356
I0000 00:00:1792074218.530785      49 trainer_interface.cc:578] Alphabet size=37
I0000 00:00:1792074218.530789      49 trainer_interface.cc:579] Final character coverage=1
I0000 00:00:1792074218.537658      49 trainer_interface.cc:609] Done! preprocessed 8500 sentences.
I0000 00:00:1792074218.537682      49 trainer_interface.cc:615] Tokenizing input sentences with whitespace: 8500
I0000 00:00:1792074218.542702      49 trainer_interface.cc:626] Done! 2858
I0000 00:00:1792074218.555023      49 bpe_model_trainer.cc:321] Added: freq=928 size=20 all=817 active=779 piece=𓂝𓇌
I0000 00:00:1792074218.555621      49 bpe_model_trainer.cc:321] Added: freq=533 size=40 all=1194 active=1156 piece=▁𓎜𓀀
I0000 00:00:1792074218.556235      49 bpe_model_trainer.cc:321] Added: freq=304 size=60 all=1606 active=1568 piece=▁𓏏𓄿𓈙
I0000 00:00:1792074218.556707      49 bpe_model_trainer.cc:321] Added: freq=228 size=80 all=1989 active=1951 piece=▁𓇋𓂝
I0000 00:00:1792074218.557138      49 bpe_model_trainer.cc:321] Added: freq=170 size=100 all=2264 active=2226 piece=▁𓈖
I0000 00:00:1792074218.557498      49 bpe_model_trainer.cc:321] Added: freq=141 size=120 all=2499 active=2461 piece=▁𓄿𓉔
I0000 00:00:1792074218.557805      49 bpe_model_trainer.cc:321] Added: freq=114 size=140 all=2694 active=2656 piece=𓂋𓂧
I0000 00:00:1792074218.558179      49 bpe_model_trainer.cc:321] Added: freq=87 size=160 all=2916 active=2878 piece=▁𓐍𓎛𓂝
I0000 00:00:1792074218.558392      49 bpe_model_trainer.cc:321] Added: freq=76 size=180 all=3044 active=3006 piece=𓄿𓆑𓎛
I0000 00:00:1792074218.558624      49 bpe_model_trainer.cc:321] Added: freq=69 size=200 all=3179 active=3141 piece=▁𓂋𓂝𓈎𓈙
I0000 00:00:1792074218.558935      49 bpe_model_trainer.cc:321] Added: freq=58 size=220 all=3352 active=3314 piece=▁𓇌𓂝
I0000 00:00:1792074218.559172      49 bpe_model_trainer.cc:321] Added: freq=52 size=240 all=3474 active=3436 piece=𓎡𓇌
I0000 00:00:1792074218.559454      49 bpe_model_trainer.cc:321] Added: freq=47 size=260 all=3617 active=3579 piece=▁𓇋𓄿𓏭𓈖
I0000 00:00:1792074218.559661      49 bpe_model_trainer.cc:321] Added: freq=43 size=280 all=3731 active=3693 piece=▁𓅓𓐍𓇋
I0000 00:00:1792074218.559847      49 bpe_model_trainer.cc:321] Added: freq=40 size=300 all=3839 active=3801 piece=𓀀𓎡𓈙
I0000 00:00:1792074218.560018      49 bpe_model_trainer.cc:321] Added: freq=36 size=320 all=3916 active=3878 piece=▁𓄿𓏏
I0000 00:00:1792074218.560165      49 bpe_model_trainer.cc:321] Added: freq=33 size=340 all=4001 active=3963 piece=𓆒𓀀
I0000 00:00:1792074218.560359      49 bpe_model_trainer.cc:321] Added: freq=32 size=360 all=4113 active=4075 piece=▁𓏏𓆑𓎛
I0000 00:00:1792074218.560566      49 bpe_model_trainer.cc:321] Added: freq=30 size=380 all=4215 active=4177 piece=▁𓏭𓋴𓂧
I0000 00:00:1792074218.560705      49 bpe_model_trainer.cc:321] Added: freq=27 size=400 all=4282 active=4244 piece=𓄿𓃀
I0000 00:00:1792074218.560876      49 bpe_model_trainer.cc:321] Added: freq=26 size=420 all=4365 active=4327 piece=▁𓉔𓆑𓎛𓂝
I0000 00:00:1792074218.561040      49 bpe_model_trainer.cc:321] Added: freq=24 size=440 all=4428 active=4390 piece=𓄿𓎛𓈖
I0000 00:00:1792074218.561184      49 bpe_model_trainer.cc:321] Added: freq=23 size=460 all=4495 active=4457 piece=▁𓏮𓀀𓐍𓈖
I0000 00:00:1792074218.561320      49 bpe_model_trainer.cc:321] Added: freq=21 size=480 all=4552 active=4514 piece=𓄿𓋴𓉔
I0000 00:00:1792074218.561447      49 bpe_model_trainer.cc:321] Added: freq=21 size=500 all=4599 active=4561 piece=▁𓇌𓐍𓏭𓈎𓐍𓋴
I0000 00:00:1792074218.561577      49 bpe_model_trainer.cc:321] Added: freq=19 size=520 all=4645 active=4607 piece=▁𓈖𓆑𓇌
I0000 00:00:1792074218.561684      49 bpe_model_trainer.cc:321] Added: freq=18 size=540 all=4689 active=4651 piece=▁𓊪𓂝𓄿𓋴
I0000 00:00:1792074218.561787      49 bpe_model_trainer.cc:321] Added: freq=17 size=560 all=4729 active=4691 piece=▁𓇌𓆑𓂝
I0000 00:00:1792074218.561888      49 bpe_model_trainer.cc:321] Added: freq=16 size=580 all=4763 active=4725 piece=𓎡𓋴𓂝
I0000 00:00:1792074218.561968      49 bpe_model_trainer.cc:321] Added: freq=16 size=600 all=4785 active=4747 piece=▁𓅲𓀀𓋴𓃀𓂝𓈎
I0000 00:00:1792074218.562118      49 bpe_model_trainer.cc:321] Added: freq=15 size=620 all=4849 active=4811 piece=▁𓅱𓆑𓈙𓊪
I0000 00:00:1792074218.562221      49 bpe_model_trainer.cc:321] Added: freq=14 size=640 all=4866 active=4828 piece=𓐍𓈙𓂝
I0000 00:00:1792074218.562294      49 bpe_model_trainer.cc:321] Added: freq=14 size=660 all=4873 active=4835 piece=▁𓏭𓊪𓂝𓏭𓈖
I0000 00:00:1792074218.562405      49 bpe_model_trainer.cc:321] Added: freq=13 size=680 all=4905 active=4867 piece=𓉔𓂝𓋴
I0000 00:00:1792074218.562512      49 bpe_model_trainer.cc:321] Added: freq=13 size=700 all=4952 active=4914 piece=▁𓇋𓐍𓈎𓊪
I0000 00:00:1792074218.562617      49 bpe_model_trainer.cc:321] Added: freq=12 size=720 all=4980 active=4942 piece=𓎡𓉔𓄡
I0000 00:00:1792074218.562724      49 bpe_model_trainer.cc:321] Added: freq=12 size=740 all=5008 active=4970 piece=▁𓎛𓄿𓉔𓂝
I0000 00:00:1792074218.562833      49 bpe_model_trainer.cc:321] Added: freq=11 size=760 all=5060 active=5022 piece=𓃀𓂝𓇌
I0000 00:00:1792074218.562952      49 bpe_model_trainer.cc:321] Added: freq=11 size=780 all=5102 active=5064 piece=▁𓉔𓆑𓂋𓈖
I0000 00:00:1792074218.563045      49 bpe_model_trainer.cc:321] Added: freq=11 size=800 all=5108 active=5070 piece=▁𓄿𓎛𓂧𓇋𓐍𓇌𓂧
I0000 00:00:1792074218.563198      49 bpe_model_trainer.cc:321] Added: freq=10 size=820 all=5158 active=5120 piece=𓈖𓂝𓇌
I0000 00:00:1792074218.563362      49 bpe_model_trainer.cc:321] Added: freq=10 size=840 all=5192 active=5154 piece=▁𓂋𓐍𓎛𓃀
I0000 00:00:1792074218.563429      49 bpe_model_trainer.cc:321] Added: freq=10 size=860 all=5188 active=5150 piece=▁𓎛𓂝𓂝𓇌𓈙
I0000 00:00:1792074218.563541      49 bpe_model_trainer.cc:321] Added: freq=9 size=880 all=5222 active=5184 piece=𓆑𓆓𓂝
I0000 00:00:1792074218.563770      49 bpe_model_trainer.cc:321] Added: freq=9 size=900 all=5258 active=5220 piece=▁𓈚𓀀𓎛𓃀
I0000 00:00:1792074218.563829      49 bpe_model_trainer.cc:321] Added: freq=9 size=920 all=5254 active=5216 piece=▁𓏭𓂋𓂝𓄿𓋴
I0000 00:00:1792074218.563940      49 bpe_model_trainer.cc:321] Added: freq=8 size=940 all=5287 active=5249 piece=𓂝𓄿𓂋
I0000 00:00:1792074218.564082      49 bpe_model_trainer.cc:321] Added: freq=8 size=960 all=5334 active=5296 piece=▁𓈙𓎡𓄡
I0000 00:00:1792074218.564169      49 bpe_model_trainer.cc:321] Added: freq=8 size=980 all=5353 active=5315 piece=▁𓇋𓆑𓋴𓇌
I0000 00:00:1792074218.564224      49 bpe_model_trainer.cc:321] Added: freq=8 size=1000 all=5344 active=5306 piece=▁𓏏𓋴𓆑𓈎𓂝
I0000 00:00:1792074218.564320      49 bpe_model_trainer.cc:321] Added: freq=7 size=1020 all=5351 active=5313 piece=𓃀𓄿𓂋
I0000 00:00:1792074218.564466      49 bpe_model_trainer.cc:321] Added: freq=7 size=1040 all=5385 active=5347 piece=▁𓈎𓂝𓋴
I0000 00:00:1792074218.564578      49 bpe_model_trainer.cc:321] Added: freq=7 size=1060 all=5406 active=5368 piece=▁𓇌𓄿𓎛𓏭
I0000 00:00:1792074218.564676      49 bpe_model_trainer.cc:321] Added: freq=7 size=1080 all=5412 active=5374 piece=▁𓈎𓂝𓋴𓋴𓆑
I0000 00:00:1792074218.564725      49 bpe_model_trainer.cc:321] Added: freq=7 size=1100 all=5403 active=5365 piece=▁𓏏𓐍𓋴𓈖𓂝𓇌
I0000 00:00:1792074218.564806      49 bpe_model_trainer.cc:321] Added: freq=6 size=1120 all=5406 active=5368 piece=▁𓈙𓆑
I0000 00:00:1792074218.564934      49 bpe_model_trainer.cc:321] Added: freq=6 size=1140 all=5447 active=5409 piece=▁𓃀𓐍𓇌
I0000 00:00:1792074218.565050      49 bpe_model_trainer.cc:321] Added: freq=6 size=1160 all=5479 active=5441 piece=𓆑𓋴𓈎𓂧
I0000 00:00:1792074218.565145      49 bpe_model_trainer.cc:321] Added: freq=6 size=1180 all=5488 active=5450 piece=▁𓈖𓂝𓂧𓈙
I0000 00:00:1792074218.565231      49 bpe_model_trainer.cc:321] Added: freq=6 size=1200 all=5495 active=5457 piece=▁𓄡𓄿𓋴𓆑𓈙
I0000 00:00:1792074218.565288      49 bpe_model_trainer.cc:321] Added: freq=6 size=1220 all=5487 active=5449 piece=▁𓄿𓅱𓋴𓄿𓆑𓇌
I0000 00:00:1792074218.565344      49 bpe_model_trainer.cc:321] Added: freq=6 size=1240 all=5472 active=5434 piece=▁𓏮𓀀𓐍𓈖𓆑𓎛𓃀
I0000 00:00:1792074218.565444      49 bpe_model_trainer.cc:321] Added: freq=5 size=1260 all=5488 active=5450 piece=𓄿𓎛𓈙
I0000 00:00:1792074218.565574      49 bpe_model_trainer.cc:321] Added: freq=5 size=1280 all=5525 active=5487 piece=▁𓆑𓎛𓎼
I0000 00:00:1792074218.565667      49 bpe_model_trainer.cc:321] Added: freq=5 size=1300 all=5552 active=5514 piece=𓂝𓎛𓏭𓂝
I0000 00:00:1792074218.565773      49 bpe_model_trainer.cc:321] Added: freq=5 size=1320 all=5566 active=5528 piece=▁𓄿𓂋𓋴𓂝
I0000 00:00:1792074218.565837      49 bpe_model_trainer.cc:321] Added: freq=5 size=1340 all=5564 active=5526 piece=▁𓈙𓎡𓆑𓈎
I0000 00:00:1792074218.565911      49 bpe_model_trainer.cc:321] Added: freq=5 size=1360 all=5570 active=5532 piece=▁𓂋𓄿𓈎𓂝𓋴
I0000 00:00:1792074218.565964      49 bpe_model_trainer.cc:321] Added: freq=5 size=1380 all=5565 active=5527 piece=▁𓊪𓂝𓋴𓂝𓈙
I0000 00:00:1792074218.566037      49 bpe_model_trainer.cc:321] Added: freq=5 size=1400 all=5553 active=5515 piece=▁𓈙𓂝𓏮𓀀𓎛𓇌
I0000 00:00:1792074218.566091      49 bpe_model_trainer.cc:321] Added: freq=5 size=1420 all=5536 active=5498 piece=▁𓎡𓎛𓂋𓎡𓏭𓈖𓂧
I0000 00:00:1792074218.566130      49 bpe_model_trainer.cc:321] Added: freq=5 size=1440 all=5517 active=5479 piece=▁𓂝𓎼𓂝𓋴𓂧𓇋𓐍𓇌𓂧𓈙
I0000 00:00:1792074218.566261      49 bpe_model_trainer.cc:321] Added: freq=4 size=1460 all=5557 active=5519 piece=𓄿𓋴𓈙
I0000 00:00:1792074218.566389      49 bpe_model_trainer.cc:321] Added: freq=4 size=1480 all=5589 active=5551 piece=▁𓄡𓄿𓎛
I0000 00:00:1792074218.566475      49 bpe_model_trainer.cc:321] Added: freq=4 size=1500 all=5600 active=5562 piece=▁𓎡𓎛𓇌
I0000 00:00:1792074218.566584      49 bpe_model_trainer.cc:321] Added: freq=4 size=1520 all=5618 active=5580 piece=𓎡𓈎𓂝𓇌
I0000 00:00:1792074218.566660      49 bpe_model_trainer.cc:321] Added: freq=4 size=1540 all=5618 active=5580 piece=▁𓇋𓄿𓇋𓂧
I0000 00:00:1792074218.566729      49 bpe_model_trainer.cc:321] Added: freq=4 size=1560 all=5616 active=5578 piece=▁𓋴𓎡𓈎𓊪
I0000 00:00:1792074218.566827      49 bpe_model_trainer.cc:321] Added: freq=4 size=1580 all=5623 active=5585 piece=𓏭𓈎𓎡𓄿𓂋
I0000 00:00:1792074218.566892      49 bpe_model_trainer.cc:321] Added: freq=4 size=1600 all=5615 active=5577 piece=▁𓈎𓏏𓆑𓎛𓈙
I0000 00:00:1792074218.566951      49 bpe_model_trainer.cc:321] Added: freq=4 size=1620 all=5606 active=5568 piece=▁𓏭𓊪𓂝𓈙𓈙
I0000 00:00:1792074218.567025      49 bpe_model_trainer.cc:321] Added: freq=4 size=1640 all=5595 active=5557 piece=▁𓇌𓂝𓏭𓆑𓇌𓂝
I0000 00:00:1792074218.567072      49 bpe_model_trainer.cc:321] Added: freq=4 size=1660 all=5581 active=5543 piece=▁𓂝𓎛𓃀𓂋𓆑𓈙𓊪
I0000 00:00:1792074218.567129      49 bpe_model_trainer.cc:321] Added: freq=4 size=1680 all=5563 active=5525 piece=▁𓊪𓂝𓄿𓂋𓈎𓊪𓂧
I0000 00:00:1792074218.567176      49 bpe_model_trainer.cc:321] Added: freq=4 size=1700 all=5545 active=5507 piece=▁𓂝𓎼𓂝𓋴𓂨𓀀𓎛𓂝𓈙
I0000 00:00:1792074218.567271      49 bpe_model_trainer.cc:321] Added: freq=3 size=1720 all=5558 active=5520 piece=▁𓈗𓀀
I0000 00:00:1792074218.567406      49 bpe_model_trainer.cc:321] Added: freq=3 size=1740 all=5587 active=5549 piece=𓋴𓆑𓇋
I0000 00:00:1792074218.567518      49 bpe_model_trainer.cc:321] Added: freq=3 size=1760 all=5603 active=5565 piece=▁𓄡𓐍𓂋
I0000 00:00:1792074218.567594      49 bpe_model_trainer.cc:321] Added: freq=3 size=1780 all=5610 active=5572 piece=▁𓉔𓐍𓇌
I0000 00:00:1792074218.567829      49 bpe_model_trainer.cc:321] Added: freq=3 size=1800 all=5625 active=5587 piece=𓆑𓏭𓂝𓈙
I0000 00:00:1792074218.567891      49 bpe_model_trainer.cc:321] Added: freq=3 size=1820 all=5637 active=5599 piece=▁𓃀𓋴𓂝𓏏
I0000 00:00:1792074218.567969      49 bpe_model_trainer.cc:321] Added: freq=3 size=1840 all=5631 active=5593 piece=▁𓈙𓄿𓂧𓈙
I0000 00:00:1792074218.568051      49 bpe_model_trainer.cc:321] Added: freq=3 size=1860 all=5629 active=5591 piece=▁𓏮𓀀𓄡𓈙
I0000 00:00:1792074218.568156      49 bpe_model_trainer.cc:321] Added: freq=3 size=1880 all=5637 active=5599 piece=▁𓄡𓂋𓄿𓂧𓈙
I0000 00:00:1792074218.568202      49 bpe_model_trainer.cc:321] Added: freq=3 size=1900 all=5626 active=5588 piece=▁𓈎𓐍𓎡𓃀𓊪
I0000 00:00:1792074218.568252      49 bpe_model_trainer.cc:321] Added: freq=3 size=1920 all=5615 active=5577 piece=▁𓎼𓐍𓈎𓂝𓇌
I0000 00:00:1792074218.568338      49 bpe_model_trainer.cc:321] Added: freq=3 size=1940 all=5608 active=5570 piece=▁𓄡𓂝𓐍𓄡𓂋𓂝
I0000 00:00:1792074218.568376      49 bpe_model_trainer.cc:321] Added: freq=3 size=1960 all=5592 active=5554 piece=▁𓈙𓈖𓆑𓆑𓎛𓃀
I0000 00:00:1792074218.568417      49 bpe_model_trainer.cc:321] Added: freq=3 size=1980 all=5576 active=5538 piece=▁𓏭𓄿𓎛𓎜𓀀𓈎
I0000 00:00:1792074218.568483      49 bpe_model_trainer.cc:321] Added: freq=3 size=2000 all=5564 active=5526 piece=▁𓆑𓃀𓎜𓀀𓋴𓂝𓇌
I0000 00:00:1792074218.568525      49 bpe_model_trainer.cc:321] Added: freq=3 size=2020 all=5546 active=5508 piece=▁𓋴𓂝𓈙𓏭𓊪𓂝𓇌
I0000 00:00:1792074218.568570      49 bpe_model_trainer.cc:321] Added: freq=3 size=2040 all=5530 active=5492 piece=▁𓈙𓈎𓄿𓋴𓎼𓆑𓎛𓃀
I0000 00:00:1792074218.568678      49 bpe_model_trainer.cc:321] Added: freq=3 size=2060 all=5510 active=5472 piece=▁𓋴𓂝𓈙𓆑𓂋𓆑𓂝𓎛𓈎
I0000 00:00:1792074218.568802      49 bpe_model_trainer.cc:321] Added: freq=2 size=2080 all=5523 active=5485 piece=▁𓂧𓄿
I0000 00:00:1792074218.568911      49 bpe_model_trainer.cc:321] Added: freq=2 size=2100 all=5544 active=5506 piece=𓅓𓄿𓉔
I0000 00:00:1792074218.569049      49 bpe_model_trainer.cc:321] Added: freq=2 size=2120 all=5566 active=5528 piece=𓎼𓆑𓂋
I0000 00:00:1792074218.569141      49 bpe_model_trainer.cc:321] Added: freq=2 size=2140 all=5580 active=5542 piece=▁𓄿𓇌𓅓
I0000 00:00:1792074218.569218      49 bpe_model_trainer.cc:321] Added: freq=2 size=2160 all=5584 active=5546 piece=▁𓈙𓊃𓎡
I0000 00:00:1792074218.569290      49 bpe_model_trainer.cc:321] Added: freq=2 size=2180 all=5583 active=5545 piece=𓂋𓐍𓎡𓈙
I0000 00:00:1792074218.569405      49 bpe_model_trainer.cc:321] Added: freq=2 size=2200 all=5595 active=5557 piece=𓆓𓆑𓎛𓃀
I0000 00:00:1792074218.569517      49 bpe_model_trainer.cc:321] Added: freq=2 size=2220 all=5608 active=5570 piece=𓏭𓂝𓈙𓈙
I0000 00:00:1792074218.569578      49 bpe_model_trainer.cc:321] Added: freq=2 size=2240 all=5601 active=5563 piece=▁𓃀𓂝𓎛𓈎
I0000 00:00:1792074218.569639      49 bpe_model_trainer.cc:321] Added: freq=2 size=2260 all=5596 active=5558 piece=▁𓆑𓈎𓄿𓂋
I0000 00:00:1792074218.569706      49 bpe_model_trainer.cc:321] Added: freq=2 size=2280 all=5591 active=5553 piece=▁𓈎𓊪𓋴𓐍
I0000 00:00:1792074218.569764      49 bpe_model_trainer.cc:321] Added: freq=2 size=2300 all=5581 active=5543 piece=▁𓉔𓂝𓎛𓈎
I0000 00:00:1792074218.569819      49 bpe_model_trainer.cc:321] Added: freq=2 size=2320 all=5570 active=5532 piece=▁𓎛𓂝𓋴𓇌
I0000 00:00:1792074218.569892      49 bpe_model_trainer.cc:321] Added: freq=2 size=2340 all=5566 active=5528 piece=𓂝𓎛𓆑𓎛𓃀
I0000 00:00:1792074218.570026      49 bpe_model_trainer.cc:321] Added: freq=2 size=2360 all=5578 active=5540 piece=▁𓂋𓆑𓉔𓆑𓈎
I0000 00:00:1792074218.570085      49 bpe_model_trainer.cc:321] Added: freq=2 size=2380 all=5567 active=5529 piece=▁𓄿𓇌𓉔𓆑𓈎
I0000 00:00:1792074218.570131      49 bpe_model_trainer.cc:321] Added: freq=2 size=2400 all=5554 active=5516 piece=▁𓇋𓎡𓆑𓂋𓈎
I0000 00:00:1792074218.570165      49 bpe_model_trainer.cc:321] Added: freq=2 size=2420 all=5540 active=5502 piece=▁𓈙𓂝𓂋𓂋𓈙
I0000 00:00:1792074218.570214      49 bpe_model_trainer.cc:321] Added: freq=2 size=2440 all=5526 active=5488 piece=▁𓉔𓐍𓇌𓂝𓂋
I0000 00:00:1792074218.570277      49 bpe_model_trainer.cc:321] Added: freq=2 size=2460 all=5517 active=5479 piece=▁𓏏𓊪𓆑𓈎𓂝
I0000 00:00:1792074218.570371      49 bpe_model_trainer.cc:321] Added: freq=2 size=2480 all=5515 active=5477 piece=𓎼𓆑𓎛𓏭𓂝𓇌
I0000 00:00:1792074218.570428      49 bpe_model_trainer.cc:321] Added: freq=2 size=2500 all=5505 active=5467 piece=▁𓄿𓇋𓐍𓄿𓋴𓇌
I0000 00:00:1792074218.570473      49 bpe_model_trainer.cc:321] Added: freq=2 size=2520 all=5491 active=5453 piece=▁𓇋𓂝𓊪𓄿𓎼𓂝
I0000 00:00:1792074218.570517      49 bpe_model_trainer.cc:321] Added: freq=2 size=2540 all=5473 active=5435 piece=▁𓈙𓄡𓂝𓂝𓏭𓊪
I0000 00:00:1792074218.570558      49 bpe_model_trainer.cc:321] Added: freq=2 size=2560 all=5457 active=5419 piece=▁𓊪𓆑𓈙𓈎𓐍𓋴
I0000 00:00:1792074218.570609      49 bpe_model_trainer.cc:321] Added: freq=2 size=2580 all=5444 active=5406 piece=▁𓏭𓄿𓎛𓇌𓂋𓂝
I0000 00:00:1792074218.570687      49 bpe_model_trainer.cc:321] Added: freq=2 size=2600 all=5431 active=5393 piece=▁𓄡𓂋𓄿𓂧𓆑𓎛𓃀
I0000 00:00:1792074218.570742      49 bpe_model_trainer.cc:321] Added: freq=2 size=2620 all=5413 active=5375 piece=▁𓅓𓐍𓃀𓃀𓆑𓎛𓃀
I0000 00:00:1792074218.570777      49 bpe_model_trainer.cc:321] Added: freq=2 size=2640 all=5393 active=5355 piece=▁𓈎𓂧𓄡𓆑𓏭𓄿𓂋
I0000 00:00:1792074218.570819      49 bpe_model_trainer.cc:321] Added: freq=2 size=2660 all=5374 active=5336 piece=▁𓉔𓂝𓎛𓈎𓆒𓀀𓎛
I0000 00:00:1792074218.570868      49 bpe_model_trainer.cc:321] Added: freq=2 size=2680 all=5355 active=5317 piece=▁𓏮𓀀𓂋𓂋𓂝𓃀𓂝
I0000 00:00:1792074218.570926      49 bpe_model_trainer.cc:321] Added: freq=2 size=2700 all=5336 active=5298 piece=▁𓇋𓂋𓎡𓅱𓅱𓆑𓎛𓃀
I0000 00:00:1792074218.570963      49 bpe_model_trainer.cc:321] Added: freq=2 size=2720 all=5318 active=5280 piece=▁𓊃𓎡𓆑𓈎𓈎𓆑𓎛𓃀
I0000 00:00:1792074218.571018      49 bpe_model_trainer.cc:321] Added: freq=2 size=2740 all=5300 active=5262 piece=▁𓃀𓐍𓐍𓇌𓎛𓆑𓃀𓊪𓈎
I0000 00:00:1792074218.571064      49 bpe_model_trainer.cc:321] Added: freq=2 size=2760 all=5280 active=5242 piece=▁𓉔𓄿𓈚𓀀𓏭𓊪𓆑𓈙𓈎
I0000 00:00:1792074218.571111      49 bpe_model_trainer.cc:321] Added: freq=2 size=2780 all=5261 active=5223 piece=▁𓉔𓂝𓇌𓆑𓈎𓄿𓈎𓆑𓎛𓃀
I0000 00:00:1792074218.571182      49 bpe_model_trainer.cc:321] Added: freq=1 size=2800 all=5258 active=5220 piece=𓄿𓍿
I0000 00:00:1792074218.571273      49 bpe_model_trainer.cc:321] Added: freq=1 size=2820 all=5266 active=5228 piece=𓏭𓋴
I0000 00:00:1792074218.571356      49 bpe_model_trainer.cc:321] Added: freq=1 size=2840 all=5273 active=5235 piece=𓂋𓆑𓃀
I0000 00:00:1792074218.571428      49 bpe_model_trainer.cc:321] Added: freq=1 size=2860 all=5280 active=5242 piece=𓃀𓃀𓂧

True

In [6]:
import sentencepiece as spm

# Initialize SentencePiece processors
hi_spm = spm.SentencePieceProcessor(model_file="hi_spm.model")
my_spm = spm.SentencePieceProcessor(model_file="my_spm.model")


def encode_file(input_path, output_path, sp_processor):
  with open(input_path, "r", encoding="utf-8") as f_in, open(
      output_path, "w", encoding="utf-8"
  ) as f_out:
    for line in f_in:
      pieces = sp_processor.encode(line.strip(), out_type=str)
      f_out.write(" ".join(pieces) + "\n")


# Process train, validation, and test splits
splits = ["train", "valid", "test"]
for split in splits:
  encode_file(
      f"/kaggle/working/data/{split}.hi",
      f"/kaggle/working/data/{split}.hi.spm",
      hi_spm,
  )
  encode_file(
      f"/kaggle/working/data/{split}.my",
      f"/kaggle/working/data/{split}.my.spm",
      my_spm,
  )

print("All datasets successfully encoded into subwords!")

All datasets successfully encoded into subwords!

In [7]:
# Generate vocabularies for source (Hieroglyph) and target (Burmese)
MARIAN_VOCAB="/kaggle/working/marian-dev/build/marian-vocab"

!{MARIAN_VOCAB} < /kaggle/working/data/train.hi.spm > /kaggle/working/data/hi.vocab.yml
!{MARIAN_VOCAB} < /kaggle/working/data/train.my.spm > /kaggle/working/data/my.vocab.yml

[2026-10-15 14:24:07] Creating vocabulary...
[2026-10-15 14:24:07] [data] Creating vocabulary stdout from stdin
[2026-10-15 14:24:07] Finished
[2026-10-15 14:24:08] Creating vocabulary...
[2026-10-15 14:24:08] [data] Creating vocabulary stdout from stdin
[2026-10-15 14:24:08] Finished

In [8]:
%%writefile /kaggle/working/config/transformer/hi2my/config.yml
# Device and Model Settings
devices: [0]
model: /kaggle/working/models/transformer/hi-my.npz
type: transformer

# Training Corpora
train-sets:
  - /kaggle/working/data/train.hi.spm
  - /kaggle/working/data/train.my.spm
vocabs:
  - /kaggle/working/data/hi.vocab.yml
  - /kaggle/working/data/my.vocab.yml

# Validation Settings
valid-sets:
  - /kaggle/working/data/valid.hi.spm
  - /kaggle/working/data/valid.my.spm
valid-freq: 100
valid-metrics: [cross-entropy,bleu]
early-stopping: 15

# Optimization & Hyperparameters (Corrected Marian Keys)
after-batches: 5000
mini-batch-words: 2048
workspace: 4096
optimizer: adam
learn-rate: 0.0003
lr-warmup: 4000
lr-decay-inv-sqrt: 4000
label-smoothing: 0.1

# Regularization
dropout-rnn: 0.2
dropout-src: 0.2
dropout-trg: 0.2
transformer-dropout: 0.2

# Corrected Architecture Parameters
transformer-heads: 4
dim-emb: 512
transformer-dim-ffn: 2048
enc-depth: 4
dec-depth: 4

Writing /kaggle/working/config/transformer/hi2my/config.yml

In [20]:
MARIAN_TRAIN="/kaggle/working/marian-dev/build/marian"
!{MARIAN_TRAIN} --config /kaggle/working/config/transformer/hi2my/config.yml

[2026-10-15 15:35:35] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:35:35] [marian] Running on f2fe76130532 as process 18643 with command line:
[2026-10-15 15:35:35] [marian] /kaggle/working/marian-dev/build/marian --config /kaggle/working/config/transformer/hi2my/config.yml
[2026-10-15 15:35:35] [config] after: 0e
[2026-10-15 15:35:35] [config] after-batches: 5000
[2026-10-15 15:35:35] [config] after-epochs: 0
[2026-10-15 15:35:35] [config] all-caps-every: 0
[2026-10-15 15:35:35] [config] allow-unk: false
[2026-10-15 15:35:35] [config] authors: false
[2026-10-15 15:35:35] [config] beam-size: 12
[2026-10-15 15:35:35] [config] bert-class-symbol: "[CLS]"
[2026-10-15 15:35:35] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 15:35:35] [config] bert-masking-fraction: 0.15
[2026-10-15 15:35:35] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 15:35:35] [config] bert-train-type-embeddings: true
[2026-10-15 15:35:35] [config] bert-type-vocab-size: 2
[2026-10-15 15:35:35] [config] build-info: ""
[2026-10-15 15:35:35] [config] check-gradient-nan: false
[2026-10-15 15:35:35] [config] check-nan: false
[2026-10-15 15:35:35] [config] cite: false
[2026-10-15 15:35:35] [config] clip-norm: 1
[2026-10-15 15:35:35] [config] comet-augment-bad: 0
[2026-10-15 15:35:35] [config] comet-dropout: 0.1
[2026-10-15 15:35:35] [config] comet-final-sigmoid: false
[2026-10-15 15:35:35] [config] comet-mix: false
[2026-10-15 15:35:35] [config] comet-mix-norm: false
[2026-10-15 15:35:35] [config] comet-mix-transformation: softmax
[2026-10-15 15:35:35] [config] comet-mixup: 0
[2026-10-15 15:35:35] [config] comet-mixup-reg: false
[2026-10-15 15:35:35] [config] comet-pool: avg
[2026-10-15 15:35:35] [config] comet-pooler-ffn:
[2026-10-15 15:35:35] [config]   - 2048
[2026-10-15 15:35:35] [config]   - 1024
[2026-10-15 15:35:35] [config] comet-prepend-zero: false
[2026-10-15 15:35:35] [config] comet-stop-grad: false
[2026-10-15 15:35:35] [config] comet-use-separator: false
[2026-10-15 15:35:35] [config] cost-scaling:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] cost-type: ce-sum
[2026-10-15 15:35:35] [config] cpu-threads: 0
[2026-10-15 15:35:35] [config] custom-fallbacks:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] data-threads: 8
[2026-10-15 15:35:35] [config] data-weighting: ""
[2026-10-15 15:35:35] [config] data-weighting-type: sentence
[2026-10-15 15:35:35] [config] dec-cell: gru
[2026-10-15 15:35:35] [config] dec-cell-base-depth: 2
[2026-10-15 15:35:35] [config] dec-cell-high-depth: 1
[2026-10-15 15:35:35] [config] dec-depth: 4
[2026-10-15 15:35:35] [config] devices:
[2026-10-15 15:35:35] [config]   - 0
[2026-10-15 15:35:35] [config] dim-emb: 512
[2026-10-15 15:35:35] [config] dim-rnn: 1024
[2026-10-15 15:35:35] [config] dim-vocabs:
[2026-10-15 15:35:35] [config]   - 0
[2026-10-15 15:35:35] [config]   - 0
[2026-10-15 15:35:35] [config] disp-first: 0
[2026-10-15 15:35:35] [config] disp-freq: 1000u
[2026-10-15 15:35:35] [config] disp-label-counts: true
[2026-10-15 15:35:35] [config] dropout-rnn: 0.2
[2026-10-15 15:35:35] [config] dropout-src: 0.2
[2026-10-15 15:35:35] [config] dropout-trg: 0.2
[2026-10-15 15:35:35] [config] dump-config: ""
[2026-10-15 15:35:35] [config] dynamic-gradient-scaling:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] early-stopping: 15
[2026-10-15 15:35:35] [config] early-stopping-epsilon:
[2026-10-15 15:35:35] [config]   - 0
[2026-10-15 15:35:35] [config] early-stopping-on: first
[2026-10-15 15:35:35] [config] embedding-fix-src: false
[2026-10-15 15:35:35] [config] embedding-fix-trg: false
[2026-10-15 15:35:35] [config] embedding-normalization: false
[2026-10-15 15:35:35] [config] embedding-vectors:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] enc-cell: gru
[2026-10-15 15:35:35] [config] enc-cell-depth: 1
[2026-10-15 15:35:35] [config] enc-depth: 4
[2026-10-15 15:35:35] [config] enc-type: bidirectional
[2026-10-15 15:35:35] [config] english-title-case-every: 0
[2026-10-15 15:35:35] [config] exponential-smoothing: 0
[2026-10-15 15:35:35] [config] exponential-smoothing-replace-freq: 0
[2026-10-15 15:35:35] [config] factor-weight: 1
[2026-10-15 15:35:35] [config] factors-combine: sum
[2026-10-15 15:35:35] [config] factors-dim-emb: 0
[2026-10-15 15:35:35] [config] gradient-checkpointing: false
[2026-10-15 15:35:35] [config] gradient-norm-average-window: 100
[2026-10-15 15:35:35] [config] guided-alignment: none
[2026-10-15 15:35:35] [config] guided-alignment-cost: ce
[2026-10-15 15:35:35] [config] guided-alignment-weight: 0.1
[2026-10-15 15:35:35] [config] ignore-model-config: false
[2026-10-15 15:35:35] [config] input-join-fields: false
[2026-10-15 15:35:35] [config] input-reorder:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] input-types:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] interpolate-env-vars: false
[2026-10-15 15:35:35] [config] keep-best: false
[2026-10-15 15:35:35] [config] label-smoothing: 0.1
[2026-10-15 15:35:35] [config] layer-normalization: false
[2026-10-15 15:35:35] [config] learn-rate: 0.0003
[2026-10-15 15:35:35] [config] lemma-dependency: ""
[2026-10-15 15:35:35] [config] lemma-dim-emb: 0
[2026-10-15 15:35:35] [config] log: ""
[2026-10-15 15:35:35] [config] log-level: info
[2026-10-15 15:35:35] [config] log-time-zone: ""
[2026-10-15 15:35:35] [config] logical-epoch:
[2026-10-15 15:35:35] [config]   - 1e
[2026-10-15 15:35:35] [config]   - 0
[2026-10-15 15:35:35] [config] lr-decay: 0
[2026-10-15 15:35:35] [config] lr-decay-freq: 50000
[2026-10-15 15:35:35] [config] lr-decay-inv-sqrt:
[2026-10-15 15:35:35] [config]   - 4000
[2026-10-15 15:35:35] [config] lr-decay-repeat-warmup: false
[2026-10-15 15:35:35] [config] lr-decay-reset-optimizer: false
[2026-10-15 15:35:35] [config] lr-decay-start:
[2026-10-15 15:35:35] [config]   - 10
[2026-10-15 15:35:35] [config]   - 1
[2026-10-15 15:35:35] [config] lr-decay-strategy: epoch+stalled
[2026-10-15 15:35:35] [config] lr-report: false
[2026-10-15 15:35:35] [config] lr-warmup: 4000
[2026-10-15 15:35:35] [config] lr-warmup-at-reload: false
[2026-10-15 15:35:35] [config] lr-warmup-cycle: false
[2026-10-15 15:35:35] [config] lr-warmup-start-rate: 0
[2026-10-15 15:35:35] [config] max-length: 50
[2026-10-15 15:35:35] [config] max-length-crop: false
[2026-10-15 15:35:35] [config] max-length-factor: 3
[2026-10-15 15:35:35] [config] maxi-batch: 100
[2026-10-15 15:35:35] [config] maxi-batch-sort: trg
[2026-10-15 15:35:35] [config] mini-batch: 64
[2026-10-15 15:35:35] [config] mini-batch-fit: false
[2026-10-15 15:35:35] [config] mini-batch-fit-step: 10
[2026-10-15 15:35:35] [config] mini-batch-round-up: true
[2026-10-15 15:35:35] [config] mini-batch-track-lr: false
[2026-10-15 15:35:35] [config] mini-batch-warmup: 0
[2026-10-15 15:35:35] [config] mini-batch-words: 2048
[2026-10-15 15:35:35] [config] mini-batch-words-ref: 0
[2026-10-15 15:35:35] [config] model: /kaggle/working/models/transformer/hi-my.npz
[2026-10-15 15:35:35] [config] multi-loss-type: sum
[2026-10-15 15:35:35] [config] n-best: false
[2026-10-15 15:35:35] [config] no-nccl: false
[2026-10-15 15:35:35] [config] no-optimizer-reload: false
[2026-10-15 15:35:35] [config] no-reload: false
[2026-10-15 15:35:35] [config] no-restore-corpus: false
[2026-10-15 15:35:35] [config] no-spm-encode: false
[2026-10-15 15:35:35] [config] normalize: 0
[2026-10-15 15:35:35] [config] normalize-gradient: false
[2026-10-15 15:35:35] [config] normalize-gradient-by-ratio: false
[2026-10-15 15:35:35] [config] optimizer: adam
[2026-10-15 15:35:35] [config] optimizer-delay: 1
[2026-10-15 15:35:35] [config] optimizer-params:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] output-omit-bias: false
[2026-10-15 15:35:35] [config] overwrite: false
[2026-10-15 15:35:35] [config] overwrite-checkpoint: true
[2026-10-15 15:35:35] [config] precision:
[2026-10-15 15:35:35] [config]   - float32
[2026-10-15 15:35:35] [config]   - float32
[2026-10-15 15:35:35] [config] pretrained-model: ""
[2026-10-15 15:35:35] [config] quantize-biases: false
[2026-10-15 15:35:35] [config] quantize-bits: 0
[2026-10-15 15:35:35] [config] quantize-log-based: false
[2026-10-15 15:35:35] [config] quantize-optimization-steps: 0
[2026-10-15 15:35:35] [config] quiet: false
[2026-10-15 15:35:35] [config] quiet-translation: false
[2026-10-15 15:35:35] [config] quiet-validation: false
[2026-10-15 15:35:35] [config] relative-paths: false
[2026-10-15 15:35:35] [config] right-left: false
[2026-10-15 15:35:35] [config] save-freq: 10000u
[2026-10-15 15:35:35] [config] seed: 0
[2026-10-15 15:35:35] [config] sentencepiece-alphas:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] sentencepiece-max-lines: 2000000
[2026-10-15 15:35:35] [config] sentencepiece-options: ""
[2026-10-15 15:35:35] [config] separator-symbol: "[eos]"
[2026-10-15 15:35:35] [config] sharding: global
[2026-10-15 15:35:35] [config] shuffle: data
[2026-10-15 15:35:35] [config] shuffle-in-ram: false
[2026-10-15 15:35:35] [config] sigterm: save-and-exit
[2026-10-15 15:35:35] [config] skip: false
[2026-10-15 15:35:35] [config] sqlite: ""
[2026-10-15 15:35:35] [config] sqlite-drop: false
[2026-10-15 15:35:35] [config] sync-freq: 200u
[2026-10-15 15:35:35] [config] sync-sgd: false
[2026-10-15 15:35:35] [config] tempdir: /tmp
[2026-10-15 15:35:35] [config] throw-on-divergence:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] tied-embeddings: false
[2026-10-15 15:35:35] [config] tied-embeddings-all: false
[2026-10-15 15:35:35] [config] tied-embeddings-src: false
[2026-10-15 15:35:35] [config] train-embedder-rank:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] train-sets:
[2026-10-15 15:35:35] [config]   - /kaggle/working/data/train.hi.spm
[2026-10-15 15:35:35] [config]   - /kaggle/working/data/train.my.spm
[2026-10-15 15:35:35] [config] transformer-aan-activation: swish
[2026-10-15 15:35:35] [config] transformer-aan-depth: 2
[2026-10-15 15:35:35] [config] transformer-aan-nogate: false
[2026-10-15 15:35:35] [config] transformer-alibi-shift: false
[2026-10-15 15:35:35] [config] transformer-alibi-trainable: false
[2026-10-15 15:35:35] [config] transformer-attention-mask: default
[2026-10-15 15:35:35] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 15:35:35] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 15:35:35] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 15:35:35] [config] transformer-depth-scaling: false
[2026-10-15 15:35:35] [config] transformer-dim-aan: 2048
[2026-10-15 15:35:35] [config] transformer-dim-ffn: 2048
[2026-10-15 15:35:35] [config] transformer-disable-position-embeddings: false
[2026-10-15 15:35:35] [config] transformer-dropout: 0.2
[2026-10-15 15:35:35] [config] transformer-dropout-attention: 0
[2026-10-15 15:35:35] [config] transformer-dropout-ffn: 0
[2026-10-15 15:35:35] [config] transformer-ffn-activation: swish
[2026-10-15 15:35:35] [config] transformer-ffn-depth: 2
[2026-10-15 15:35:35] [config] transformer-guided-alignment-layer: last
[2026-10-15 15:35:35] [config] transformer-heads: 4
[2026-10-15 15:35:35] [config] transformer-no-affine: false
[2026-10-15 15:35:35] [config] transformer-no-bias: false
[2026-10-15 15:35:35] [config] transformer-no-projection: false
[2026-10-15 15:35:35] [config] transformer-pool: false
[2026-10-15 15:35:35] [config] transformer-postprocess: dan
[2026-10-15 15:35:35] [config] transformer-postprocess-emb: d
[2026-10-15 15:35:35] [config] transformer-postprocess-top: ""
[2026-10-15 15:35:35] [config] transformer-preprocess: ""
[2026-10-15 15:35:35] [config] transformer-rnn-projection: false
[2026-10-15 15:35:35] [config] transformer-tied-layers:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] transformer-train-position-embeddings: false
[2026-10-15 15:35:35] [config] tsv: false
[2026-10-15 15:35:35] [config] tsv-fields: 0
[2026-10-15 15:35:35] [config] type: transformer
[2026-10-15 15:35:35] [config] ulr: false
[2026-10-15 15:35:35] [config] ulr-dim-emb: 0
[2026-10-15 15:35:35] [config] ulr-dropout: 0
[2026-10-15 15:35:35] [config] ulr-keys-vectors: ""
[2026-10-15 15:35:35] [config] ulr-query-vectors: ""
[2026-10-15 15:35:35] [config] ulr-softmax-temperature: 1
[2026-10-15 15:35:35] [config] ulr-trainable-transformation: false
[2026-10-15 15:35:35] [config] unlikelihood-loss: false
[2026-10-15 15:35:35] [config] valid-freq: 100
[2026-10-15 15:35:35] [config] valid-log: ""
[2026-10-15 15:35:35] [config] valid-max-length: 1000
[2026-10-15 15:35:35] [config] valid-metrics:
[2026-10-15 15:35:35] [config]   - cross-entropy
[2026-10-15 15:35:35] [config]   - bleu
[2026-10-15 15:35:35] [config] valid-mini-batch: 32
[2026-10-15 15:35:35] [config] valid-reset-all: false
[2026-10-15 15:35:35] [config] valid-reset-stalled: false
[2026-10-15 15:35:35] [config] valid-script-args:
[2026-10-15 15:35:35] [config]   []
[2026-10-15 15:35:35] [config] valid-script-path: ""
[2026-10-15 15:35:35] [config] valid-sets:
[2026-10-15 15:35:35] [config]   - /kaggle/working/data/valid.hi.spm
[2026-10-15 15:35:35] [config]   - /kaggle/working/data/valid.my.spm
[2026-10-15 15:35:35] [config] valid-translation-output: ""
[2026-10-15 15:35:35] [config] vocabs:
[2026-10-15 15:35:35] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:35:35] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 15:35:35] [config] word-penalty: 0
[2026-10-15 15:35:35] [config] word-scores: false
[2026-10-15 15:35:35] [config] workspace: 4096
[2026-10-15 15:35:35] [config] Model is being created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:35:35] [training] Using single-device training
[2026-10-15 15:35:35] [comm] Compiled without MPI support. Running as a single process on f2fe76130532
[2026-10-15 15:35:35] Synced seed 1792078535
[2026-10-15 15:35:35] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:35:35] [data] Setting vocabulary size for input 0 to 2,988
[2026-10-15 15:35:35] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 15:35:35] [data] Setting vocabulary size for input 1 to 6,014
[2026-10-15 15:35:35] [memory] Extending reserved space to 4096 MB (device gpu0)
[2026-10-15 15:35:35] [comm] Using NCCL 2.8.3 for GPU communication
[2026-10-15 15:35:35] [comm] Using global sharding
[2026-10-15 15:35:35] [comm] NCCLCommunicators constructed successfully
[2026-10-15 15:35:35] [training] Using 1 GPUs
[2026-10-15 15:35:35] Training started
[2026-10-15 15:35:35] [data] Shuffling data
[2026-10-15 15:35:35] [data] Done reading 8,500 sentences
[2026-10-15 15:35:36] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:36] [training] Batches are processed as 1 process(es) x 1 devices/process
[2026-10-15 15:35:36] [logits] Applying loss function for 1 factor(s)
[2026-10-15 15:35:36] [memory] Reserving 141 MB, device gpu0
[2026-10-15 15:35:36] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 15:35:36] [memory] Reserving 141 MB, device gpu0
[2026-10-15 15:35:36] Parameter type float32, optimization type float32, casting types false
[2026-10-15 15:35:36] Allocating memory for Adam-specific shards
[2026-10-15 15:35:36] [memory] Reserving 283 MB, device gpu0
[2026-10-15 15:35:38] Seen 8,500 samples
[2026-10-15 15:35:38] Starting data epoch 2 in logical epoch 2
[2026-10-15 15:35:38] [data] Shuffling data
[2026-10-15 15:35:38] [data] Done reading 8,500 sentences
[2026-10-15 15:35:38] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:39] Seen 8,500 samples
[2026-10-15 15:35:39] Starting data epoch 3 in logical epoch 3
[2026-10-15 15:35:39] [data] Shuffling data
[2026-10-15 15:35:39] [data] Done reading 8,500 sentences
[2026-10-15 15:35:39] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:41] Seen 8,500 samples
[2026-10-15 15:35:41] Starting data epoch 4 in logical epoch 4
[2026-10-15 15:35:41] [data] Shuffling data
[2026-10-15 15:35:41] [data] Done reading 8,500 sentences
[2026-10-15 15:35:41] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:43] Seen 8,500 samples
[2026-10-15 15:35:43] Starting data epoch 5 in logical epoch 5
[2026-10-15 15:35:43] [data] Shuffling data
[2026-10-15 15:35:43] [data] Done reading 8,500 sentences
[2026-10-15 15:35:43] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:45] Seen 8,500 samples
[2026-10-15 15:35:45] Starting data epoch 6 in logical epoch 6
[2026-10-15 15:35:45] [data] Shuffling data
[2026-10-15 15:35:45] [data] Done reading 8,500 sentences
[2026-10-15 15:35:45] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:46] [valid] Ep. 6 : Up. 100 : cross-entropy : 31.186 : new best
[2026-10-15 15:35:46] Translating validation set...
[2026-10-15 15:35:46] [valid] References contain unknown word, metric scores may be inaccurate
[2026-10-15 15:35:46] [valid] First sentence's tokens as scored:
[2026-10-15 15:35:46] [valid] DefaultVocab keeps original segments for scoring
[2026-10-15 15:35:46] [valid]   Hyp:
[2026-10-15 15:35:46] [valid]   Ref: ▁ဒါက <unk> <unk> <unk> <unk> သွား တဲ့ လမ်းပါ။
[2026-10-15 15:35:46] Best translation 0 :
[2026-10-15 15:35:46] Best translation 1 :
[2026-10-15 15:35:46] Best translation 2 :
[2026-10-15 15:35:46] Best translation 3 :
[2026-10-15 15:35:46] Best translation 4 :
[2026-10-15 15:35:46] Best translation 5 :
[2026-10-15 15:35:46] Best translation 10 :
[2026-10-15 15:35:46] Best translation 20 :
[2026-10-15 15:35:46] Best translation 40 :
[2026-10-15 15:35:46] Best translation 80 :
[2026-10-15 15:35:46] Best translation 160 :
[2026-10-15 15:35:46] Best translation 320 :
[2026-10-15 15:35:46] Best translation 640 :
[2026-10-15 15:35:46] Total translation time: 0.31477s
[2026-10-15 15:35:46] [valid] Ep. 6 : Up. 100 : bleu : 0 : new best
[2026-10-15 15:35:47] Seen 8,500 samples
[2026-10-15 15:35:47] Starting data epoch 7 in logical epoch 7
[2026-10-15 15:35:47] [data] Shuffling data
[2026-10-15 15:35:47] [data] Done reading 8,500 sentences
[2026-10-15 15:35:47] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:49] Seen 8,500 samples
[2026-10-15 15:35:49] Starting data epoch 8 in logical epoch 8
[2026-10-15 15:35:49] [data] Shuffling data
[2026-10-15 15:35:49] [data] Done reading 8,500 sentences
[2026-10-15 15:35:49] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:51] Seen 8,500 samples
[2026-10-15 15:35:51] Starting data epoch 9 in logical epoch 9
[2026-10-15 15:35:51] [data] Shuffling data
[2026-10-15 15:35:51] [data] Done reading 8,500 sentences
[2026-10-15 15:35:51] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:53] Seen 8,500 samples
[2026-10-15 15:35:53] Starting data epoch 10 in logical epoch 10
[2026-10-15 15:35:53] [data] Shuffling data
[2026-10-15 15:35:53] [data] Done reading 8,500 sentences
[2026-10-15 15:35:53] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:55] Seen 8,500 samples
[2026-10-15 15:35:55] Starting data epoch 11 in logical epoch 11
[2026-10-15 15:35:55] [data] Shuffling data
[2026-10-15 15:35:55] [data] Done reading 8,500 sentences
[2026-10-15 15:35:55] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:35:56] [valid] Ep. 11 : Up. 200 : cross-entropy : 27.4244 : new best
[2026-10-15 15:35:56] Translating validation set...
[2026-10-15 15:35:56] Best translation 0 :
[2026-10-15 15:35:56] Best translation 1 :
[2026-10-15 15:35:56] Best translation 2 :
[2026-10-15 15:35:56] Best translation 3 :
[2026-10-15 15:35:56] Best translation 4 :
[2026-10-15 15:35:56] Best translation 5 :
[2026-10-15 15:35:56] Best translation 10 :
[2026-10-15 15:35:56] Best translation 20 :
[2026-10-15 15:35:56] Best translation 40 :
[2026-10-15 15:35:56] Best translation 80 :
[2026-10-15 15:35:56] Best translation 160 :

In [21]:
MARIAN_DECODER="/kaggle/working/marian-dev/build/marian-decoder"

!{MARIAN_DECODER} \
  --models /kaggle/working/models/transformer/hi-my.npz \
  --vocabs /kaggle/working/data/hi.vocab.yml /kaggle/working/data/my.vocab.yml \
  --beam-size 12 \
  --normalize 1.0 \
  < /kaggle/working/data/test.hi.spm \
  > /kaggle/working/output/transformer/test.output.my.spm

[2026-10-15 15:44:49] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:44:49] [marian] Running on f2fe76130532 as process 18683 with command line:
[2026-10-15 15:44:49] [marian] /kaggle/working/marian-dev/build/marian-decoder --models /kaggle/working/models/transformer/hi-my.npz --vocabs /kaggle/working/data/hi.vocab.yml /kaggle/working/data/my.vocab.yml --beam-size 12 --normalize 1.0
[2026-10-15 15:44:49] [config] alignment: ""
[2026-10-15 15:44:49] [config] allow-special: false
[2026-10-15 15:44:49] [config] allow-unk: false
[2026-10-15 15:44:49] [config] authors: false
[2026-10-15 15:44:49] [config] beam-size: 12
[2026-10-15 15:44:49] [config] bert-class-symbol: "[CLS]"
[2026-10-15 15:44:49] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 15:44:49] [config] bert-masking-fraction: 0.15
[2026-10-15 15:44:49] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 15:44:49] [config] bert-train-type-embeddings: true
[2026-10-15 15:44:49] [config] bert-type-vocab-size: 2
[2026-10-15 15:44:49] [config] best-deep: false
[2026-10-15 15:44:49] [config] build-info: ""
[2026-10-15 15:44:49] [config] check-nan: false
[2026-10-15 15:44:49] [config] cite: false
[2026-10-15 15:44:49] [config] comet-augment-bad: 0
[2026-10-15 15:44:49] [config] comet-dropout: 0.1
[2026-10-15 15:44:49] [config] comet-final-sigmoid: false
[2026-10-15 15:44:49] [config] comet-mix: false
[2026-10-15 15:44:49] [config] comet-mix-norm: false
[2026-10-15 15:44:49] [config] comet-mix-transformation: softmax
[2026-10-15 15:44:49] [config] comet-mixup: 0
[2026-10-15 15:44:49] [config] comet-mixup-reg: false
[2026-10-15 15:44:49] [config] comet-pool: avg
[2026-10-15 15:44:49] [config] comet-pooler-ffn:
[2026-10-15 15:44:49] [config]   - 2048
[2026-10-15 15:44:49] [config]   - 1024
[2026-10-15 15:44:49] [config] comet-prepend-zero: false
[2026-10-15 15:44:49] [config] comet-stop-grad: false
[2026-10-15 15:44:49] [config] comet-use-separator: false
[2026-10-15 15:44:49] [config] cpu-threads: 0
[2026-10-15 15:44:49] [config] data-threads: 8
[2026-10-15 15:44:49] [config] dec-cell: gru
[2026-10-15 15:44:49] [config] dec-cell-base-depth: 2
[2026-10-15 15:44:49] [config] dec-cell-high-depth: 1
[2026-10-15 15:44:49] [config] dec-depth: 4
[2026-10-15 15:44:49] [config] devices:
[2026-10-15 15:44:49] [config]   - 0
[2026-10-15 15:44:49] [config] dim-emb: 512
[2026-10-15 15:44:49] [config] dim-rnn: 1024
[2026-10-15 15:44:49] [config] dim-vocabs:
[2026-10-15 15:44:49] [config]   - 2988
[2026-10-15 15:44:49] [config]   - 6014
[2026-10-15 15:44:49] [config] dump-config: ""
[2026-10-15 15:44:49] [config] enc-cell: gru
[2026-10-15 15:44:49] [config] enc-cell-depth: 1
[2026-10-15 15:44:49] [config] enc-depth: 4
[2026-10-15 15:44:49] [config] enc-type: bidirectional
[2026-10-15 15:44:49] [config] factors-combine: sum
[2026-10-15 15:44:49] [config] factors-dim-emb: 0
[2026-10-15 15:44:49] [config] force-decode: false
[2026-10-15 15:44:49] [config] gemm-type: float32
[2026-10-15 15:44:49] [config] ignore-model-config: false
[2026-10-15 15:44:49] [config] input:
[2026-10-15 15:44:49] [config]   - stdin
[2026-10-15 15:44:49] [config] input-join-fields: false
[2026-10-15 15:44:49] [config] input-reorder:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] input-types:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] interpolate-env-vars: false
[2026-10-15 15:44:49] [config] layer-normalization: false
[2026-10-15 15:44:49] [config] lemma-dependency: ""
[2026-10-15 15:44:49] [config] lemma-dim-emb: 0
[2026-10-15 15:44:49] [config] log: ""
[2026-10-15 15:44:49] [config] log-level: info
[2026-10-15 15:44:49] [config] log-time-zone: ""
[2026-10-15 15:44:49] [config] max-length: 1000
[2026-10-15 15:44:49] [config] max-length-crop: false
[2026-10-15 15:44:49] [config] max-length-factor: 3
[2026-10-15 15:44:49] [config] maxi-batch: 1
[2026-10-15 15:44:49] [config] maxi-batch-sort: none
[2026-10-15 15:44:49] [config] mini-batch: 1
[2026-10-15 15:44:49] [config] mini-batch-words: 0
[2026-10-15 15:44:49] [config] model-mmap: false
[2026-10-15 15:44:49] [config] models:
[2026-10-15 15:44:49] [config]   - /kaggle/working/models/transformer/hi-my.npz
[2026-10-15 15:44:49] [config] n-best: false
[2026-10-15 15:44:49] [config] no-spm-decode: false
[2026-10-15 15:44:49] [config] no-spm-encode: false
[2026-10-15 15:44:49] [config] normalize: 1
[2026-10-15 15:44:49] [config] optimize: false
[2026-10-15 15:44:49] [config] output: stdout
[2026-10-15 15:44:49] [config] output-approx-knn:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] output-omit-bias: false
[2026-10-15 15:44:49] [config] output-sampling:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] precision:
[2026-10-15 15:44:49] [config]   - float32
[2026-10-15 15:44:49] [config] quantize-range: 0
[2026-10-15 15:44:49] [config] quiet: false
[2026-10-15 15:44:49] [config] quiet-translation: false
[2026-10-15 15:44:49] [config] relative-paths: false
[2026-10-15 15:44:49] [config] right-left: false
[2026-10-15 15:44:49] [config] seed: 0
[2026-10-15 15:44:49] [config] separator-symbol: "[eos]"
[2026-10-15 15:44:49] [config] shortlist:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] skip: false
[2026-10-15 15:44:49] [config] skip-cost: false
[2026-10-15 15:44:49] [config] stat-freq: 0
[2026-10-15 15:44:49] [config] tied-embeddings: false
[2026-10-15 15:44:49] [config] tied-embeddings-all: false
[2026-10-15 15:44:49] [config] tied-embeddings-src: false
[2026-10-15 15:44:49] [config] transformer-aan-activation: swish
[2026-10-15 15:44:49] [config] transformer-aan-depth: 2
[2026-10-15 15:44:49] [config] transformer-aan-nogate: false
[2026-10-15 15:44:49] [config] transformer-alibi-shift: false
[2026-10-15 15:44:49] [config] transformer-alibi-trainable: false
[2026-10-15 15:44:49] [config] transformer-attention-mask: default
[2026-10-15 15:44:49] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 15:44:49] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 15:44:49] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 15:44:49] [config] transformer-depth-scaling: false
[2026-10-15 15:44:49] [config] transformer-dim-aan: 2048
[2026-10-15 15:44:49] [config] transformer-dim-ffn: 2048
[2026-10-15 15:44:49] [config] transformer-disable-position-embeddings: false
[2026-10-15 15:44:49] [config] transformer-ffn-activation: swish
[2026-10-15 15:44:49] [config] transformer-ffn-depth: 2
[2026-10-15 15:44:49] [config] transformer-guided-alignment-layer: last
[2026-10-15 15:44:49] [config] transformer-heads: 4
[2026-10-15 15:44:49] [config] transformer-no-affine: false
[2026-10-15 15:44:49] [config] transformer-no-bias: false
[2026-10-15 15:44:49] [config] transformer-no-projection: false
[2026-10-15 15:44:49] [config] transformer-pool: false
[2026-10-15 15:44:49] [config] transformer-postprocess: dan
[2026-10-15 15:44:49] [config] transformer-postprocess-emb: d
[2026-10-15 15:44:49] [config] transformer-postprocess-top: ""
[2026-10-15 15:44:49] [config] transformer-preprocess: ""
[2026-10-15 15:44:49] [config] transformer-rnn-projection: false
[2026-10-15 15:44:49] [config] transformer-tied-layers:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] transformer-train-position-embeddings: false
[2026-10-15 15:44:49] [config] tsv: false
[2026-10-15 15:44:49] [config] tsv-fields: 0
[2026-10-15 15:44:49] [config] type: transformer
[2026-10-15 15:44:49] [config] ulr: false
[2026-10-15 15:44:49] [config] ulr-dim-emb: 0
[2026-10-15 15:44:49] [config] ulr-trainable-transformation: false
[2026-10-15 15:44:49] [config] version: v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:44:49] [config] vocabs:
[2026-10-15 15:44:49] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:44:49] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 15:44:49] [config] weights:
[2026-10-15 15:44:49] [config]   []
[2026-10-15 15:44:49] [config] word-penalty: 0
[2026-10-15 15:44:49] [config] word-scores: false
[2026-10-15 15:44:49] [config] workspace: 512
[2026-10-15 15:44:49] [config] Loaded model has been created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:44:49] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:44:49] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 15:44:49] Loading model from /kaggle/working/models/transformer/hi-my.npz
[2026-10-15 15:44:50] [memory] Extending reserved space to 512 MB (device gpu0)
[2026-10-15 15:44:50] Loaded model config
[2026-10-15 15:44:50] Loading scorer of type transformer as feature F0
[2026-10-15 15:44:50] [memory] Reserving 141 MB, device gpu0
[2026-10-15 15:44:50] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 15:44:50] Best translation 0 : ▁မင်းက ▁နာကျင်တယ်
[2026-10-15 15:44:50] Best translation 1 : ▁ကျွန်မမှာ ▁အစားအစာမရှိဘူး။
[2026-10-15 15:44:50] Best translation 2 : ▁ဘယ်သူမှ ▁ကျွန်မကို ▁မမြင်ခဲ့ဘူး။
[2026-10-15 15:44:50] Best translation 3 : ▁စောင့်ကြည့် နေသူပါ။
[2026-10-15 15:44:50] Best translation 4 : ▁သူက ▁အသင်း မှာပါ
[2026-10-15 15:44:50] Best translation 5 : ▁ခရီး ကောင်းပါ
[2026-10-15 15:44:50] Best translation 6 : ▁ဘယ်လို ပဲဖြစ်ဖြစ် ▁သွားမယ်။
[2026-10-15 15:44:50] Best translation 7 : ▁အခန်းက ▁ပူနေတယ်။
[2026-10-15 15:44:50] Best translation 8 : ▁Tom ▁ဟာ ▁ဖြည်းဖြည်းချင်း ▁လျှောက် နေတယ်။
[2026-10-15 15:44:50] Best translation 9 : ▁ဒါပဲ
[2026-10-15 15:44:50] Best translation 10 : ▁မင်းက ▁ကောင်းကောင်း ▁ခံစားရတယ်။
[2026-10-15 15:44:50] Best translation 11 : ▁ကျွန်မ သွားပါ
[2026-10-15 15:44:50] Best translation 12 : ▁ကျွန်မ ▁တာဝန်ရှိနေတယ်။
[2026-10-15 15:44:50] Best translation 13 : ▁ပိုများ မယ်လို့ ▁မျှော်လင့် ခဲ့တယ်။
[2026-10-15 15:44:50] Best translation 14 : ▁ကူညီပါရစေ။
[2026-10-15 15:44:50] Best translation 15 : ▁အံ့သြစရာတွေကို ▁ကြိုက်တယ်။
[2026-10-15 15:44:50] Best translation 16 : ▁သူမက ▁ကြိုးစားခဲ့တယ်။
[2026-10-15 15:44:50] Best translation 17 : ▁ကျွန်မက ▁ပုံပြင် တွေကို ▁ကြိုက်တယ်။
[2026-10-15 15:44:50] Best translation 18 : ▁ဂီတသံ ▁ကြားရတယ်။
[2026-10-15 15:44:50] Best translation 19 : ▁တစ်ခုခုကို ▁မြင်ခဲ့တယ်။
[2026-10-15 15:44:50] Best translation 20 : ▁ဒါက ▁ခွေးတစ်ကောင် ပါ။
[2026-10-15 15:44:50] Best translation 21 : ▁နွားနို့ ကို ▁မုန်းတယ်။
[2026-10-15 15:44:50] Best translation 22 : ▁သူ့မှာ ▁ခွေး နှစ်ကောင်ရှိတယ်။
[2026-10-15 15:44:50] Best translation 23 : ▁မိသားစု ဆိုတာ ▁မိသားစုပဲ
[2026-10-15 15:44:50] Best translation 24 : ▁သူမက ▁သူ့ကို ▁ချစ်တယ်။
[2026-10-15 15:44:50] Best translation 25 : ▁သူနာကျင် နေခဲ့တယ်။
[2026-10-15 15:44:50] Best translation 26 : ▁မလုပ်ချင်ဘူး။
[2026-10-15 15:44:50] Best translation 27 : ▁ကျွန်မက ▁ပေး နိုင်တယ်
[2026-10-15 15:44:50] Best translation 28 : ▁သိပ် ကောင်းပါတယ်။
[2026-10-15 15:44:50] Best translation 29 : ▁Tom ▁ကို ▁မေးပါ။
[2026-10-15 15:44:50] Best translation 30 : ▁ပြောတာကို ▁လုပ်ပါ။
[2026-10-15 15:44:50] Best translation 31 : ▁ဒါက ▁အချစ်လား။
[2026-10-15 15:44:50] Best translation 32 : ▁အားလုံး ▁သေကြရမယ်။
[2026-10-15 15:44:50] Best translation 33 : ▁မင်း ▁အရမ်းနောက်ကျ နေပြီ
[2026-10-15 15:44:50] Best translation 34 : ▁ဒါကို ▁မလုပ်နိုင်ဘူး။
[2026-10-15 15:44:51] Best translation 35 : ▁သူက ▁မင်းသား
[2026-10-15 15:44:51] Best translation 36 : ▁အရမ်း မှောင်နေတယ်။
[2026-10-15 15:44:51] Best translation 37 : ▁ဒါက ▁ချိန်းဆို မှု မဟုတ်ဘူး။
[2026-10-15 15:44:51] Best translation 38 : ▁ဒါကို ▁ငါလေး ခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 39 : ▁သူတို့က ▁ကျွန်တော်တို့ ▁ဘယ်မှာလဲ။
[2026-10-15 15:44:51] Best translation 40 : ▁သူမ ဟုတ်ဘူး။
[2026-10-15 15:44:51] Best translation 41 : ▁မင်းက ▁အရမ်းကို ▁ကောင်းတယ်။
[2026-10-15 15:44:51] Best translation 42 : ▁စိတ်ဝင်စား စရာပါ။
[2026-10-15 15:44:51] Best translation 43 : ▁ဒါက ▁မိုက်လိုက်တာ
[2026-10-15 15:44:51] Best translation 44 : ▁ကျွန်မက ▁ရိုးစင်းခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 45 : ▁အနားယူ ချိန်များ ▁ပြီးဆုံး
[2026-10-15 15:44:51] Best translation 46 : ▁သူက ▁ကျွန်မအ ရွယ် ပဲရှိပါသေးတယ်။
[2026-10-15 15:44:51] Best translation 47 : ▁အသစ်တစ်ခု ▁လိုတယ်။
[2026-10-15 15:44:51] Best translation 48 : ▁သူထွက်သွားပြီ
[2026-10-15 15:44:51] Best translation 49 : ▁ဖြစ်ပျက် ခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 50 : ▁သူဟာ ▁ချွေးထွက် လာခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 51 : ▁ကျွန်တော် ▁ကြည့်နေခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 52 : ▁သူ့ကို ▁လိုက်ခဲ့
[2026-10-15 15:44:51] Best translation 53 : ▁အားလုံးက ▁ရူးကြောင်ကြောင်
[2026-10-15 15:44:51] Best translation 54 : ▁ကျွန်တော်က ▁ငတုံးမဟုတ်ဘူး။
[2026-10-15 15:44:51] Best translation 55 : ▁သူအိမ်မှာ ▁မရှိဘူး။
[2026-10-15 15:44:51] Best translation 56 : ▁ကျွန်မပြော သလို ▁လုပ်ပါ။
[2026-10-15 15:44:51] Best translation 57 : ▁အားလုံး ▁အဆင်ပြေပါတယ်။
[2026-10-15 15:44:51] Best translation 58 : ▁အော်ဟစ်တာ ▁ရပ်လိုက်ပါ
[2026-10-15 15:44:51] Best translation 59 : ▁Tom ▁က ▁ရက်စက်တယ်။
[2026-10-15 15:44:51] Best translation 60 : ▁ပဟေ ဠ ိတွေကို ▁ကြိုက်တယ်။
[2026-10-15 15:44:51] Best translation 61 : ▁ဖတ်တတ်တယ်။
[2026-10-15 15:44:51] Best translation 62 : ▁ကျွန်မမှာ ▁ဘာရှိလဲ။
[2026-10-15 15:44:51] Best translation 63 : ▁လက်ဖက်ရည် သောက်ပါ။
[2026-10-15 15:44:51] Best translation 64 : ▁ကျွန်မတို့က ▁အကောင်းဆုံး တွေပါ။
[2026-10-15 15:44:51] Best translation 65 : ▁ရေခဲ တစ်လုံး ▁လိုတယ်။
[2026-10-15 15:44:51] Best translation 66 : ▁နေ့လည်စာ ▁အသင့်ရှိ ပြီလား။
[2026-10-15 15:44:51] Best translation 67 : ▁မိသားစု ဆိုတာ ▁မိသားစုပဲ
[2026-10-15 15:44:51] Best translation 68 : ▁မင်းက ▁အဆိုတော် မဟုတ်ဘူး။
[2026-10-15 15:44:51] Best translation 69 : ▁သူဟာ ▁ချွတ်ယွင်း နေပြီ။
[2026-10-15 15:44:51] Best translation 70 : ▁ကျွန်မ ▁အဆင်ပြေပါတယ်။
[2026-10-15 15:44:51] Best translation 71 : ▁နေ့ကောင်း တစ်ခုရှိပါစေ။
[2026-10-15 15:44:51] Best translation 72 : ▁ကောင်းပြီ၊ ▁တုံ့ ပြန်ပါ။
[2026-10-15 15:44:51] Best translation 73 : ▁တီဗွီကို ▁ဖွင့်လိုက်ပါ
[2026-10-15 15:44:51] Best translation 74 : ▁ကျွန်တော်က ▁လယ် သမားပါ။
[2026-10-15 15:44:51] Best translation 75 : ▁ကျွန်တော်ကတော့ ▁ဆန့်ကျင်ပါတယ်။
[2026-10-15 15:44:51] Best translation 76 : ▁ပါးစပ်က ▁တုံပြန် နေပြီ။
[2026-10-15 15:44:51] Best translation 77 : ▁ကျွန်မတို့ ▁ပြင်ဆင် ထားတယ်
[2026-10-15 15:44:51] Best translation 78 : ▁Tom ▁ဟာ ▁မြန်မြန်ပြေး နိုင်တယ်
[2026-10-15 15:44:51] Best translation 79 : ▁ဒါက ▁တောင်းပန် တယ်။
[2026-10-15 15:44:51] Best translation 80 : ▁တွေ့လိုက်တယ်
[2026-10-15 15:44:51] Best translation 81 : ▁ဘယ်သူမဆို ▁လုပ်ပေး မှာပါ။
[2026-10-15 15:44:51] Best translation 82 : ▁ကျွန်မ ▁အများကြီး ▁သောက်ခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 83 : ▁Toms ▁ဟာ ▁ဒေါသထွက်တယ်။
[2026-10-15 15:44:51] Best translation 84 : ▁ကျွန်မလည်း ▁ထင်တယ်။
[2026-10-15 15:44:51] Best translation 85 : ▁သူဟာ ▁မြန်မြန်ပြေး နိုင်တယ်
[2026-10-15 15:44:51] Best translation 86 : ▁ကြိုးကို ▁ဖြတ်လိုက်တယ်။
[2026-10-15 15:44:51] Best translation 87 : ▁ဒါကို ▁ခင်ဗျား လိုချင်လား။
[2026-10-15 15:44:51] Best translation 88 : ▁ချက်ချင်းလာပါ
[2026-10-15 15:44:51] Best translation 89 : ▁သူဟာ ▁ပါရီကို ▁ပျံသန်း ခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 90 : ▁ရှင်း ပြီလား။
[2026-10-15 15:44:51] Best translation 91 : ▁ကျွန်မ ▁ဆုံး ရှုံးခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 92 : ▁သူဟာ ▁အကူအညီမရ နိုင်ပါ။
[2026-10-15 15:44:51] Best translation 93 : ▁ကျွန်မ ▁မပြီးသေးဘူး။
[2026-10-15 15:44:51] Best translation 94 : ▁ကျွန်တော် ▁ဘာလုပ်ပေး နိုင်လဲ။
[2026-10-15 15:44:51] Best translation 95 : ▁ငါက ▁အကောင်းဆုံးပါ။
[2026-10-15 15:44:51] Best translation 96 : ▁ကျွန်မ ▁အရမ်းပင်ပန်း နေခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 97 : ▁အားလုံး ▁ခင်ဗျားကို ▁သဘောကျ ပါတယ်။
[2026-10-15 15:44:51] Best translation 98 : ▁သူမဟာ ▁အစာချေနေတာပါ။
[2026-10-15 15:44:51] Best translation 99 : ▁ဒါက ▁ပျော်စရာပါ။
[2026-10-15 15:44:51] Best translation 100 : ▁စိတ်ပျက် သွားခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 101 : ▁Tom ▁က ▁အော်
[2026-10-15 15:44:51] Best translation 102 : ▁မင်းက ▁သစ္စာဖောက် သူတွေပါ။
[2026-10-15 15:44:51] Best translation 103 : ▁လာပြီး ▁ကျွန်မတို့ နဲ့အတူပါ
[2026-10-15 15:44:51] Best translation 104 : ▁အင်္ဂ ါဂြိုဟ်ဟာ ▁ဂြိုဟ် တစ်လုံးပါ။
[2026-10-15 15:44:51] Best translation 105 : ▁လာ လို့ရတယ်
[2026-10-15 15:44:51] Best translation 106 : ▁ ၎ င်းရဲ့ ▁တစ်ခု တော့ဘူး။
[2026-10-15 15:44:51] Best translation 107 : ▁ဒါက ▁မမျှ ော်လင့် ပါနဲ့။
[2026-10-15 15:44:51] Best translation 108 : ▁အကူအညီ တွေလည်း ▁ရခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 109 : ▁သူက ▁အမဲလိုက်တာကို ▁ကြိုက်တယ်။
[2026-10-15 15:44:51] Best translation 110 : ▁ဒါကို ▁ကျွန်မသိပါတယ်။
[2026-10-15 15:44:51] Best translation 111 : ▁ဒီခွေးက ▁ငါ့ခွေး
[2026-10-15 15:44:51] Best translation 112 : ▁ဘတ်စ်ကား တိုင်း ▁ပြည့် ခဲ့တယ်။
[2026-10-15 15:44:51] Best translation 113 : ▁ဘယ်အချိန် လောက်မှာလဲ။
[2026-10-15 15:44:52] Best translation 114 : ▁ ၆ ▁နာရီမှာ
[2026-10-15 15:44:52] Best translation 115 : ▁ဒါကို ▁နှစ် ပိုင်းဖြတ် လိုက်ပါ
[2026-10-15 15:44:52] Best translation 116 : ▁နေ့လည်စာ စားချိန်ပါ။
[2026-10-15 15:44:52] Best translation 117 : ▁မင်းက ▁ပင်ပန်း ပုံပေါက်တယ်။
[2026-10-15 15:44:52] Best translation 118 : ▁တံခါးက ▁ဖွင့်ထားတယ်။
[2026-10-15 15:44:52] Best translation 119 : ▁ပျော်ခဲ့တယ်။
[2026-10-15 15:44:52] Best translation 120 : ▁မလုပ်ချင်ဘူး။
[2026-10-15 15:44:52] Best translation 121 : ▁နောက်ကျ တာအတွက် ▁စိတ်မကောင်း ပါဘူး။
[2026-10-15 15:44:52] Best translation 122 : ▁Tom ▁က ▁ဒါကို ▁လိုချင်ခဲ့တယ်။
[2026-10-15 15:44:52] Best translation 123 : ▁ဒီမှာ ▁ဘယ်သူ များရှိလဲ။
[2026-10-15 15:44:52] Best translation 124 : ▁မင်း ▁တစ်ယောက်တည်း လား။
[2026-10-15 15:44:52] Best translation 125 : ▁ကျွန်မမှာ ▁သံသယ တွေရှိတယ်
[2026-10-15 15:44:52] Best translation 126 : ▁ကျွန်တော် ▁အနိုင်ရခဲ့တယ်။
[2026-10-15 15:44:52] Best translation 127 : ▁မင်းက ▁ပျော် နေခဲ့တာ
[2026-10-15 15:44:52] Best translation 128 : ▁ကျွန်မ ▁အများကြီး ▁စားတယ်။
[2026-10-15 15:44:52] Best translation 129 : ▁မင်းက ▁အသားကျဉ်း မနေဘူး။
[2026-10-15 15:44:52] Best translation 130 : ▁ကျွန်မ ▁စိတ်မကောင်းဖြစ် မိတယ်။
[2026-10-15 15:44:52] Best translation 131 : ▁ကားလိုတယ်။
[2026-10-15 15:44:52] Best translation 132 : ▁Tom ▁က ▁အသက်ရှင် နေလား။
[2026-10-15 15:44:52] Best translation 133 : ▁ဒါဟာ ▁ကစားပွဲ မဟုတ်ဘူး။
[2026-10-15 15:44:52] Best translation 134 : ▁စိတ်ကူး တွေက ုန်သွားပြီ။
[2026-10-15 15:44:52] Best translation 135 : ▁မင်းနဲ့အတူ ▁မတက်နိုင်ဘူး။
[2026-10-15 15:44:52] Best translation 136 : ▁ကျွန်မ ▁ကြောက်လန့် ခဲ့တယ်။
[2026-10-15 15:44:52] Best translation 137 : ▁ကျွန်မတို့ အားလုံးမှာ ▁ကလေးတွေရှိတယ်
[2026-10-15 15:44:52] Best translation 138 : ▁ကံကောင်းပါစေ။
[2026-10-15 15:44:52] Best translation 139 : ▁ကျွန်မအပေါ် ▁ကျသွားတာက
[2026-10-15 15:44:52] Best translation 140 : ▁နိုးနေပြီ
[2026-10-15 15:44:52] Best translation 141 : ▁ဒါကို ▁ခင်ဗျား လိုချင်လား။
[2026-10-15 15:44:52] Best translation 142 : ▁သင်ဟာ ▁အနားယူ ဖို့လိုပါတယ်။
[2026-10-15 15:44:52] Best translation 143 : ▁သူရှင်သန် နိုင်မလား
[2026-10-15 15:44:52] Best translation 144 : ▁ဘယ်သူမှ ▁မသိဘူး။
[2026-10-15 15:44:52] Best translation 145 : ▁ကျွန်မ ▁လမ်းပျောက် နေခဲ့တယ်။
[2026-10-15 15:44:52] Best translation 146 : ▁Toms ▁ဘေးကင်းပါတယ်။
[2026-10-15 15:44:52] Best translation 147 : ▁Tom ▁က ▁ဂျင်းဘ ောင်းဘီ ဝတ်ထားတယ်။
[2026-10-15 15:44:52] Best translation 148 : ▁ဘာမှ မပြောခဲ့ဘူး။
[2026-10-15 15:44:52] Best translation 149 : ▁နေ့တိုင်း လာတယ်
[2026-10-15 15:44:52] Best translation 150 : ▁ဒါကို ▁မြှုပ် လိုက်တယ်။
[2026-10-15 15:44:52] Best translation 151 : ▁သူက ▁ဒီမှာ နေလား။
[2026-10-15 15:44:52] Best translation 152 : ▁မြင်နိုင်လား။
[2026-10-15 15:44:52] Best translation 153 : ▁ကျွန်မက ▁အရမ်းကို ▁တင်းကျပ် တယ်။
[2026-10-15 15:44:52] Best translation 154 : ▁စောင့် သင့်လား။
[2026-10-15 15:44:52] Best translation 155 : ▁သတိထားမိတယ်။
[2026-10-15 15:44:52] Best translation 156 : ▁ဒါက ▁ငွေတစ်လုံး တည်းပါ။
[2026-10-15 15:44:52] Best translation 157 : ▁ကျွန်တော် ▁ဒေါသထွက်တယ်။
[2026-10-15 15:44:52] Best translation 158 : ▁ကျွန်မ ▁အလုပ်များတယ်။
[2026-10-15 15:44:52] Best translation 159 : ▁Tom ▁က ▁သိမှာလဲ။
[2026-10-15 15:44:52] Best translation 160 : ▁ပိုကောင်း လာမယ်။
[2026-10-15 15:44:52] Best translation 161 : ▁မင်းရော။
[2026-10-15 15:44:52] Best translation 162 : ▁ဒါက ▁ထူးဆန်းပါတယ်။

In [22]:
import sentencepiece as spm

my_spm = spm.SentencePieceProcessor(model_file="my_spm.model")

with open(
    "/kaggle/working/output/transformer/test.output.my.spm", "r", encoding="utf-8"
) as f_in, open("/kaggle/working/output/transformer/test.output.my", "w", encoding="utf-8") as f_out:
  for line in f_in:
    pieces = line.strip().split()
    decoded_text = my_spm.decode(pieces)
    f_out.write(decoded_text + "\n")

print("Test set successfully detokenized!")

Test set successfully detokenized!

In [24]:
print("----Scoring Hieroglyph -> Burmese Transformer Model----")
!sacrebleu /kaggle/working/data/test.my -i /kaggle/working/output/transformer/test.output.my

----Scoring Hieroglyph -> Burmese Transformer Model----
{
 "name": "BLEU",
 "score": 15.0,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.6.0",
 "verbose_score": "31.0/14.6/9.1/12.5 (BP = 1.000 ratio = 1.026 hyp_len = 981 ref_len = 956)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.6.0"
}

In [25]:
%%writefile /kaggle/working/config/transformer/my2hi/config.yml
# Device and Model Settings
devices: [0]
model: /kaggle/working/models/transformer/my-hi.npz
type: transformer

# Training Corpora (Burmese -> Hieroglyph)
train-sets:
  - /kaggle/working/data/train.my.spm
  - /kaggle/working/data/train.hi.spm
vocabs:
  - /kaggle/working/data/my.vocab.yml
  - /kaggle/working/data/hi.vocab.yml

# Validation Settings
valid-sets:
  - /kaggle/working/data/valid.my.spm
  - /kaggle/working/data/valid.hi.spm
valid-freq: 100
valid-metrics: [cross-entropy, bleu]
early-stopping: 15

# Optimization & Hyperparameters
after-batches: 5000
mini-batch-words: 2048
workspace: 4096
optimizer: adam
learn-rate: 0.0003
lr-warmup: 4000
lr-decay-inv-sqrt: 4000
label-smoothing: 0.1

# Regularization
dropout-rnn: 0.2
dropout-src: 0.2
dropout-trg: 0.2
transformer-dropout: 0.2

# Architecture Parameters
transformer-heads: 4
dim-emb: 512
transformer-dim-ffn: 2048
enc-depth: 4
dec-depth: 4

Writing /kaggle/working/config/transformer/my2hi/config.yml

In [26]:
MARIAN_TRAIN = "/kaggle/working/marian-dev/build/marian"
!{MARIAN_TRAIN} --config /kaggle/working/config/transformer/my2hi/config.yml

[2026-10-15 15:49:55] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:49:55] [marian] Running on f2fe76130532 as process 18788 with command line:
[2026-10-15 15:49:55] [marian] /kaggle/working/marian-dev/build/marian --config /kaggle/working/config/transformer/my2hi/config.yml
[2026-10-15 15:49:55] [config] after: 0e
[2026-10-15 15:49:55] [config] after-batches: 5000
[2026-10-15 15:49:55] [config] after-epochs: 0
[2026-10-15 15:49:55] [config] all-caps-every: 0
[2026-10-15 15:49:55] [config] allow-unk: false
[2026-10-15 15:49:55] [config] authors: false
[2026-10-15 15:49:55] [config] beam-size: 12
[2026-10-15 15:49:55] [config] bert-class-symbol: "[CLS]"
[2026-10-15 15:49:55] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 15:49:55] [config] bert-masking-fraction: 0.15
[2026-10-15 15:49:55] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 15:49:55] [config] bert-train-type-embeddings: true
[2026-10-15 15:49:55] [config] bert-type-vocab-size: 2
[2026-10-15 15:49:55] [config] build-info: ""
[2026-10-15 15:49:55] [config] check-gradient-nan: false
[2026-10-15 15:49:55] [config] check-nan: false
[2026-10-15 15:49:55] [config] cite: false
[2026-10-15 15:49:55] [config] clip-norm: 1
[2026-10-15 15:49:55] [config] comet-augment-bad: 0
[2026-10-15 15:49:55] [config] comet-dropout: 0.1
[2026-10-15 15:49:55] [config] comet-final-sigmoid: false
[2026-10-15 15:49:55] [config] comet-mix: false
[2026-10-15 15:49:55] [config] comet-mix-norm: false
[2026-10-15 15:49:55] [config] comet-mix-transformation: softmax
[2026-10-15 15:49:55] [config] comet-mixup: 0
[2026-10-15 15:49:55] [config] comet-mixup-reg: false
[2026-10-15 15:49:55] [config] comet-pool: avg
[2026-10-15 15:49:55] [config] comet-pooler-ffn:
[2026-10-15 15:49:55] [config]   - 2048
[2026-10-15 15:49:55] [config]   - 1024
[2026-10-15 15:49:55] [config] comet-prepend-zero: false
[2026-10-15 15:49:55] [config] comet-stop-grad: false
[2026-10-15 15:49:55] [config] comet-use-separator: false
[2026-10-15 15:49:55] [config] cost-scaling:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] cost-type: ce-sum
[2026-10-15 15:49:55] [config] cpu-threads: 0
[2026-10-15 15:49:55] [config] custom-fallbacks:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] data-threads: 8
[2026-10-15 15:49:55] [config] data-weighting: ""
[2026-10-15 15:49:55] [config] data-weighting-type: sentence
[2026-10-15 15:49:55] [config] dec-cell: gru
[2026-10-15 15:49:55] [config] dec-cell-base-depth: 2
[2026-10-15 15:49:55] [config] dec-cell-high-depth: 1
[2026-10-15 15:49:55] [config] dec-depth: 4
[2026-10-15 15:49:55] [config] devices:
[2026-10-15 15:49:55] [config]   - 0
[2026-10-15 15:49:55] [config] dim-emb: 512
[2026-10-15 15:49:55] [config] dim-rnn: 1024
[2026-10-15 15:49:55] [config] dim-vocabs:
[2026-10-15 15:49:55] [config]   - 0
[2026-10-15 15:49:55] [config]   - 0
[2026-10-15 15:49:55] [config] disp-first: 0
[2026-10-15 15:49:55] [config] disp-freq: 1000u
[2026-10-15 15:49:55] [config] disp-label-counts: true
[2026-10-15 15:49:55] [config] dropout-rnn: 0.2
[2026-10-15 15:49:55] [config] dropout-src: 0.2
[2026-10-15 15:49:55] [config] dropout-trg: 0.2
[2026-10-15 15:49:55] [config] dump-config: ""
[2026-10-15 15:49:55] [config] dynamic-gradient-scaling:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] early-stopping: 15
[2026-10-15 15:49:55] [config] early-stopping-epsilon:
[2026-10-15 15:49:55] [config]   - 0
[2026-10-15 15:49:55] [config] early-stopping-on: first
[2026-10-15 15:49:55] [config] embedding-fix-src: false
[2026-10-15 15:49:55] [config] embedding-fix-trg: false
[2026-10-15 15:49:55] [config] embedding-normalization: false
[2026-10-15 15:49:55] [config] embedding-vectors:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] enc-cell: gru
[2026-10-15 15:49:55] [config] enc-cell-depth: 1
[2026-10-15 15:49:55] [config] enc-depth: 4
[2026-10-15 15:49:55] [config] enc-type: bidirectional
[2026-10-15 15:49:55] [config] english-title-case-every: 0
[2026-10-15 15:49:55] [config] exponential-smoothing: 0
[2026-10-15 15:49:55] [config] exponential-smoothing-replace-freq: 0
[2026-10-15 15:49:55] [config] factor-weight: 1
[2026-10-15 15:49:55] [config] factors-combine: sum
[2026-10-15 15:49:55] [config] factors-dim-emb: 0
[2026-10-15 15:49:55] [config] gradient-checkpointing: false
[2026-10-15 15:49:55] [config] gradient-norm-average-window: 100
[2026-10-15 15:49:55] [config] guided-alignment: none
[2026-10-15 15:49:55] [config] guided-alignment-cost: ce
[2026-10-15 15:49:55] [config] guided-alignment-weight: 0.1
[2026-10-15 15:49:55] [config] ignore-model-config: false
[2026-10-15 15:49:55] [config] input-join-fields: false
[2026-10-15 15:49:55] [config] input-reorder:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] input-types:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] interpolate-env-vars: false
[2026-10-15 15:49:55] [config] keep-best: false
[2026-10-15 15:49:55] [config] label-smoothing: 0.1
[2026-10-15 15:49:55] [config] layer-normalization: false
[2026-10-15 15:49:55] [config] learn-rate: 0.0003
[2026-10-15 15:49:55] [config] lemma-dependency: ""
[2026-10-15 15:49:55] [config] lemma-dim-emb: 0
[2026-10-15 15:49:55] [config] log: ""
[2026-10-15 15:49:55] [config] log-level: info
[2026-10-15 15:49:55] [config] log-time-zone: ""
[2026-10-15 15:49:55] [config] logical-epoch:
[2026-10-15 15:49:55] [config]   - 1e
[2026-10-15 15:49:55] [config]   - 0
[2026-10-15 15:49:55] [config] lr-decay: 0
[2026-10-15 15:49:55] [config] lr-decay-freq: 50000
[2026-10-15 15:49:55] [config] lr-decay-inv-sqrt:
[2026-10-15 15:49:55] [config]   - 4000
[2026-10-15 15:49:55] [config] lr-decay-repeat-warmup: false
[2026-10-15 15:49:55] [config] lr-decay-reset-optimizer: false
[2026-10-15 15:49:55] [config] lr-decay-start:
[2026-10-15 15:49:55] [config]   - 10
[2026-10-15 15:49:55] [config]   - 1
[2026-10-15 15:49:55] [config] lr-decay-strategy: epoch+stalled
[2026-10-15 15:49:55] [config] lr-report: false
[2026-10-15 15:49:55] [config] lr-warmup: 4000
[2026-10-15 15:49:55] [config] lr-warmup-at-reload: false
[2026-10-15 15:49:55] [config] lr-warmup-cycle: false
[2026-10-15 15:49:55] [config] lr-warmup-start-rate: 0
[2026-10-15 15:49:55] [config] max-length: 50
[2026-10-15 15:49:55] [config] max-length-crop: false
[2026-10-15 15:49:55] [config] max-length-factor: 3
[2026-10-15 15:49:55] [config] maxi-batch: 100
[2026-10-15 15:49:55] [config] maxi-batch-sort: trg
[2026-10-15 15:49:55] [config] mini-batch: 64
[2026-10-15 15:49:55] [config] mini-batch-fit: false
[2026-10-15 15:49:55] [config] mini-batch-fit-step: 10
[2026-10-15 15:49:55] [config] mini-batch-round-up: true
[2026-10-15 15:49:55] [config] mini-batch-track-lr: false
[2026-10-15 15:49:55] [config] mini-batch-warmup: 0
[2026-10-15 15:49:55] [config] mini-batch-words: 2048
[2026-10-15 15:49:55] [config] mini-batch-words-ref: 0
[2026-10-15 15:49:55] [config] model: /kaggle/working/models/transformer/my-hi.npz
[2026-10-15 15:49:55] [config] multi-loss-type: sum
[2026-10-15 15:49:55] [config] n-best: false
[2026-10-15 15:49:55] [config] no-nccl: false
[2026-10-15 15:49:55] [config] no-optimizer-reload: false
[2026-10-15 15:49:55] [config] no-reload: false
[2026-10-15 15:49:55] [config] no-restore-corpus: false
[2026-10-15 15:49:55] [config] no-spm-encode: false
[2026-10-15 15:49:55] [config] normalize: 0
[2026-10-15 15:49:55] [config] normalize-gradient: false
[2026-10-15 15:49:55] [config] normalize-gradient-by-ratio: false
[2026-10-15 15:49:55] [config] optimizer: adam
[2026-10-15 15:49:55] [config] optimizer-delay: 1
[2026-10-15 15:49:55] [config] optimizer-params:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] output-omit-bias: false
[2026-10-15 15:49:55] [config] overwrite: false
[2026-10-15 15:49:55] [config] overwrite-checkpoint: true
[2026-10-15 15:49:55] [config] precision:
[2026-10-15 15:49:55] [config]   - float32
[2026-10-15 15:49:55] [config]   - float32
[2026-10-15 15:49:55] [config] pretrained-model: ""
[2026-10-15 15:49:55] [config] quantize-biases: false
[2026-10-15 15:49:55] [config] quantize-bits: 0
[2026-10-15 15:49:55] [config] quantize-log-based: false
[2026-10-15 15:49:55] [config] quantize-optimization-steps: 0
[2026-10-15 15:49:55] [config] quiet: false
[2026-10-15 15:49:55] [config] quiet-translation: false
[2026-10-15 15:49:55] [config] quiet-validation: false
[2026-10-15 15:49:55] [config] relative-paths: false
[2026-10-15 15:49:55] [config] right-left: false
[2026-10-15 15:49:55] [config] save-freq: 10000u
[2026-10-15 15:49:55] [config] seed: 0
[2026-10-15 15:49:55] [config] sentencepiece-alphas:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] sentencepiece-max-lines: 2000000
[2026-10-15 15:49:55] [config] sentencepiece-options: ""
[2026-10-15 15:49:55] [config] separator-symbol: "[eos]"
[2026-10-15 15:49:55] [config] sharding: global
[2026-10-15 15:49:55] [config] shuffle: data
[2026-10-15 15:49:55] [config] shuffle-in-ram: false
[2026-10-15 15:49:55] [config] sigterm: save-and-exit
[2026-10-15 15:49:55] [config] skip: false
[2026-10-15 15:49:55] [config] sqlite: ""
[2026-10-15 15:49:55] [config] sqlite-drop: false
[2026-10-15 15:49:55] [config] sync-freq: 200u
[2026-10-15 15:49:55] [config] sync-sgd: false
[2026-10-15 15:49:55] [config] tempdir: /tmp
[2026-10-15 15:49:55] [config] throw-on-divergence:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] tied-embeddings: false
[2026-10-15 15:49:55] [config] tied-embeddings-all: false
[2026-10-15 15:49:55] [config] tied-embeddings-src: false
[2026-10-15 15:49:55] [config] train-embedder-rank:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] train-sets:
[2026-10-15 15:49:55] [config]   - /kaggle/working/data/train.my.spm
[2026-10-15 15:49:55] [config]   - /kaggle/working/data/train.hi.spm
[2026-10-15 15:49:55] [config] transformer-aan-activation: swish
[2026-10-15 15:49:55] [config] transformer-aan-depth: 2
[2026-10-15 15:49:55] [config] transformer-aan-nogate: false
[2026-10-15 15:49:55] [config] transformer-alibi-shift: false
[2026-10-15 15:49:55] [config] transformer-alibi-trainable: false
[2026-10-15 15:49:55] [config] transformer-attention-mask: default
[2026-10-15 15:49:55] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 15:49:55] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 15:49:55] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 15:49:55] [config] transformer-depth-scaling: false
[2026-10-15 15:49:55] [config] transformer-dim-aan: 2048
[2026-10-15 15:49:55] [config] transformer-dim-ffn: 2048
[2026-10-15 15:49:55] [config] transformer-disable-position-embeddings: false
[2026-10-15 15:49:55] [config] transformer-dropout: 0.2
[2026-10-15 15:49:55] [config] transformer-dropout-attention: 0
[2026-10-15 15:49:55] [config] transformer-dropout-ffn: 0
[2026-10-15 15:49:55] [config] transformer-ffn-activation: swish
[2026-10-15 15:49:55] [config] transformer-ffn-depth: 2
[2026-10-15 15:49:55] [config] transformer-guided-alignment-layer: last
[2026-10-15 15:49:55] [config] transformer-heads: 4
[2026-10-15 15:49:55] [config] transformer-no-affine: false
[2026-10-15 15:49:55] [config] transformer-no-bias: false
[2026-10-15 15:49:55] [config] transformer-no-projection: false
[2026-10-15 15:49:55] [config] transformer-pool: false
[2026-10-15 15:49:55] [config] transformer-postprocess: dan
[2026-10-15 15:49:55] [config] transformer-postprocess-emb: d
[2026-10-15 15:49:55] [config] transformer-postprocess-top: ""
[2026-10-15 15:49:55] [config] transformer-preprocess: ""
[2026-10-15 15:49:55] [config] transformer-rnn-projection: false
[2026-10-15 15:49:55] [config] transformer-tied-layers:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] transformer-train-position-embeddings: false
[2026-10-15 15:49:55] [config] tsv: false
[2026-10-15 15:49:55] [config] tsv-fields: 0
[2026-10-15 15:49:55] [config] type: transformer
[2026-10-15 15:49:55] [config] ulr: false
[2026-10-15 15:49:55] [config] ulr-dim-emb: 0
[2026-10-15 15:49:55] [config] ulr-dropout: 0
[2026-10-15 15:49:55] [config] ulr-keys-vectors: ""
[2026-10-15 15:49:55] [config] ulr-query-vectors: ""
[2026-10-15 15:49:55] [config] ulr-softmax-temperature: 1
[2026-10-15 15:49:55] [config] ulr-trainable-transformation: false
[2026-10-15 15:49:55] [config] unlikelihood-loss: false
[2026-10-15 15:49:55] [config] valid-freq: 100
[2026-10-15 15:49:55] [config] valid-log: ""
[2026-10-15 15:49:55] [config] valid-max-length: 1000
[2026-10-15 15:49:55] [config] valid-metrics:
[2026-10-15 15:49:55] [config]   - cross-entropy
[2026-10-15 15:49:55] [config]   - bleu
[2026-10-15 15:49:55] [config] valid-mini-batch: 32
[2026-10-15 15:49:55] [config] valid-reset-all: false
[2026-10-15 15:49:55] [config] valid-reset-stalled: false
[2026-10-15 15:49:55] [config] valid-script-args:
[2026-10-15 15:49:55] [config]   []
[2026-10-15 15:49:55] [config] valid-script-path: ""
[2026-10-15 15:49:55] [config] valid-sets:
[2026-10-15 15:49:55] [config]   - /kaggle/working/data/valid.my.spm
[2026-10-15 15:49:55] [config]   - /kaggle/working/data/valid.hi.spm
[2026-10-15 15:49:55] [config] valid-translation-output: ""
[2026-10-15 15:49:55] [config] vocabs:
[2026-10-15 15:49:55] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 15:49:55] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:49:55] [config] word-penalty: 0
[2026-10-15 15:49:55] [config] word-scores: false
[2026-10-15 15:49:55] [config] workspace: 4096
[2026-10-15 15:49:55] [config] Model is being created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:49:55] [training] Using single-device training
[2026-10-15 15:49:55] [comm] Compiled without MPI support. Running as a single process on f2fe76130532
[2026-10-15 15:49:55] Synced seed 1792079395
[2026-10-15 15:49:55] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 15:49:55] [data] Setting vocabulary size for input 0 to 6,014
[2026-10-15 15:49:55] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:49:55] [data] Setting vocabulary size for input 1 to 2,988
[2026-10-15 15:49:56] [memory] Extending reserved space to 4096 MB (device gpu0)
[2026-10-15 15:49:56] [comm] Using NCCL 2.8.3 for GPU communication
[2026-10-15 15:49:56] [comm] Using global sharding
[2026-10-15 15:49:56] [comm] NCCLCommunicators constructed successfully
[2026-10-15 15:49:56] [training] Using 1 GPUs
[2026-10-15 15:49:56] Training started
[2026-10-15 15:49:56] [data] Shuffling data
[2026-10-15 15:49:56] [data] Done reading 8,500 sentences
[2026-10-15 15:49:56] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:49:56] [training] Batches are processed as 1 process(es) x 1 devices/process
[2026-10-15 15:49:56] [logits] Applying loss function for 1 factor(s)
[2026-10-15 15:49:56] [memory] Reserving 135 MB, device gpu0
[2026-10-15 15:49:56] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 15:49:56] [memory] Reserving 135 MB, device gpu0
[2026-10-15 15:49:56] Parameter type float32, optimization type float32, casting types false
[2026-10-15 15:49:56] Allocating memory for Adam-specific shards
[2026-10-15 15:49:56] [memory] Reserving 271 MB, device gpu0
[2026-10-15 15:49:58] Seen 8,500 samples
[2026-10-15 15:49:58] Starting data epoch 2 in logical epoch 2
[2026-10-15 15:49:58] [data] Shuffling data
[2026-10-15 15:49:58] [data] Done reading 8,500 sentences
[2026-10-15 15:49:58] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:00] Seen 8,500 samples
[2026-10-15 15:50:00] Starting data epoch 3 in logical epoch 3
[2026-10-15 15:50:00] [data] Shuffling data
[2026-10-15 15:50:00] [data] Done reading 8,500 sentences
[2026-10-15 15:50:00] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:02] Seen 8,500 samples
[2026-10-15 15:50:02] Starting data epoch 4 in logical epoch 4
[2026-10-15 15:50:02] [data] Shuffling data
[2026-10-15 15:50:02] [data] Done reading 8,500 sentences
[2026-10-15 15:50:02] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:03] Seen 8,500 samples
[2026-10-15 15:50:03] Starting data epoch 5 in logical epoch 5
[2026-10-15 15:50:03] [data] Shuffling data
[2026-10-15 15:50:03] [data] Done reading 8,500 sentences
[2026-10-15 15:50:03] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:05] Seen 8,500 samples
[2026-10-15 15:50:05] Starting data epoch 6 in logical epoch 6
[2026-10-15 15:50:05] [data] Shuffling data
[2026-10-15 15:50:05] [data] Done reading 8,500 sentences
[2026-10-15 15:50:05] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:07] Seen 8,500 samples
[2026-10-15 15:50:07] Starting data epoch 7 in logical epoch 7
[2026-10-15 15:50:07] [data] Shuffling data
[2026-10-15 15:50:07] [data] Done reading 8,500 sentences
[2026-10-15 15:50:07] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:08] [valid] Ep. 7 : Up. 100 : cross-entropy : 28.637 : new best
[2026-10-15 15:50:08] Translating validation set...
[2026-10-15 15:50:08] [valid] References contain unknown word, metric scores may be inaccurate
[2026-10-15 15:50:08] [valid] First sentence's tokens as scored:
[2026-10-15 15:50:08] [valid] DefaultVocab keeps original segments for scoring
[2026-10-15 15:50:08] [valid]   Hyp:
[2026-10-15 15:50:08] [valid]   Ref: ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓏭𓄿𓈎 <unk> <unk> 𓆑𓏭
[2026-10-15 15:50:08] Best translation 0 :
[2026-10-15 15:50:08] Best translation 1 :
[2026-10-15 15:50:08] Best translation 2 :
[2026-10-15 15:50:08] Best translation 3 :
[2026-10-15 15:50:08] Best translation 4 :
[2026-10-15 15:50:08] Best translation 5 :
[2026-10-15 15:50:08] Best translation 10 :
[2026-10-15 15:50:08] Best translation 20 :
[2026-10-15 15:50:08] Best translation 40 :
[2026-10-15 15:50:08] Best translation 80 :
[2026-10-15 15:50:08] Best translation 160 :
[2026-10-15 15:50:08] Best translation 320 :
[2026-10-15 15:50:08] Best translation 640 :
[2026-10-15 15:50:08] Total translation time: 0.37951s
[2026-10-15 15:50:08] [valid] Ep. 7 : Up. 100 : bleu : 0 : new best
[2026-10-15 15:50:09] Seen 8,500 samples
[2026-10-15 15:50:09] Starting data epoch 8 in logical epoch 8
[2026-10-15 15:50:09] [data] Shuffling data
[2026-10-15 15:50:09] [data] Done reading 8,500 sentences
[2026-10-15 15:50:10] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:11] Seen 8,500 samples
[2026-10-15 15:50:11] Starting data epoch 9 in logical epoch 9
[2026-10-15 15:50:11] [data] Shuffling data
[2026-10-15 15:50:11] [data] Done reading 8,500 sentences
[2026-10-15 15:50:11] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:13] Seen 8,500 samples
[2026-10-15 15:50:13] Starting data epoch 10 in logical epoch 10
[2026-10-15 15:50:13] [data] Shuffling data
[2026-10-15 15:50:13] [data] Done reading 8,500 sentences
[2026-10-15 15:50:13] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:15] Seen 8,500 samples
[2026-10-15 15:50:15] Starting data epoch 11 in logical epoch 11
[2026-10-15 15:50:15] [data] Shuffling data
[2026-10-15 15:50:15] [data] Done reading 8,500 sentences
[2026-10-15 15:50:15] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:17] Seen 8,500 samples
[2026-10-15 15:50:17] Starting data epoch 12 in logical epoch 12
[2026-10-15 15:50:17] [data] Shuffling data
[2026-10-15 15:50:17] [data] Done reading 8,500 sentences
[2026-10-15 15:50:17] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:19] Seen 8,500 samples
[2026-10-15 15:50:19] Starting data epoch 13 in logical epoch 13
[2026-10-15 15:50:19] [data] Shuffling data
[2026-10-15 15:50:19] [data] Done reading 8,500 sentences
[2026-10-15 15:50:19] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 15:50:20] [valid] Ep. 13 : Up. 200 : cross-entropy : 25.457 : new best

In [27]:
MARIAN_DECODER="/kaggle/working/marian-dev/build/marian-decoder"

!{MARIAN_DECODER} \
  --models /kaggle/working/models/transformer/my-hi.npz \
  --vocabs /kaggle/working/data/my.vocab.yml /kaggle/working/data/hi.vocab.yml \
  --beam-size 12 \
  --normalize 1.0 \
  < /kaggle/working/data/test.my.spm \
  > /kaggle/working/output/transformer/test.output.hi.spm

[2026-10-15 16:00:40] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:00:40] [marian] Running on f2fe76130532 as process 18828 with command line:
[2026-10-15 16:00:40] [marian] /kaggle/working/marian-dev/build/marian-decoder --models /kaggle/working/models/transformer/my-hi.npz --vocabs /kaggle/working/data/my.vocab.yml /kaggle/working/data/hi.vocab.yml --beam-size 12 --normalize 1.0
[2026-10-15 16:00:40] [config] alignment: ""
[2026-10-15 16:00:40] [config] allow-special: false
[2026-10-15 16:00:40] [config] allow-unk: false
[2026-10-15 16:00:40] [config] authors: false
[2026-10-15 16:00:40] [config] beam-size: 12
[2026-10-15 16:00:40] [config] bert-class-symbol: "[CLS]"
[2026-10-15 16:00:40] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 16:00:40] [config] bert-masking-fraction: 0.15
[2026-10-15 16:00:40] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 16:00:40] [config] bert-train-type-embeddings: true
[2026-10-15 16:00:40] [config] bert-type-vocab-size: 2
[2026-10-15 16:00:40] [config] best-deep: false
[2026-10-15 16:00:40] [config] build-info: ""
[2026-10-15 16:00:40] [config] check-nan: false
[2026-10-15 16:00:40] [config] cite: false
[2026-10-15 16:00:40] [config] comet-augment-bad: 0
[2026-10-15 16:00:40] [config] comet-dropout: 0.1
[2026-10-15 16:00:40] [config] comet-final-sigmoid: false
[2026-10-15 16:00:40] [config] comet-mix: false
[2026-10-15 16:00:40] [config] comet-mix-norm: false
[2026-10-15 16:00:40] [config] comet-mix-transformation: softmax
[2026-10-15 16:00:40] [config] comet-mixup: 0
[2026-10-15 16:00:40] [config] comet-mixup-reg: false
[2026-10-15 16:00:40] [config] comet-pool: avg
[2026-10-15 16:00:40] [config] comet-pooler-ffn:
[2026-10-15 16:00:40] [config]   - 2048
[2026-10-15 16:00:40] [config]   - 1024
[2026-10-15 16:00:40] [config] comet-prepend-zero: false
[2026-10-15 16:00:40] [config] comet-stop-grad: false
[2026-10-15 16:00:40] [config] comet-use-separator: false
[2026-10-15 16:00:40] [config] cpu-threads: 0
[2026-10-15 16:00:40] [config] data-threads: 8
[2026-10-15 16:00:40] [config] dec-cell: gru
[2026-10-15 16:00:40] [config] dec-cell-base-depth: 2
[2026-10-15 16:00:40] [config] dec-cell-high-depth: 1
[2026-10-15 16:00:40] [config] dec-depth: 4
[2026-10-15 16:00:40] [config] devices:
[2026-10-15 16:00:40] [config]   - 0
[2026-10-15 16:00:40] [config] dim-emb: 512
[2026-10-15 16:00:40] [config] dim-rnn: 1024
[2026-10-15 16:00:40] [config] dim-vocabs:
[2026-10-15 16:00:40] [config]   - 6014
[2026-10-15 16:00:40] [config]   - 2988
[2026-10-15 16:00:40] [config] dump-config: ""
[2026-10-15 16:00:40] [config] enc-cell: gru
[2026-10-15 16:00:40] [config] enc-cell-depth: 1
[2026-10-15 16:00:40] [config] enc-depth: 4
[2026-10-15 16:00:40] [config] enc-type: bidirectional
[2026-10-15 16:00:40] [config] factors-combine: sum
[2026-10-15 16:00:40] [config] factors-dim-emb: 0
[2026-10-15 16:00:40] [config] force-decode: false
[2026-10-15 16:00:40] [config] gemm-type: float32
[2026-10-15 16:00:40] [config] ignore-model-config: false
[2026-10-15 16:00:40] [config] input:
[2026-10-15 16:00:40] [config]   - stdin
[2026-10-15 16:00:40] [config] input-join-fields: false
[2026-10-15 16:00:40] [config] input-reorder:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] input-types:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] interpolate-env-vars: false
[2026-10-15 16:00:40] [config] layer-normalization: false
[2026-10-15 16:00:40] [config] lemma-dependency: ""
[2026-10-15 16:00:40] [config] lemma-dim-emb: 0
[2026-10-15 16:00:40] [config] log: ""
[2026-10-15 16:00:40] [config] log-level: info
[2026-10-15 16:00:40] [config] log-time-zone: ""
[2026-10-15 16:00:40] [config] max-length: 1000
[2026-10-15 16:00:40] [config] max-length-crop: false
[2026-10-15 16:00:40] [config] max-length-factor: 3
[2026-10-15 16:00:40] [config] maxi-batch: 1
[2026-10-15 16:00:40] [config] maxi-batch-sort: none
[2026-10-15 16:00:40] [config] mini-batch: 1
[2026-10-15 16:00:40] [config] mini-batch-words: 0
[2026-10-15 16:00:40] [config] model-mmap: false
[2026-10-15 16:00:40] [config] models:
[2026-10-15 16:00:40] [config]   - /kaggle/working/models/transformer/my-hi.npz
[2026-10-15 16:00:40] [config] n-best: false
[2026-10-15 16:00:40] [config] no-spm-decode: false
[2026-10-15 16:00:40] [config] no-spm-encode: false
[2026-10-15 16:00:40] [config] normalize: 1
[2026-10-15 16:00:40] [config] optimize: false
[2026-10-15 16:00:40] [config] output: stdout
[2026-10-15 16:00:40] [config] output-approx-knn:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] output-omit-bias: false
[2026-10-15 16:00:40] [config] output-sampling:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] precision:
[2026-10-15 16:00:40] [config]   - float32
[2026-10-15 16:00:40] [config] quantize-range: 0
[2026-10-15 16:00:40] [config] quiet: false
[2026-10-15 16:00:40] [config] quiet-translation: false
[2026-10-15 16:00:40] [config] relative-paths: false
[2026-10-15 16:00:40] [config] right-left: false
[2026-10-15 16:00:40] [config] seed: 0
[2026-10-15 16:00:40] [config] separator-symbol: "[eos]"
[2026-10-15 16:00:40] [config] shortlist:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] skip: false
[2026-10-15 16:00:40] [config] skip-cost: false
[2026-10-15 16:00:40] [config] stat-freq: 0
[2026-10-15 16:00:40] [config] tied-embeddings: false
[2026-10-15 16:00:40] [config] tied-embeddings-all: false
[2026-10-15 16:00:40] [config] tied-embeddings-src: false
[2026-10-15 16:00:40] [config] transformer-aan-activation: swish
[2026-10-15 16:00:40] [config] transformer-aan-depth: 2
[2026-10-15 16:00:40] [config] transformer-aan-nogate: false
[2026-10-15 16:00:40] [config] transformer-alibi-shift: false
[2026-10-15 16:00:40] [config] transformer-alibi-trainable: false
[2026-10-15 16:00:40] [config] transformer-attention-mask: default
[2026-10-15 16:00:40] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 16:00:40] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 16:00:40] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 16:00:40] [config] transformer-depth-scaling: false
[2026-10-15 16:00:40] [config] transformer-dim-aan: 2048
[2026-10-15 16:00:40] [config] transformer-dim-ffn: 2048
[2026-10-15 16:00:40] [config] transformer-disable-position-embeddings: false
[2026-10-15 16:00:40] [config] transformer-ffn-activation: swish
[2026-10-15 16:00:40] [config] transformer-ffn-depth: 2
[2026-10-15 16:00:40] [config] transformer-guided-alignment-layer: last
[2026-10-15 16:00:40] [config] transformer-heads: 4
[2026-10-15 16:00:40] [config] transformer-no-affine: false
[2026-10-15 16:00:40] [config] transformer-no-bias: false
[2026-10-15 16:00:40] [config] transformer-no-projection: false
[2026-10-15 16:00:40] [config] transformer-pool: false
[2026-10-15 16:00:40] [config] transformer-postprocess: dan
[2026-10-15 16:00:40] [config] transformer-postprocess-emb: d
[2026-10-15 16:00:40] [config] transformer-postprocess-top: ""
[2026-10-15 16:00:40] [config] transformer-preprocess: ""
[2026-10-15 16:00:40] [config] transformer-rnn-projection: false
[2026-10-15 16:00:40] [config] transformer-tied-layers:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] transformer-train-position-embeddings: false
[2026-10-15 16:00:40] [config] tsv: false
[2026-10-15 16:00:40] [config] tsv-fields: 0
[2026-10-15 16:00:40] [config] type: transformer
[2026-10-15 16:00:40] [config] ulr: false
[2026-10-15 16:00:40] [config] ulr-dim-emb: 0
[2026-10-15 16:00:40] [config] ulr-trainable-transformation: false
[2026-10-15 16:00:40] [config] version: v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:00:40] [config] vocabs:
[2026-10-15 16:00:40] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 16:00:40] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 16:00:40] [config] weights:
[2026-10-15 16:00:40] [config]   []
[2026-10-15 16:00:40] [config] word-penalty: 0
[2026-10-15 16:00:40] [config] word-scores: false
[2026-10-15 16:00:40] [config] workspace: 512
[2026-10-15 16:00:40] [config] Loaded model has been created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:00:40] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 16:00:40] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 16:00:40] Loading model from /kaggle/working/models/transformer/my-hi.npz
[2026-10-15 16:00:40] [memory] Extending reserved space to 512 MB (device gpu0)
[2026-10-15 16:00:40] Loaded model config
[2026-10-15 16:00:40] Loading scorer of type transformer as feature F0
[2026-10-15 16:00:40] [memory] Reserving 135 MB, device gpu0
[2026-10-15 16:00:41] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 16:00:41] Best translation 0 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓎜𓀀𓈎 ▁𓂋𓐍𓎼𓂝
[2026-10-15 16:00:41] Best translation 1 : ▁𓈎𓊪𓂝𓋴𓂝𓈙 ▁𓎜𓀀 ▁𓅲𓀀𓐍𓇌
[2026-10-15 16:00:41] Best translation 2 : ▁𓎜𓀀𓇋𓐍𓇌𓂧 ▁𓈙𓄿𓏏 ▁𓉔𓂝
[2026-10-15 16:00:41] Best translation 3 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓏭𓄿𓎡𓈎 𓆒𓀀𓎡𓈙
[2026-10-15 16:00:41] Best translation 4 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓄿 ▁𓊪𓄿𓈎
[2026-10-15 16:00:41] Best translation 5 : ▁𓊪𓄿𓎼𓂝 ▁𓄿 ▁𓈙𓄿𓅱𓂝 ▁𓈎𓋴𓆑𓄡
[2026-10-15 16:00:41] Best translation 6 : ▁𓆑𓂋𓂋 ▁𓃀𓐍 ▁𓄿𓎛𓂧𓏏𓄿𓂧
[2026-10-15 16:00:41] Best translation 7 : ▁𓆑𓈎 ▁𓆑𓈙 ▁𓅲𓀀𓃀𓃀𓂧
[2026-10-15 16:00:41] Best translation 8 : ▁𓈙𓊪𓂝 ▁𓏏𓆑𓂋𓂋 ▁𓏏𓄿𓂋𓈖
[2026-10-15 16:00:41] Best translation 9 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓆑𓈎
[2026-10-15 16:00:41] Best translation 10 : ▁𓆑𓈙𓎛𓈎 ▁𓆑𓈎 ▁𓎛𓆑𓏭𓂝
[2026-10-15 16:00:41] Best translation 11 : ▁𓆑𓂋𓂋 ▁𓃀𓐍𓈎 ▁𓎡𓄡 ▁𓂋𓄿𓈎𓂝
[2026-10-15 16:00:41] Best translation 12 : ▁𓆑 ▁𓄿𓉔 ▁𓐍𓎛 ▁𓇌𓎡𓈎𓂧 ▁𓎜𓀀𓏏
[2026-10-15 16:00:41] Best translation 13 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓈎𓄿𓂋𓂋
[2026-10-15 16:00:41] Best translation 14 : ▁𓂋𓂝𓈎 ▁𓉔𓂝 ▁𓊪𓂝𓂋𓄡 ▁𓉔𓂝
[2026-10-15 16:00:41] Best translation 15 : ▁𓆑 ▁𓂋𓆑𓈖𓂝 ▁𓈙𓎡𓋴𓄡𓋴𓆑𓈙𓂝𓈙
[2026-10-15 16:00:41] Best translation 16 : ▁𓈙𓊪𓂝 ▁𓈎𓋴𓆑𓂝𓇌
[2026-10-15 16:00:41] Best translation 17 : ▁𓆑 ▁𓂋𓐍𓎼𓂝 ▁𓄿𓎛𓆑𓉔𓄿𓂋𓈙
[2026-10-15 16:00:41] Best translation 18 : ▁𓆑 ▁𓏮𓀀𓉔𓄡𓂋𓄿𓆑𓎛 ▁𓄿 ▁𓉔𓆑𓎛𓎡𓈎𓂝
[2026-10-15 16:00:41] Best translation 19 : ▁𓆑 ▁𓈙𓂝𓂝 ▁𓈚𓀀𓉔𓂝𓈎𓊪𓆑𓎛𓃀
[2026-10-15 16:00:41] Best translation 20 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓇋𓆑𓃀
[2026-10-15 16:00:41] Best translation 21 : ▁𓆑 ▁𓊪𓄿𓈎𓂝 ▁𓉔𓆑𓂋𓈖
[2026-10-15 16:00:41] Best translation 22 : ▁𓊪𓂝 ▁𓊪𓄿𓈙 ▁𓄿 ▁𓇌𓐍𓃀
[2026-10-15 16:00:41] Best translation 23 : ▁𓏏𓂝 ▁𓏏𓄿𓎛𓈎 ▁𓄿 ▁𓅱𓄿𓉔𓆑𓂋𓂧
[2026-10-15 16:00:41] Best translation 24 : ▁𓈙𓊪𓂝 ▁𓂋𓐍𓎼𓂝𓈙 ▁𓊪𓆑𓉔
[2026-10-15 16:00:41] Best translation 25 : ▁𓊪𓂝 ▁𓆑𓈙 ▁𓈙𓆑𓏭𓈖
[2026-10-15 16:00:41] Best translation 26 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓐍 ▁𓇌𓆑𓂝
[2026-10-15 16:00:41] Best translation 27 : ▁𓊪𓐍𓏏 ▁𓐍𓂋𓇌 ▁𓆑𓈙 ▁𓆑𓈎
[2026-10-15 16:00:41] Best translation 28 : ▁𓆑𓈎 ▁𓏏𓄿𓈙 ▁𓈙𓎡𓄡 𓂝𓋴𓇋
[2026-10-15 16:00:41] Best translation 29 : ▁𓈎𓊪𓂝𓂧 ▁𓊪𓄿𓎼𓂝 ▁𓄿𓈙𓈖𓂝𓇌 ▁𓈎𓐍𓉔
[2026-10-15 16:00:41] Best translation 30 : ▁𓇌𓐍 ▁𓏏𓊪𓄿𓈎 ▁𓂨𓀀𓎡 ▁𓏏𓄿𓎛𓈎
[2026-10-15 16:00:41] Best translation 31 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓎜𓀀𓈎 ▁𓂋𓐍𓎼𓂝
[2026-10-15 16:00:41] Best translation 32 : ▁𓏏𓂝 ▁𓄿𓂋𓂋 ▁𓂋𓆑𓂝
[2026-10-15 16:00:41] Best translation 33 : ▁𓂨𓀀𓎡 ▁𓉔𓎡𓈙𓈎 ▁𓇋𓂝 ▁𓈙𓆑𓏭𓈖
[2026-10-15 16:00:41] Best translation 34 : ▁𓆑 ▁𓏭𓄿𓎛𓈎 ▁𓎡𓈙𓂝 ▁𓆑𓈎
[2026-10-15 16:00:41] Best translation 35 : ▁𓏏𓄿𓂋𓈖 ▁𓈎𓐍 ▁𓉔𓂝
[2026-10-15 16:00:41] Best translation 36 : ▁𓆑𓈎𓈙 ▁𓈎𓐍𓐍 ▁𓇌𓄿𓋴𓈖
[2026-10-15 16:00:41] Best translation 37 : ▁𓈎𓊪𓂝𓂧 ▁𓈖𓎛𓆑𓈎𓈙
[2026-10-15 16:00:41] Best translation 38 : ▁𓆑 ▁𓉔𓎡𓈙𓈎 ▁𓊪𓂝𓂋𓄡 ▁𓂨𓀀𓎡
[2026-10-15 16:00:41] Best translation 39 : ▁𓏏𓊪𓂝𓋴𓂝 ▁𓄿𓋴𓂝 ▁𓈎𓊪𓂝𓂧
[2026-10-15 16:00:41] Best translation 40 : ▁𓏏𓂝 ▁𓏏𓂝𓋴𓂝𓎛𓈎 ▁𓂋𓎡𓏭𓈖𓂧
[2026-10-15 16:00:41] Best translation 41 : ▁𓈙𓊪𓂝𓈙 ▁𓎛𓆑𓏭𓂝 ▁𓈎𓐍 ▁𓉔𓂝
[2026-10-15 16:00:41] Best translation 42 : ▁𓆑𓉔 ▁𓆑𓎛𓈎𓂝𓋴𓂝𓈙𓈎 𓆑𓎛𓃀
[2026-10-15 16:00:41] Best translation 43 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓄿𓏏𓂝𓈚𓀀𓉔𓂝
[2026-10-15 16:00:41] Best translation 44 : ▁𓉔𓂝𓎛 ▁𓄿𓋴𓂝 ▁𓈙𓆑𓉔𓄡𓂋𓂝
[2026-10-15 16:00:41] Best translation 45 : ▁𓄡𓋴𓆑𓏭𓂝𓈙 ▁𓏏𓂝𓎛𓈎 ▁𓎡𓄡
[2026-10-15 16:00:41] Best translation 46 : ▁𓊪𓂝 ▁𓆑𓈙 ▁𓅓𓎡𓈙𓈎 ▁𓄿 ▁𓈖𓆑𓇌
[2026-10-15 16:00:41] Best translation 47 : ▁𓆑 ▁𓂋𓆑𓈖𓂝 ▁𓈎𓐍𓉔
[2026-10-15 16:00:41] Best translation 48 : ▁𓊪𓂝 ▁𓅓𓎡𓈙𓈎 ▁𓃀𓐍𓈎 ▁𓎡𓄡
[2026-10-15 16:00:41] Best translation 49 : ▁𓆑 ▁𓇌𓆑𓇌𓎛𓈎 ▁𓎜𓀀𓈎𓊪𓆑𓎛𓃀
[2026-10-15 16:00:41] Best translation 50 : ▁𓊪𓂝 ▁𓏭𓄿𓉔𓂝 ▁𓈎𓐍 ▁𓋴𓎡𓎛
[2026-10-15 16:00:41] Best translation 51 : ▁𓆑𓉔 ▁𓄿𓇋𓐍𓎡𓈎 ▁𓋴𓂝𓄿𓇌𓂧
[2026-10-15 16:00:41] Best translation 52 : ▁𓆑 ▁𓅓𓎡𓈙𓈎 ▁𓅲𓀀𓂋𓂋𓐍𓏏 ▁𓊪𓆑𓉔
[2026-10-15 16:00:41] Best translation 53 : ▁𓏏𓂝𓋴𓂝 ▁𓄿𓂋𓂋 ▁𓎡𓎛 𓆑𓊃𓎡𓂝
[2026-10-15 16:00:41] Best translation 54 : ▁𓆑𓈎𓈙 ▁𓎜𓀀𓈎 ▁𓆑𓎛 𓅓𓎡𓋴𓆑𓂝𓈙
[2026-10-15 16:00:41] Best translation 55 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓊪𓐍𓉔𓂝
[2026-10-15 16:00:41] Best translation 56 : ▁𓇌𓐍 ▁𓄿𓈙 ▁𓆑 ▁𓈎𓐍𓂋𓇌 ▁𓂨𓀀𓎡
[2026-10-15 16:00:41] Best translation 57 : ▁𓄿𓂋𓂋 ▁𓆑𓈙 ▁𓏏𓂝𓂋𓂋
[2026-10-15 16:00:41] Best translation 58 : ▁𓇌𓐍𓎛𓈎 ▁𓂋𓆑𓈖𓂝 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:00:41] Best translation 59 : ▁𓈎𓐍𓉔 ▁𓆑𓈙 ▁𓏭𓋴𓎡𓂝𓂋
[2026-10-15 16:00:41] Best translation 60 : ▁𓆑 ▁𓂋𓆑𓈖𓂝 ▁𓄡𓎡𓆓𓆓 𓂋𓂝𓈙
[2026-10-15 16:00:41] Best translation 61 : ▁𓊪𓂝 ▁𓏭𓄿𓎛 ▁𓈙𓈖𓄿𓈎𓂝
[2026-10-15 16:00:42] Best translation 62 : ▁𓏏𓊪𓄿𓈎𓎼𓂝 ▁𓂨𓀀𓎡 ▁𓃀𓐍𓈎
[2026-10-15 16:00:42] Best translation 63 : ▁𓆑 ▁𓇌𓋴𓄿𓎛𓈖 ▁𓈎𓊪𓂝 ▁𓏏𓆑𓎛𓂝
[2026-10-15 16:00:42] Best translation 64 : ▁𓏏𓂝 ▁𓈎𓋴𓂧
[2026-10-15 16:00:42] Best translation 65 : ▁𓆑𓂋𓂋 ▁𓃀𓂝𓈎 ▁𓆑𓏭𓂝
[2026-10-15 16:00:42] Best translation 66 : ▁𓆑𓉔 ▁𓋴𓂝𓄿𓇌𓂧
[2026-10-15 16:00:42] Best translation 67 : ▁𓆑𓈎𓈙 ▁𓎜𓀀𓈎 ▁𓄿 ▁𓅱𓄿𓉔𓆑𓂋𓂧
[2026-10-15 16:00:42] Best translation 68 : ▁𓂨𓀀𓎡𓋴𓂝 ▁𓎜𓀀 ▁𓈙𓆑𓎛𓃀𓂝𓋴
[2026-10-15 16:00:42] Best translation 69 : ▁𓆑𓉔 ▁𓄿 ▁𓇋𓄿𓎛𓈖 ▁𓏭𓂋𓂝𓋴𓈖
[2026-10-15 16:00:42] Best translation 70 : ▁𓊪𓐍𓏏 ▁𓇌𓐍 ▁𓂨𓀀𓎡 ▁𓇌𓐍 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:00:42] Best translation 71 : ▁𓆑𓈎𓈙 ▁𓄿 ▁𓃀𓐍𓐍𓇌 ▁𓇌𓄿𓂧
[2026-10-15 16:00:42] Best translation 72 : ▁𓎜𓀀 ▁𓐍𓎛𓂝 ▁𓈙𓄡𓐍𓈖𓂝
[2026-10-15 16:00:42] Best translation 73 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓊪𓂝 ▁𓅱𓄿𓎛
[2026-10-15 16:00:42] Best translation 74 : ▁𓆑 ▁𓏭𓄿𓎛 ▁𓋴𓂝𓈙𓏭𓊪𓂝𓇌𓎡𓂋𓂝
[2026-10-15 16:00:42] Best translation 75 : ▁𓄿𓉔 ▁𓆑 ▁𓊪𓆑𓋴𓂝𓇌
[2026-10-15 16:00:42] Best translation 76 : ▁𓆑𓈎𓈙 ▁𓎼𓂝𓋴𓂧 ▁𓇌𓋴𓂧
[2026-10-15 16:00:42] Best translation 77 : ▁𓄿𓋴𓂝 ▁𓏏𓂝 ▁𓋴𓂝𓄿𓇌𓂧
[2026-10-15 16:00:42] Best translation 78 : ▁𓈎𓐍𓉔 ▁𓉔𓐍𓎼𓂝𓈙 ▁𓊃𓎡𓆑𓏭𓈖𓂋𓂧
[2026-10-15 16:00:42] Best translation 79 : ▁𓆑 ▁𓃀𓐍𓈎 ▁𓎡𓄡
[2026-10-15 16:00:42] Best translation 80 : ▁𓊪𓂝 ▁𓂋𓆑𓈖𓂝𓇌 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:00:42] Best translation 81 : ▁𓂋𓂝𓈎 ▁𓉔𓂝 ▁𓄿𓎛𓂧 𓈎𓆑𓉔𓂝
[2026-10-15 16:00:42] Best translation 82 : ▁𓆑 ▁𓈎𓐍𓐍𓈖 ▁𓄿 ▁𓂋𓐍𓈎
[2026-10-15 16:00:42] Best translation 83 : ▁𓈎𓐍𓉔𓈙 ▁𓄿𓎛𓃀𓋴𓂧
[2026-10-15 16:00:42] Best translation 84 : ▁𓆑 ▁𓄿𓃀𓋴𓂝𓂝
[2026-10-15 16:00:42] Best translation 85 : ▁𓆑 ▁𓏭𓄿𓎛 ▁𓈙𓏏𓆑𓉔 ▁𓏏𓂝𓂋𓂋
[2026-10-15 16:00:42] Best translation 86 : ▁𓈖𓂝𓂝𓄡 ▁𓈎𓊪𓂝 ▁𓇋𓐍𓈎𓈎𓐍𓉔
[2026-10-15 16:00:42] Best translation 87 : ▁𓇌𓆑𓇌 ▁𓆑 ▁𓇌𓐍 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:00:42] Best translation 88 : ▁𓏮𓀀𓉔𓂝 ▁𓆑𓉔𓉔𓂝𓇌 𓆑𓄿𓈎𓂝𓂋𓂧
[2026-10-15 16:00:42] Best translation 89 : ▁𓊪𓂝 ▁𓅱𓂋𓂝𓏏 ▁𓈎𓐍 ▁𓄡𓄿𓋴𓆑𓈙
[2026-10-15 16:00:42] Best translation 90 : ▁𓄿𓉔 ▁𓆑 ▁𓏭𓂋𓂝𓄿𓋴
[2026-10-15 16:00:42] Best translation 91 : ▁𓊪𓂝 ▁𓏭𓋴𓄿 𓏭𓈖𓂝𓇌 ▁𓎡𓄡
[2026-10-15 16:00:42] Best translation 92 : ▁𓆑𓈎𓈙 ▁𓆑𓉔𓄡𓋴𓐍 𓇋𓄿𓇋𓂋𓂝
[2026-10-15 16:00:42] Best translation 93 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓅱𓆑𓎛𓆑𓈙𓊪𓂝𓇌
[2026-10-15 16:00:42] Best translation 94 : ▁𓄿𓈙𓈖 ▁𓉔𓂝 ▁𓄿𓎛𓂧𓈎𓊪𓆑𓎛𓃀
[2026-10-15 16:00:42] Best translation 95 : ▁𓏏𓂝𓋴𓂝 ▁𓈎𓊪𓂝 ▁𓇋𓂝𓈙𓈎
[2026-10-15 16:00:42] Best translation 96 : ▁𓆑 ▁𓊪𓄿𓇌 ▁𓈎𓐍 ▁𓏏𓐍𓋴𓈖
[2026-10-15 16:00:42] Best translation 97 : ▁𓏏𓂝 ▁𓄿𓂋𓂋 ▁𓈙𓎡𓅱𓅱𓂝 𓋴𓂝𓇌
[2026-10-15 16:00:42] Best translation 98 : ▁𓆑𓉔 ▁𓇌𓆑𓂝𓈎𓆑𓎛𓃀
[2026-10-15 16:00:42] Best translation 99 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓎜𓀀 ▁𓅱𓎡𓎛
[2026-10-15 16:00:42] Best translation 100 : ▁𓆑 ▁𓂋𓂝𓈎 ▁𓂨𓀀𓎡 ▁𓇌𓐍𓏏𓎛
[2026-10-15 16:00:42] Best translation 101 : ▁𓈎𓐍𓉔 ▁𓆑𓈙𓎛𓈎 ▁𓐍𓄡𓂝𓋴𓄿
[2026-10-15 16:00:42] Best translation 102 : ▁𓂨𓀀𓎡 ▁𓏏𓆑𓂋𓂋 ▁𓐍𓇋𓂝𓂧 ▁𓎡𓈙
[2026-10-15 16:00:42] Best translation 103 : ▁𓏮𓀀𓉔𓂝 ▁𓅓𓐍𓆑𓎛 ▁𓎡𓈙
[2026-10-15 16:00:42] Best translation 104 : ▁𓈎𓐍𓉔 ▁𓆑𓈙 ▁𓄿 ▁𓄡𓂋𓄿𓎛𓂝𓈎
[2026-10-15 16:00:42] Best translation 105 : ▁𓏭𓄿𓎛 ▁𓂨𓀀𓎡 ▁𓏭𓄿𓎛 ▁𓏮𓀀𓉔𓂝
[2026-10-15 16:00:42] Best translation 106 : ▁𓂋𓐍𓐍𓈖 ▁𓅲𓀀𓋴 ▁𓎡𓈙
[2026-10-15 16:00:42] Best translation 107 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓄿 ▁𓇋𓐍𓐍𓈖
[2026-10-15 16:00:42] Best translation 108 : ▁𓏏𓂝 ▁𓎛𓂝𓂝𓇌 ▁𓊪𓂝𓂋𓄡
[2026-10-15 16:00:42] Best translation 109 : ▁𓊪𓂝 ▁𓂋𓐍𓎼𓂝𓈙 ▁𓋴𓎡𓎛𓎛𓆑𓎛𓃀
[2026-10-15 16:00:42] Best translation 110 : ▁𓆑 ▁𓈖𓎜𓀀𓏏 ▁𓈎𓊪𓂝 ▁𓎛𓄿𓉔𓂝
[2026-10-15 16:00:42] Best translation 111 : ▁𓈎𓊪𓆑𓈙 ▁𓇌𓐍𓃀 ▁𓆑𓈙 ▁𓉔𓆑𓎛𓂝
[2026-10-15 16:00:42] Best translation 112 : ▁𓈎𓊪𓂝 ▁𓇋𓎡𓈙 ▁𓆑𓈙 ▁𓅱𓎡𓂋𓂋
[2026-10-15 16:00:42] Best translation 113 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓆑𓉔𓂝
[2026-10-15 16:00:42] Best translation 114 : ▁𓆑 ▁𓄿𓉔 ▁𓄿𓈎 ▁𓈙𓆑𓍿
[2026-10-15 16:00:42] Best translation 115 : ▁𓆑𓈙𓎛𓈎 ▁𓈎𓊪𓄿𓈎 ▁𓋴𓆑𓃀𓊪𓈎
[2026-10-15 16:00:42] Best translation 116 : ▁𓂋𓂝𓈎𓈙 ▁𓄡𓋴𓄿𓂧
[2026-10-15 16:00:42] Best translation 117 : ▁𓂨𓀀𓎡 ▁𓈚𓀀𓎡𓎛𓇌 ▁𓈎𓆑𓋴𓂝𓇌
[2026-10-15 16:00:42] Best translation 118 : ▁𓈎𓊪𓂝 ▁𓇋𓂋 ▁𓆑𓈙 ▁𓂝𓄿𓈙𓂧
[2026-10-15 16:00:42] Best translation 119 : ▁𓏏𓂝𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓊪𓄿𓄡𓄡𓂧
[2026-10-15 16:00:42] Best translation 120 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓐍 ▁𓈙𓈎𓄿𓂧
[2026-10-15 16:00:42] Best translation 121 : ▁𓈚𓀀𓋴𓋴𓂧 ▁𓈎𓐍 ▁𓇋𓂝 ▁𓂋𓄿𓈎𓂝
[2026-10-15 16:00:42] Best translation 122 : ▁𓈎𓐍𓉔 ▁𓏏𓄿𓎛𓈎𓂝𓇌 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:00:42] Best translation 123 : ▁𓏏𓊪𓐍𓈙 ▁𓆑𓉔 ▁𓊪𓂝𓋴𓂝
[2026-10-15 16:00:42] Best translation 124 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓎛𓂝𓋴𓎼𓐍𓎡𓈙
[2026-10-15 16:00:42] Best translation 125 : ▁𓆑 ▁𓊪𓄿𓇌 ▁𓉔𓂧 ▁𓇌𓐍𓎡𓇋𓈎𓈙
[2026-10-15 16:00:42] Best translation 126 : ▁𓆑 ▁𓉔𓄿𓇌𓂝 ▁𓈎𓊪𓂝 ▁𓇋𓂝𓈎
[2026-10-15 16:00:42] Best translation 127 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓄿𓂋𓂋 ▁𓊪𓄿𓄡𓄡𓂧
[2026-10-15 16:00:42] Best translation 128 : ▁𓆑 ▁𓉔𓄿𓇌𓂝 ▁𓄿 ▁𓂋𓐍𓈎
[2026-10-15 16:00:42] Best translation 129 : ▁𓂨𓀀𓎡 ▁𓄿𓋴𓂝 ▁𓃀𓋴𓂝𓄿𓈎
[2026-10-15 16:00:42] Best translation 130 : ▁𓆑 ▁𓃀𓐍𓈎 ▁𓊪𓎡𓋴𓈎
[2026-10-15 16:00:42] Best translation 131 : ▁𓏏𓂝 ▁𓎛𓂝𓂝𓇌 ▁𓄿 ▁𓏭𓄿𓇋
[2026-10-15 16:00:42] Best translation 132 : ▁𓈎𓐍𓉔 ▁𓏏𓄿𓈙 ▁𓇌𓐍𓎡𓇋𓈎𓈙
[2026-10-15 16:00:42] Best translation 133 : ▁𓆑𓈎 ▁𓇌𓐍𓂝𓈙𓎛𓈎 ▁𓏭𓋴𓂧
[2026-10-15 16:00:42] Best translation 134 : ▁𓆑𓉔 ▁𓊪𓎡𓎛𓃀 ▁𓐍𓎼𓂝𓋴
[2026-10-15 16:00:42] Best translation 135 : ▁𓏮𓀀𓉔𓂝 ▁𓅓𓐍𓆑𓎛 ▁𓎡𓈙
[2026-10-15 16:00:42] Best translation 136 : ▁𓆑𓉔 ▁𓇌𓂝𓂋𓆑𓃀𓊪𓈎𓂝𓇌
[2026-10-15 16:00:42] Best translation 137 : ▁𓇌𓐍 ▁𓂨𓀀𓎡 ▁𓊪𓄿𓎼𓂝 ▁𓄿 ▁𓎜𓀀𓈎𓂝
[2026-10-15 16:00:42] Best translation 138 : ▁𓏏𓂝 ▁𓏏𓆑𓈙𓊪 ▁𓂨𓀀𓎡 ▁𓂋𓎡𓏭𓈖
[2026-10-15 16:00:43] Best translation 139 : ▁𓇌𓐍𓎛𓈎 ▁𓂋𓐍𓐍𓈖 ▁𓄿𓈎 ▁𓉔𓂝
[2026-10-15 16:00:43] Best translation 140 : ▁𓆑 ▁𓏏𓐍𓈖𓂝 ▁𓎡𓄡
[2026-10-15 16:00:43] Best translation 141 : ▁𓇌𓆑𓇌 ▁𓂨𓀀𓎡 ▁𓇌𓐍 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:00:43] Best translation 142 : ▁𓏏𓂝 ▁𓏭𓄿𓎛 ▁𓈎𓋴𓂧
[2026-10-15 16:00:43] Best translation 143 : ▁𓆑𓂋𓂋 ▁𓃀𓐍 ▁𓈎𓊪𓆑𓈙 ▁𓏏𓄿𓂧
[2026-10-15 16:00:43] Best translation 144 : ▁𓊪𓂝𓈙 ▁𓎜𓀀𓈎 ▁𓆑𓎛 ▁𓂧𓂝𓈎
[2026-10-15 16:00:43] Best translation 145 : ▁𓏭𓄿𓎛 ▁𓆑 ▁𓈙𓈎𓐍𓄡 ▁𓈎𓐍𓉔
[2026-10-15 16:00:43] Best translation 146 : ▁𓈎𓐍𓉔𓈙 ▁𓈙𓄿𓅱𓂝
[2026-10-15 16:00:43] Best translation 147 : ▁𓈎𓐍𓉔 ▁𓊪𓄿𓇌 ▁𓅓𓂝𓄿𓎛𓈙 ▁𓐍𓎛
[2026-10-15 16:00:43] Best translation 148 : ▁𓎜𓀀 ▁𓐍𓎛𓂝 ▁𓏭𓊪𓂝𓄿𓈎𓂝𓇌
[2026-10-15 16:00:43] Best translation 149 : ▁𓆑 ▁𓇌𓂝𓈙𓂝𓋴𓎼𓂝 ▁𓉔𓐍𓋴𓂝
[2026-10-15 16:00:43] Best translation 150 : ▁𓆑 ▁𓋴𓄿𓎛 ▁𓊪𓐍𓉔𓂝
[2026-10-15 16:00:43] Best translation 151 : ▁𓊪𓂝 ▁𓆑𓈙 ▁𓐍𓅱𓅱 ▁𓈖𓂝𓂧
[2026-10-15 16:00:43] Best translation 152 : ▁𓇌𓆑𓇌 ▁𓂨𓀀𓎡 ▁𓇌𓆑𓇌 ▁𓆑𓈎
[2026-10-15 16:00:43] Best translation 153 : ▁𓆑𓉔 ▁𓋴𓄿𓈎𓊪𓂝𓋴 ▁𓈙𓊪𓂧
[2026-10-15 16:00:43] Best translation 154 : ▁𓏏𓂝 ▁𓈙𓊪𓐍𓎡𓂋𓇌 ▁𓏏𓄿𓆑𓈎
[2026-10-15 16:00:43] Best translation 155 : ▁𓆑 ▁𓏏𓐍𓎡𓂋𓇌 ▁𓏭𓄿𓋴𓂝
[2026-10-15 16:00:43] Best translation 156 : ▁𓆑𓈎𓈙 ▁𓐍𓎛𓂋𓂧 ▁𓉔𓐍𓎛𓂝𓂧
[2026-10-15 16:00:43] Best translation 157 : ▁𓆑𓉔 ▁𓅱𓎡𓋴𓆒𓀀𓎡𓈙
[2026-10-15 16:00:43] Best translation 158 : ▁𓆑𓉔 ▁𓇋𓎡𓈙𓂧
[2026-10-15 16:00:43] Best translation 159 : ▁𓈎𓐍𓉔 ▁𓈖𓎜𓀀𓏏 ▁𓈎𓐍𓉔
[2026-10-15 16:00:43] Best translation 160 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓐍𓂋𓇌
[2026-10-15 16:00:43] Best translation 161 : ▁𓊪𓐍𓏏 ▁𓄿 ▁𓇌𓋴𓆑𓎛𓈖
[2026-10-15 16:00:43] Best translation 162 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓄡𓂝𓏭𓎡𓂋 𓆑𓄿𓋴
[2026-10-15 16:00:43] Best translation 163 : ▁𓆑𓉔 ▁𓇋𓄿𓏭𓈖
[2026-10-15 16:00:43] Best translation 164 : ▁𓆑𓉔 ▁𓉔𓂧 ▁𓄡𓄿𓋴𓈎𓎛𓂝𓋴
[2026-10-15 16:00:43] Best translation 165 : ▁𓆑 ▁𓇌𓆑𓇌𓎛𓈎 ▁𓅱𓂋𓎡𓎛𓈖
[2026-10-15 16:00:43] Best translation 166 : ▁𓆑𓂋𓂋 ▁𓈎𓋴𓂧 ▁𓆑𓈎 ▁𓄿𓃀𓄿𓆑𓎛
[2026-10-15 16:00:43] Best translation 167 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓋴𓆑𓏭𓊪
[2026-10-15 16:00:43] Best translation 168 : ▁𓏏𓂝 ▁𓄿𓄡𓐍𓂋𓐍𓃀𓆑𓆓𓂝
[2026-10-15 16:00:43] Best translation 169 : ▁𓂝𓎼𓂝𓋴𓂧𓇋𓐍𓇌𓂧𓈙 ▁𓊪𓄿𓄡𓄡𓂧
[2026-10-15 16:00:43] Best translation 170 : ▁𓊪𓂝𓈙 ▁𓄿 ▁𓃀𓂝𓎛𓈎𓂋𓂝 𓉔𓄿𓎛
[2026-10-15 16:00:43] Best translation 171 : ▁𓈎𓐍𓉔 ▁𓈙𓂝𓂝𓉔𓈙 ▁𓄿𓎛𓃀𓋴𓂧
[2026-10-15 16:00:43] Best translation 172 : ▁𓎜𓀀 ▁𓐍𓎛𓂝 ▁𓏭𓄿𓎛𓈎
[2026-10-15 16:00:43] Best translation 173 : ▁𓈎𓊪𓂝𓂧 ▁𓄿𓄡𓄡 𓋴𓐍𓎼𓂝
[2026-10-15 16:00:43] Best translation 174 : ▁𓆑𓈎 ▁𓏏𓄿𓈙 ▁𓄿𓂋𓂋 ▁𓏏𓋴𓐍𓎛𓃀
[2026-10-15 16:00:43] Best translation 175 : ▁𓈎𓊪𓂝𓂧 ▁𓏏𓂝𓋴𓂝 ▁𓇋𓐍𓋴𓂝𓇌
[2026-10-15 16:00:43] Best translation 176 : ▁𓆑 ▁𓄿𓉔 ▁𓅓𓐍𓈖𓆑𓎛𓃀
[2026-10-15 16:00:43] Best translation 177 : ▁𓆑 ▁𓇌𓐍𓎛𓈎 ▁𓏏𓐍𓋴𓈖
[2026-10-15 16:00:43] Best translation 178 : ▁𓊪𓂝 ▁𓏏𓂝𓎛𓈎 ▁𓄿𓏏𓄿𓂧
[2026-10-15 16:00:43] Best translation 179 : ▁𓆑 ▁𓇋𓎡𓋴𓎛𓂝𓇌 ▁𓈎𓊪𓂝𓉔

In [29]:
import sentencepiece as spm

hi_spm = spm.SentencePieceProcessor(model_file="hi_spm.model")

with open(
    "/kaggle/working/output/transformer/test.output.hi.spm", "r", encoding="utf-8"
) as f_in, open("/kaggle/working/output/transformer/test.output.hi", "w", encoding="utf-8") as f_out:
  for line in f_in:
    pieces = line.strip().split()
    decoded_text = my_spm.decode(pieces)
    f_out.write(decoded_text + "\n")

print("Test set successfully detokenized!")
print("----Scoring Burmese -> Hieroglyph Transformer Model")
!sacrebleu /kaggle/working/data/test.hi -i /kaggle/working/output/transformer/test.output.hi

Test set successfully detokenized!
----Scoring Burmese -> Hieroglyph Transformer Model
{
 "name": "BLEU",
 "score": 0.0,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.6.0",
 "verbose_score": "0.0/0.0/0.0/0.0 (BP = 0.117 ratio = 0.318 hyp_len = 500 ref_len = 1573)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.6.0"
}

In [30]:
!sacrebleu /kaggle/working/data/test.hi -i /kaggle/working/output/transformer/test.output.hi --tok char

{
 "name": "BLEU",
 "score": 20.8,
 "signature": "nrefs:1|case:mixed|eff:no|tok:char|smooth:exp|version:2.6.0",
 "verbose_score": "48.5/27.0/16.4/8.6 (BP = 1.000 ratio = 1.278 hyp_len = 7201 ref_len = 5636)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "char",
 "smooth": "exp",
 "version": "2.6.0"
}

In [31]:
!sacrebleu /kaggle/working/data/test.hi -i /kaggle/working/output/transformer/test.output.hi -m chrf

{
 "name": "chrF2",
 "score": 21.9,
 "signature": "nrefs:1|case:mixed|eff:yes|nc:6|nw:0|space:no|version:2.6.0",
 "nrefs": "1",
 "case": "mixed",
 "eff": "yes",
 "nc": "6",
 "nw": "0",
 "space": "no",
 "version": "2.6.0"
}

In [35]:
import pandas as pd

# Define paths to your test dataset files
src_file = "/kaggle/working/data/test.my"
ref_file = "/kaggle/working/data/test.hi"
pred_file = "/kaggle/working/output/transformer/test.output.hi"

# Read lines from all three files
with open(src_file, "r", encoding="utf-8") as f_src, open(
    ref_file, "r", encoding="utf-8"
) as f_ref, open(pred_file, "r", encoding="utf-8") as f_pred:
  src_lines = [line.strip() for line in f_src]
  ref_lines = [line.strip() for line in f_ref]
  pred_lines = [line.strip() for line in f_pred]

# Select 10 sample indices to inspect
sample_indices = [0, 1, 2, 5, 10, 20, 40, 80, 160, 320]

samples = []
for idx in sample_indices:
  if idx < len(src_lines):
    samples.append({
        "Index": idx,
        "Source (Burmese)": src_lines[idx],
        "Reference (Hieroglyphs)": ref_lines[idx],
        "Prediction (Hieroglyphs)": pred_lines[idx],
    })

# Format as a clean Pandas DataFrame for easy viewing
df_samples = pd.DataFrame(samples)
pd.set_option("display.max_colwidth", None)
display(df_samples)

,Index,Source (Burmese),Reference (Hieroglyphs),Prediction (Hieroglyphs)
0,0,အချစ်က နာကျင်စေတယ်။,𓂋𓐍𓎼𓂝 𓊪𓎡𓋴𓈎𓈙,▁𓈎𓊪𓆑𓈙▁𓆑𓈙▁𓂨𓀀𓎡𓋴𓎛𓈙
1,1,ကျွန်မမှာ အစားအစာမရှိဘူး။,𓆑 𓊪𓄿𓎼𓂝 𓎜𓀀 𓅲𓀀𓐍𓇌,▁𓈎𓊪𓂝𓋴𓂝𓈙▁𓎜𓀀▁𓅲𓀀𓐍𓇌
2,2,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။,𓎜𓀀 𓐍𓎛𓂝 𓈙𓄿𓏏 𓉔𓂝,▁𓎜𓀀𓇋𓐍𓇌𓂧▁𓈙𓄿𓏏▁𓉔𓂝
3,5,ခရီးကောင်းပါ,𓊪𓄿𓎼𓂝 𓄿 𓎛𓆑𓏭𓂝 𓈎𓋴𓆑𓄡,▁𓊪𓄿𓎼𓂝▁𓄿▁𓈙𓄿𓅱𓂝▁𓈎𓋴𓆑𓄡
4,10,နင့်နံ့က ကောင်းတယ်,𓂨𓀀𓎡 𓈙𓉔𓂝𓂋𓂋 𓃀𓐍𓐍𓇌,▁𓆑𓈎▁𓆑𓈙▁𓇋𓐍𓋴𓆑𓎛𓃀
5,20,ဒါက ကြီးမားပါတယ်။,𓈎𓊪𓆑𓈙 𓆑𓈙 𓊪𓎡𓃀𓂝,▁𓈎𓊪𓆑𓈙▁𓆑𓈙▁𓇋𓆑𓃀
6,40,ကံမကောင်းခဲ့ဘူး။,𓆑𓈎 𓏏𓄿𓈙𓎛𓈎 𓂋𓎡𓏭𓈖,▁𓏏𓂝▁𓏏𓂝𓋴𓂝𓎛𓈎▁𓂋𓎡𓏭𓈖𓂧
7,80,သူတွေ့တယ်။,𓊪𓂝 𓅲𓀀𓎡𓎛𓇌 𓆑𓈎,▁𓊪𓂝▁𓏏𓄿𓈙▁𓐍𓎡𓈎𓋴𓄿𓃀𓂝𓇌
8,160,ပိုဆိုးလာတယ်,𓆑𓈎 𓃀𓂝𓈎𓈙 𓏏𓐍𓋴𓈙𓂝,▁𓆑𓈎▁𓇋𓂝𓃀𓄿𓎛▁𓈎𓐍▁𓉔𓂝
9,320,ကျွန်တော် အလုပ်ကြိုးစားတယ်။,𓆑𓂋𓂋 𓏏𓐍𓋴𓈖 𓊪𓄿𓋴𓇌,▁𓆑𓉔▁𓊪𓄿𓋴𓇌𓏏𓐍𓋴𓈖𓆑𓎛𓃀

In [36]:
import pandas as pd

# Define paths to your test dataset files
src_file = "/kaggle/working/data/test.hi"
ref_file = "/kaggle/working/data/test.my"
pred_file = "/kaggle/working/output/transformer/test.output.my"

# Read lines from all three files
with open(src_file, "r", encoding="utf-8") as f_src, open(
    ref_file, "r", encoding="utf-8"
) as f_ref, open(pred_file, "r", encoding="utf-8") as f_pred:
  src_lines = [line.strip() for line in f_src]
  ref_lines = [line.strip() for line in f_ref]
  pred_lines = [line.strip() for line in f_pred]

# Select 10 sample indices to inspect
sample_indices = [0, 1, 2, 5, 10, 20, 40, 80, 160, 320]

samples = []
for idx in sample_indices:
  if idx < len(src_lines):
    samples.append({
        "Index": idx,
        "Source (Hieroglyphs)": src_lines[idx],
        "Reference (Burmese)": ref_lines[idx],
        "Prediction (Burmese)": pred_lines[idx],
    })

# Format as a clean Pandas DataFrame for easy viewing
df_samples = pd.DataFrame(samples)
pd.set_option("display.max_colwidth", None)
display(df_samples)

,Index,Source (Hieroglyphs),Reference (Burmese),Prediction (Burmese)
0,0,𓂋𓐍𓎼𓂝 𓊪𓎡𓋴𓈎𓈙,အချစ်က နာကျင်စေတယ်။,နာကျင်တယ်
1,1,𓆑 𓊪𓄿𓎼𓂝 𓎜𓀀 𓅲𓀀𓐍𓇌,ကျွန်မမှာ အစားအစာမရှိဘူး။,ကျွန်မမှာ အစားအစာရှိတယ်
2,2,𓎜𓀀 𓐍𓎛𓂝 𓈙𓄿𓏏 𓉔𓂝,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။
3,5,𓊪𓄿𓎼𓂝 𓄿 𓎛𓆑𓏭𓂝 𓈎𓋴𓆑𓄡,ခရီးကောင်းပါ,ခရီးကောင်းပါ
4,10,𓂨𓀀𓎡 𓈙𓉔𓂝𓂋𓂋 𓃀𓐍𓐍𓇌,နင့်နံ့က ကောင်းတယ်,နှင်းဆီတွေက အနံ့ကောင်းတယ်။
5,20,𓈎𓊪𓆑𓈙 𓆑𓈙 𓊪𓎡𓃀𓂝,ဒါက ကြီးမားပါတယ်။,ဒါက ခွေးတစ်ကောင်ပါ။
6,40,𓆑𓈎 𓏏𓄿𓈙𓎛𓈎 𓂋𓎡𓏭𓈖,ကံမကောင်းခဲ့ဘူး။,အဲဒါက ငါ့ဟာ မဟုတ်ခဲ့ဘူး။
7,80,𓊪𓂝 𓅲𓀀𓎡𓎛𓇌 𓆑𓈎,သူတွေ့တယ်။,သူက ကျွန်တော့်စက်ဘီးကိုတွေ့တယ်
8,160,𓆑𓈎 𓃀𓂝𓈎𓈙 𓏏𓐍𓋴𓈙𓂝,ပိုဆိုးလာတယ်,ဒါဟာ အမှန်ဖြစ်လောက်တယ်။
9,320,𓆑𓂋𓂋 𓏏𓐍𓋴𓈖 𓊪𓄿𓋴𓇌,ကျွန်တော် အလုပ်ကြိုးစားတယ်။,အလုပ်မကောင်းခြင်း

In [10]:
%%writefile /kaggle/working/config/seq2seq/hi2my/config.yml
devices: [0]
model: /kaggle/working/models/seq2seq/hi-my-rnn.npz
type: s2s

train-sets:
  - /kaggle/working/data/train.hi.spm
  - /kaggle/working/data/train.my.spm
vocabs:
  - /kaggle/working/data/hi.vocab.yml
  - /kaggle/working/data/my.vocab.yml

valid-sets:
  - /kaggle/working/data/valid.hi.spm
  - /kaggle/working/data/valid.my.spm
valid-freq: 100
valid-metrics: [cross-entropy, bleu]
early-stopping: 15

after-batches: 5000
mini-batch-words: 2048
workspace: 4096
optimizer: adam
learn-rate: 0.0003
lr-warmup: 500

# RNN Regularization & Architecture
enc-type: bidirectional
enc-cell: gru
dec-cell: gru
dropout-rnn: 0.2
dropout-src: 0.2
dropout-trg: 0.2
dim-emb: 512
dim-rnn: 1024
enc-depth: 1
dec-depth: 1

Overwriting /kaggle/working/config/seq2seq/hi2my/config.yml

In [11]:
%%writefile /kaggle/working/config/seq2seq/my2hi/config.yml
devices: [0]
model: /kaggle/working/models/seq2seq/my-hi-rnn.npz
type: s2s

train-sets:
  - /kaggle/working/data/train.my.spm
  - /kaggle/working/data/train.hi.spm
vocabs:
  - /kaggle/working/data/my.vocab.yml
  - /kaggle/working/data/hi.vocab.yml

valid-sets:
  - /kaggle/working/data/valid.my.spm
  - /kaggle/working/data/valid.hi.spm
valid-freq: 100
valid-metrics: [cross-entropy, bleu]
early-stopping: 15

after-batches: 5000
mini-batch-words: 2048
workspace: 4096
optimizer: adam
learn-rate: 0.0003
lr-warmup: 500

# RNN Regularization & Architecture
enc-type: bidirectional
enc-cell: gru
dec-cell: gru
dropout-rnn: 0.2
dropout-src: 0.2
dropout-trg: 0.2
dim-emb: 512
dim-rnn: 1024
enc-depth: 1
dec-depth: 1

Writing /kaggle/working/config/seq2seq/my2hi/config.yml

In [12]:
MARIAN_TRAIN = "/kaggle/working/marian-dev/build/marian"

print("--- Training Hieroglyph -> Burmese RNN Model ---")
!{MARIAN_TRAIN} --config /kaggle/working/config/seq2seq/hi2my/config.yml

--- Training Hieroglyph -> Burmese RNN Model ---
[2026-10-15 14:27:34] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 14:27:34] [marian] Running on f2fe76130532 as process 18376 with command line:
[2026-10-15 14:27:34] [marian] /kaggle/working/marian-dev/build/marian --config /kaggle/working/config/seq2seq/hi2my/config.yml
[2026-10-15 14:27:34] [config] after: 0e
[2026-10-15 14:27:34] [config] after-batches: 5000
[2026-10-15 14:27:34] [config] after-epochs: 0
[2026-10-15 14:27:34] [config] all-caps-every: 0
[2026-10-15 14:27:34] [config] allow-unk: false
[2026-10-15 14:27:34] [config] authors: false
[2026-10-15 14:27:34] [config] beam-size: 12
[2026-10-15 14:27:34] [config] bert-class-symbol: "[CLS]"
[2026-10-15 14:27:34] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 14:27:34] [config] bert-masking-fraction: 0.15
[2026-10-15 14:27:34] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 14:27:34] [config] bert-train-type-embeddings: true
[2026-10-15 14:27:34] [config] bert-type-vocab-size: 2
[2026-10-15 14:27:34] [config] build-info: ""
[2026-10-15 14:27:34] [config] check-gradient-nan: false
[2026-10-15 14:27:34] [config] check-nan: false
[2026-10-15 14:27:34] [config] cite: false
[2026-10-15 14:27:34] [config] clip-norm: 1
[2026-10-15 14:27:34] [config] comet-augment-bad: 0
[2026-10-15 14:27:34] [config] comet-dropout: 0.1
[2026-10-15 14:27:34] [config] comet-final-sigmoid: false
[2026-10-15 14:27:34] [config] comet-mix: false
[2026-10-15 14:27:34] [config] comet-mix-norm: false
[2026-10-15 14:27:34] [config] comet-mix-transformation: softmax
[2026-10-15 14:27:34] [config] comet-mixup: 0
[2026-10-15 14:27:34] [config] comet-mixup-reg: false
[2026-10-15 14:27:34] [config] comet-pool: avg
[2026-10-15 14:27:34] [config] comet-pooler-ffn:
[2026-10-15 14:27:34] [config]   - 2048
[2026-10-15 14:27:34] [config]   - 1024
[2026-10-15 14:27:34] [config] comet-prepend-zero: false
[2026-10-15 14:27:34] [config] comet-stop-grad: false
[2026-10-15 14:27:34] [config] comet-use-separator: false
[2026-10-15 14:27:34] [config] cost-scaling:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] cost-type: ce-sum
[2026-10-15 14:27:34] [config] cpu-threads: 0
[2026-10-15 14:27:34] [config] custom-fallbacks:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] data-threads: 8
[2026-10-15 14:27:34] [config] data-weighting: ""
[2026-10-15 14:27:34] [config] data-weighting-type: sentence
[2026-10-15 14:27:34] [config] dec-cell: gru
[2026-10-15 14:27:34] [config] dec-cell-base-depth: 2
[2026-10-15 14:27:34] [config] dec-cell-high-depth: 1
[2026-10-15 14:27:34] [config] dec-depth: 1
[2026-10-15 14:27:34] [config] devices:
[2026-10-15 14:27:34] [config]   - 0
[2026-10-15 14:27:34] [config] dim-emb: 512
[2026-10-15 14:27:34] [config] dim-rnn: 1024
[2026-10-15 14:27:34] [config] dim-vocabs:
[2026-10-15 14:27:34] [config]   - 0
[2026-10-15 14:27:34] [config]   - 0
[2026-10-15 14:27:34] [config] disp-first: 0
[2026-10-15 14:27:34] [config] disp-freq: 1000u
[2026-10-15 14:27:34] [config] disp-label-counts: true
[2026-10-15 14:27:34] [config] dropout-rnn: 0.2
[2026-10-15 14:27:34] [config] dropout-src: 0.2
[2026-10-15 14:27:34] [config] dropout-trg: 0.2
[2026-10-15 14:27:34] [config] dump-config: ""
[2026-10-15 14:27:34] [config] dynamic-gradient-scaling:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] early-stopping: 15
[2026-10-15 14:27:34] [config] early-stopping-epsilon:
[2026-10-15 14:27:34] [config]   - 0
[2026-10-15 14:27:34] [config] early-stopping-on: first
[2026-10-15 14:27:34] [config] embedding-fix-src: false
[2026-10-15 14:27:34] [config] embedding-fix-trg: false
[2026-10-15 14:27:34] [config] embedding-normalization: false
[2026-10-15 14:27:34] [config] embedding-vectors:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] enc-cell: gru
[2026-10-15 14:27:34] [config] enc-cell-depth: 1
[2026-10-15 14:27:34] [config] enc-depth: 1
[2026-10-15 14:27:34] [config] enc-type: bidirectional
[2026-10-15 14:27:34] [config] english-title-case-every: 0
[2026-10-15 14:27:34] [config] exponential-smoothing: 0
[2026-10-15 14:27:34] [config] exponential-smoothing-replace-freq: 0
[2026-10-15 14:27:34] [config] factor-weight: 1
[2026-10-15 14:27:34] [config] factors-combine: sum
[2026-10-15 14:27:34] [config] factors-dim-emb: 0
[2026-10-15 14:27:34] [config] gradient-checkpointing: false
[2026-10-15 14:27:34] [config] gradient-norm-average-window: 100
[2026-10-15 14:27:34] [config] guided-alignment: none
[2026-10-15 14:27:34] [config] guided-alignment-cost: ce
[2026-10-15 14:27:34] [config] guided-alignment-weight: 0.1
[2026-10-15 14:27:34] [config] ignore-model-config: false
[2026-10-15 14:27:34] [config] input-join-fields: false
[2026-10-15 14:27:34] [config] input-reorder:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] input-types:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] interpolate-env-vars: false
[2026-10-15 14:27:34] [config] keep-best: false
[2026-10-15 14:27:34] [config] label-smoothing: 0
[2026-10-15 14:27:34] [config] layer-normalization: false
[2026-10-15 14:27:34] [config] learn-rate: 0.0003
[2026-10-15 14:27:34] [config] lemma-dependency: ""
[2026-10-15 14:27:34] [config] lemma-dim-emb: 0
[2026-10-15 14:27:34] [config] log: ""
[2026-10-15 14:27:34] [config] log-level: info
[2026-10-15 14:27:34] [config] log-time-zone: ""
[2026-10-15 14:27:34] [config] logical-epoch:
[2026-10-15 14:27:34] [config]   - 1e
[2026-10-15 14:27:34] [config]   - 0
[2026-10-15 14:27:34] [config] lr-decay: 0
[2026-10-15 14:27:34] [config] lr-decay-freq: 50000
[2026-10-15 14:27:34] [config] lr-decay-inv-sqrt:
[2026-10-15 14:27:34] [config]   - 0
[2026-10-15 14:27:34] [config] lr-decay-repeat-warmup: false
[2026-10-15 14:27:34] [config] lr-decay-reset-optimizer: false
[2026-10-15 14:27:34] [config] lr-decay-start:
[2026-10-15 14:27:34] [config]   - 10
[2026-10-15 14:27:34] [config]   - 1
[2026-10-15 14:27:34] [config] lr-decay-strategy: epoch+stalled
[2026-10-15 14:27:34] [config] lr-report: false
[2026-10-15 14:27:34] [config] lr-warmup: 500
[2026-10-15 14:27:34] [config] lr-warmup-at-reload: false
[2026-10-15 14:27:34] [config] lr-warmup-cycle: false
[2026-10-15 14:27:34] [config] lr-warmup-start-rate: 0
[2026-10-15 14:27:34] [config] max-length: 50
[2026-10-15 14:27:34] [config] max-length-crop: false
[2026-10-15 14:27:34] [config] max-length-factor: 3
[2026-10-15 14:27:34] [config] maxi-batch: 100
[2026-10-15 14:27:34] [config] maxi-batch-sort: trg
[2026-10-15 14:27:34] [config] mini-batch: 64
[2026-10-15 14:27:34] [config] mini-batch-fit: false
[2026-10-15 14:27:34] [config] mini-batch-fit-step: 10
[2026-10-15 14:27:34] [config] mini-batch-round-up: true
[2026-10-15 14:27:34] [config] mini-batch-track-lr: false
[2026-10-15 14:27:34] [config] mini-batch-warmup: 0
[2026-10-15 14:27:34] [config] mini-batch-words: 2048
[2026-10-15 14:27:34] [config] mini-batch-words-ref: 0
[2026-10-15 14:27:34] [config] model: /kaggle/working/models/seq2seq/hi-my-rnn.npz
[2026-10-15 14:27:34] [config] multi-loss-type: sum
[2026-10-15 14:27:34] [config] n-best: false
[2026-10-15 14:27:34] [config] no-nccl: false
[2026-10-15 14:27:34] [config] no-optimizer-reload: false
[2026-10-15 14:27:34] [config] no-reload: false
[2026-10-15 14:27:34] [config] no-restore-corpus: false
[2026-10-15 14:27:34] [config] no-spm-encode: false
[2026-10-15 14:27:34] [config] normalize: 0
[2026-10-15 14:27:34] [config] normalize-gradient: false
[2026-10-15 14:27:34] [config] normalize-gradient-by-ratio: false
[2026-10-15 14:27:34] [config] optimizer: adam
[2026-10-15 14:27:34] [config] optimizer-delay: 1
[2026-10-15 14:27:34] [config] optimizer-params:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] output-omit-bias: false
[2026-10-15 14:27:34] [config] overwrite: false
[2026-10-15 14:27:34] [config] overwrite-checkpoint: true
[2026-10-15 14:27:34] [config] precision:
[2026-10-15 14:27:34] [config]   - float32
[2026-10-15 14:27:34] [config]   - float32
[2026-10-15 14:27:34] [config] pretrained-model: ""
[2026-10-15 14:27:34] [config] quantize-biases: false
[2026-10-15 14:27:34] [config] quantize-bits: 0
[2026-10-15 14:27:34] [config] quantize-log-based: false
[2026-10-15 14:27:34] [config] quantize-optimization-steps: 0
[2026-10-15 14:27:34] [config] quiet: false
[2026-10-15 14:27:34] [config] quiet-translation: false
[2026-10-15 14:27:34] [config] quiet-validation: false
[2026-10-15 14:27:34] [config] relative-paths: false
[2026-10-15 14:27:34] [config] right-left: false
[2026-10-15 14:27:34] [config] save-freq: 10000u
[2026-10-15 14:27:34] [config] seed: 0
[2026-10-15 14:27:34] [config] sentencepiece-alphas:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] sentencepiece-max-lines: 2000000
[2026-10-15 14:27:34] [config] sentencepiece-options: ""
[2026-10-15 14:27:34] [config] separator-symbol: "[eos]"
[2026-10-15 14:27:34] [config] sharding: global
[2026-10-15 14:27:34] [config] shuffle: data
[2026-10-15 14:27:34] [config] shuffle-in-ram: false
[2026-10-15 14:27:34] [config] sigterm: save-and-exit
[2026-10-15 14:27:34] [config] skip: false
[2026-10-15 14:27:34] [config] sqlite: ""
[2026-10-15 14:27:34] [config] sqlite-drop: false
[2026-10-15 14:27:34] [config] sync-freq: 200u
[2026-10-15 14:27:34] [config] sync-sgd: false
[2026-10-15 14:27:34] [config] tempdir: /tmp
[2026-10-15 14:27:34] [config] throw-on-divergence:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] tied-embeddings: false
[2026-10-15 14:27:34] [config] tied-embeddings-all: false
[2026-10-15 14:27:34] [config] tied-embeddings-src: false
[2026-10-15 14:27:34] [config] train-embedder-rank:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] train-sets:
[2026-10-15 14:27:34] [config]   - /kaggle/working/data/train.hi.spm
[2026-10-15 14:27:34] [config]   - /kaggle/working/data/train.my.spm
[2026-10-15 14:27:34] [config] transformer-aan-activation: swish
[2026-10-15 14:27:34] [config] transformer-aan-depth: 2
[2026-10-15 14:27:34] [config] transformer-aan-nogate: false
[2026-10-15 14:27:34] [config] transformer-alibi-shift: false
[2026-10-15 14:27:34] [config] transformer-alibi-trainable: false
[2026-10-15 14:27:34] [config] transformer-attention-mask: default
[2026-10-15 14:27:34] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 14:27:34] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 14:27:34] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 14:27:34] [config] transformer-depth-scaling: false
[2026-10-15 14:27:34] [config] transformer-dim-aan: 2048
[2026-10-15 14:27:34] [config] transformer-dim-ffn: 2048
[2026-10-15 14:27:34] [config] transformer-disable-position-embeddings: false
[2026-10-15 14:27:34] [config] transformer-dropout: 0
[2026-10-15 14:27:34] [config] transformer-dropout-attention: 0
[2026-10-15 14:27:34] [config] transformer-dropout-ffn: 0
[2026-10-15 14:27:34] [config] transformer-ffn-activation: swish
[2026-10-15 14:27:34] [config] transformer-ffn-depth: 2
[2026-10-15 14:27:34] [config] transformer-guided-alignment-layer: last
[2026-10-15 14:27:34] [config] transformer-heads: 8
[2026-10-15 14:27:34] [config] transformer-no-affine: false
[2026-10-15 14:27:34] [config] transformer-no-bias: false
[2026-10-15 14:27:34] [config] transformer-no-projection: false
[2026-10-15 14:27:34] [config] transformer-pool: false
[2026-10-15 14:27:34] [config] transformer-postprocess: dan
[2026-10-15 14:27:34] [config] transformer-postprocess-emb: d
[2026-10-15 14:27:34] [config] transformer-postprocess-top: ""
[2026-10-15 14:27:34] [config] transformer-preprocess: ""
[2026-10-15 14:27:34] [config] transformer-rnn-projection: false
[2026-10-15 14:27:34] [config] transformer-tied-layers:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] transformer-train-position-embeddings: false
[2026-10-15 14:27:34] [config] tsv: false
[2026-10-15 14:27:34] [config] tsv-fields: 0
[2026-10-15 14:27:34] [config] type: s2s
[2026-10-15 14:27:34] [config] ulr: false
[2026-10-15 14:27:34] [config] ulr-dim-emb: 0
[2026-10-15 14:27:34] [config] ulr-dropout: 0
[2026-10-15 14:27:34] [config] ulr-keys-vectors: ""
[2026-10-15 14:27:34] [config] ulr-query-vectors: ""
[2026-10-15 14:27:34] [config] ulr-softmax-temperature: 1
[2026-10-15 14:27:34] [config] ulr-trainable-transformation: false
[2026-10-15 14:27:34] [config] unlikelihood-loss: false
[2026-10-15 14:27:34] [config] valid-freq: 100
[2026-10-15 14:27:34] [config] valid-log: ""
[2026-10-15 14:27:34] [config] valid-max-length: 1000
[2026-10-15 14:27:34] [config] valid-metrics:
[2026-10-15 14:27:34] [config]   - cross-entropy
[2026-10-15 14:27:34] [config]   - bleu
[2026-10-15 14:27:34] [config] valid-mini-batch: 32
[2026-10-15 14:27:34] [config] valid-reset-all: false
[2026-10-15 14:27:34] [config] valid-reset-stalled: false
[2026-10-15 14:27:34] [config] valid-script-args:
[2026-10-15 14:27:34] [config]   []
[2026-10-15 14:27:34] [config] valid-script-path: ""
[2026-10-15 14:27:34] [config] valid-sets:
[2026-10-15 14:27:34] [config]   - /kaggle/working/data/valid.hi.spm
[2026-10-15 14:27:34] [config]   - /kaggle/working/data/valid.my.spm
[2026-10-15 14:27:34] [config] valid-translation-output: ""
[2026-10-15 14:27:34] [config] vocabs:
[2026-10-15 14:27:34] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 14:27:34] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 14:27:34] [config] word-penalty: 0
[2026-10-15 14:27:34] [config] word-scores: false
[2026-10-15 14:27:34] [config] workspace: 4096
[2026-10-15 14:27:34] [config] Model is being created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 14:27:34] [training] Using single-device training
[2026-10-15 14:27:34] [comm] Compiled without MPI support. Running as a single process on f2fe76130532
[2026-10-15 14:27:34] Synced seed 1792074454
[2026-10-15 14:27:34] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 14:27:34] [data] Setting vocabulary size for input 0 to 2,988
[2026-10-15 14:27:34] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 14:27:34] [data] Setting vocabulary size for input 1 to 6,014
[2026-10-15 14:27:35] [memory] Extending reserved space to 4096 MB (device gpu0)
[2026-10-15 14:27:35] [comm] Using NCCL 2.8.3 for GPU communication
[2026-10-15 14:27:35] [comm] Using global sharding
[2026-10-15 14:27:35] [comm] NCCLCommunicators constructed successfully
[2026-10-15 14:27:35] [training] Using 1 GPUs
[2026-10-15 14:27:35] Training started
[2026-10-15 14:27:35] [data] Shuffling data
[2026-10-15 14:27:35] [data] Done reading 8,500 sentences
[2026-10-15 14:27:35] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:35] [training] Batches are processed as 1 process(es) x 1 devices/process
[2026-10-15 14:27:35] [logits] Applying loss function for 1 factor(s)
[2026-10-15 14:27:35] [memory] Reserving 158 MB, device gpu0
[2026-10-15 14:27:35] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 14:27:35] [memory] Reserving 158 MB, device gpu0
[2026-10-15 14:27:35] Parameter type float32, optimization type float32, casting types false
[2026-10-15 14:27:35] Allocating memory for Adam-specific shards
[2026-10-15 14:27:35] [memory] Reserving 316 MB, device gpu0
[2026-10-15 14:27:37] Seen 8,500 samples
[2026-10-15 14:27:37] Starting data epoch 2 in logical epoch 2
[2026-10-15 14:27:37] [data] Shuffling data
[2026-10-15 14:27:37] [data] Done reading 8,500 sentences
[2026-10-15 14:27:37] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:38] Seen 8,500 samples
[2026-10-15 14:27:38] Starting data epoch 3 in logical epoch 3
[2026-10-15 14:27:38] [data] Shuffling data
[2026-10-15 14:27:38] [data] Done reading 8,500 sentences
[2026-10-15 14:27:38] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:40] Seen 8,500 samples
[2026-10-15 14:27:40] Starting data epoch 4 in logical epoch 4
[2026-10-15 14:27:40] [data] Shuffling data
[2026-10-15 14:27:40] [data] Done reading 8,500 sentences
[2026-10-15 14:27:40] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:41] Seen 8,500 samples
[2026-10-15 14:27:41] Starting data epoch 5 in logical epoch 5
[2026-10-15 14:27:41] [data] Shuffling data
[2026-10-15 14:27:41] [data] Done reading 8,500 sentences
[2026-10-15 14:27:41] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:43] Seen 8,500 samples
[2026-10-15 14:27:43] Starting data epoch 6 in logical epoch 6
[2026-10-15 14:27:43] [data] Shuffling data
[2026-10-15 14:27:43] [data] Done reading 8,500 sentences
[2026-10-15 14:27:43] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:44] [valid] Ep. 6 : Up. 100 : cross-entropy : 28.0055 : new best
[2026-10-15 14:27:44] Translating validation set...
[2026-10-15 14:27:44] [valid] References contain unknown word, metric scores may be inaccurate
[2026-10-15 14:27:44] [valid] First sentence's tokens as scored:
[2026-10-15 14:27:44] [valid] DefaultVocab keeps original segments for scoring
[2026-10-15 14:27:44] [valid]   Hyp:
[2026-10-15 14:27:44] [valid]   Ref: ▁ဒါက <unk> <unk> <unk> <unk> သွား တဲ့ လမ်းပါ။
[2026-10-15 14:27:44] Best translation 0 :
[2026-10-15 14:27:44] Best translation 1 :
[2026-10-15 14:27:44] Best translation 2 :
[2026-10-15 14:27:44] Best translation 3 :
[2026-10-15 14:27:44] Best translation 4 :
[2026-10-15 14:27:44] Best translation 5 :
[2026-10-15 14:27:44] Best translation 10 :
[2026-10-15 14:27:44] Best translation 20 :
[2026-10-15 14:27:44] Best translation 40 :
[2026-10-15 14:27:44] Best translation 80 :
[2026-10-15 14:27:44] Best translation 160 :
[2026-10-15 14:27:44] Best translation 320 :
[2026-10-15 14:27:44] Best translation 640 :
[2026-10-15 14:27:44] Total translation time: 0.25326s
[2026-10-15 14:27:44] [valid] Ep. 6 : Up. 100 : bleu : 0 : new best
[2026-10-15 14:27:45] Seen 8,500 samples
[2026-10-15 14:27:45] Starting data epoch 7 in logical epoch 7
[2026-10-15 14:27:45] [data] Shuffling data
[2026-10-15 14:27:45] [data] Done reading 8,500 sentences
[2026-10-15 14:27:45] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:47] Seen 8,500 samples
[2026-10-15 14:27:47] Starting data epoch 8 in logical epoch 8
[2026-10-15 14:27:47] [data] Shuffling data
[2026-10-15 14:27:47] [data] Done reading 8,500 sentences
[2026-10-15 14:27:47] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:48] Seen 8,500 samples
[2026-10-15 14:27:48] Starting data epoch 9 in logical epoch 9
[2026-10-15 14:27:48] [data] Shuffling data
[2026-10-15 14:27:48] [data] Done reading 8,500 sentences
[2026-10-15 14:27:48] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:50] Seen 8,500 samples
[2026-10-15 14:27:50] Starting data epoch 10 in logical epoch 10
[2026-10-15 14:27:50] [data] Shuffling data
[2026-10-15 14:27:50] [data] Done reading 8,500 sentences
[2026-10-15 14:27:50] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:51] Seen 8,500 samples
[2026-10-15 14:27:51] Starting data epoch 11 in logical epoch 11
[2026-10-15 14:27:51] [data] Shuffling data
[2026-10-15 14:27:51] [data] Done reading 8,500 sentences
[2026-10-15 14:27:51] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:27:53] [valid] Ep. 11 : Up. 200 : cross-entropy : 26.4887 : new best
[2026-10-15 14:27:53] Translating validation set...
[2026-10-15 14:27:53] Best translation 0 :
[2026-10-15 14:27:53] Best translation 1 :
[2026-10-15 14:27:53] Best translation 2 :
[2026-10-15 14:27:53] Best translation 3 :
[2026-10-15 14:27:53] Best translation 4 :
[2026-10-15 14:27:53] Best translation 5 :
[2026-10-15 14:27:53] Best translation 10 :
[2026-10-15 14:27:53] Best translation 20 :
[2026-10-15 14:27:53] Best translation 40 :
[2026-10-15 14:27:53] Best translation 80 :

In [13]:
MARIAN_TRAIN = "/kaggle/working/marian-dev/build/marian"

print("--- Training Burmese -> Hieroglyph RNN Model ---")
!{MARIAN_TRAIN} --config /kaggle/working/config/seq2seq/my2hi/config.yml

--- Training Burmese -> Hieroglyph RNN Model ---
[2026-10-15 14:40:25] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 14:40:25] [marian] Running on f2fe76130532 as process 18422 with command line:
[2026-10-15 14:40:25] [marian] /kaggle/working/marian-dev/build/marian --config /kaggle/working/config/seq2seq/my2hi/config.yml
[2026-10-15 14:40:25] [config] after: 0e
[2026-10-15 14:40:25] [config] after-batches: 5000
[2026-10-15 14:40:25] [config] after-epochs: 0
[2026-10-15 14:40:25] [config] all-caps-every: 0
[2026-10-15 14:40:25] [config] allow-unk: false
[2026-10-15 14:40:25] [config] authors: false
[2026-10-15 14:40:25] [config] beam-size: 12
[2026-10-15 14:40:25] [config] bert-class-symbol: "[CLS]"
[2026-10-15 14:40:25] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 14:40:25] [config] bert-masking-fraction: 0.15
[2026-10-15 14:40:25] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 14:40:25] [config] bert-train-type-embeddings: true
[2026-10-15 14:40:25] [config] bert-type-vocab-size: 2
[2026-10-15 14:40:25] [config] build-info: ""
[2026-10-15 14:40:25] [config] check-gradient-nan: false
[2026-10-15 14:40:25] [config] check-nan: false
[2026-10-15 14:40:25] [config] cite: false
[2026-10-15 14:40:25] [config] clip-norm: 1
[2026-10-15 14:40:25] [config] comet-augment-bad: 0
[2026-10-15 14:40:25] [config] comet-dropout: 0.1
[2026-10-15 14:40:25] [config] comet-final-sigmoid: false
[2026-10-15 14:40:25] [config] comet-mix: false
[2026-10-15 14:40:25] [config] comet-mix-norm: false
[2026-10-15 14:40:25] [config] comet-mix-transformation: softmax
[2026-10-15 14:40:25] [config] comet-mixup: 0
[2026-10-15 14:40:25] [config] comet-mixup-reg: false
[2026-10-15 14:40:25] [config] comet-pool: avg
[2026-10-15 14:40:25] [config] comet-pooler-ffn:
[2026-10-15 14:40:25] [config]   - 2048
[2026-10-15 14:40:25] [config]   - 1024
[2026-10-15 14:40:25] [config] comet-prepend-zero: false
[2026-10-15 14:40:25] [config] comet-stop-grad: false
[2026-10-15 14:40:25] [config] comet-use-separator: false
[2026-10-15 14:40:25] [config] cost-scaling:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] cost-type: ce-sum
[2026-10-15 14:40:25] [config] cpu-threads: 0
[2026-10-15 14:40:25] [config] custom-fallbacks:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] data-threads: 8
[2026-10-15 14:40:25] [config] data-weighting: ""
[2026-10-15 14:40:25] [config] data-weighting-type: sentence
[2026-10-15 14:40:25] [config] dec-cell: gru
[2026-10-15 14:40:25] [config] dec-cell-base-depth: 2
[2026-10-15 14:40:25] [config] dec-cell-high-depth: 1
[2026-10-15 14:40:25] [config] dec-depth: 1
[2026-10-15 14:40:25] [config] devices:
[2026-10-15 14:40:25] [config]   - 0
[2026-10-15 14:40:25] [config] dim-emb: 512
[2026-10-15 14:40:25] [config] dim-rnn: 1024
[2026-10-15 14:40:25] [config] dim-vocabs:
[2026-10-15 14:40:25] [config]   - 0
[2026-10-15 14:40:25] [config]   - 0
[2026-10-15 14:40:25] [config] disp-first: 0
[2026-10-15 14:40:25] [config] disp-freq: 1000u
[2026-10-15 14:40:25] [config] disp-label-counts: true
[2026-10-15 14:40:25] [config] dropout-rnn: 0.2
[2026-10-15 14:40:25] [config] dropout-src: 0.2
[2026-10-15 14:40:25] [config] dropout-trg: 0.2
[2026-10-15 14:40:25] [config] dump-config: ""
[2026-10-15 14:40:25] [config] dynamic-gradient-scaling:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] early-stopping: 15
[2026-10-15 14:40:25] [config] early-stopping-epsilon:
[2026-10-15 14:40:25] [config]   - 0
[2026-10-15 14:40:25] [config] early-stopping-on: first
[2026-10-15 14:40:25] [config] embedding-fix-src: false
[2026-10-15 14:40:25] [config] embedding-fix-trg: false
[2026-10-15 14:40:25] [config] embedding-normalization: false
[2026-10-15 14:40:25] [config] embedding-vectors:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] enc-cell: gru
[2026-10-15 14:40:25] [config] enc-cell-depth: 1
[2026-10-15 14:40:25] [config] enc-depth: 1
[2026-10-15 14:40:25] [config] enc-type: bidirectional
[2026-10-15 14:40:25] [config] english-title-case-every: 0
[2026-10-15 14:40:25] [config] exponential-smoothing: 0
[2026-10-15 14:40:25] [config] exponential-smoothing-replace-freq: 0
[2026-10-15 14:40:25] [config] factor-weight: 1
[2026-10-15 14:40:25] [config] factors-combine: sum
[2026-10-15 14:40:25] [config] factors-dim-emb: 0
[2026-10-15 14:40:25] [config] gradient-checkpointing: false
[2026-10-15 14:40:25] [config] gradient-norm-average-window: 100
[2026-10-15 14:40:25] [config] guided-alignment: none
[2026-10-15 14:40:25] [config] guided-alignment-cost: ce
[2026-10-15 14:40:25] [config] guided-alignment-weight: 0.1
[2026-10-15 14:40:25] [config] ignore-model-config: false
[2026-10-15 14:40:25] [config] input-join-fields: false
[2026-10-15 14:40:25] [config] input-reorder:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] input-types:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] interpolate-env-vars: false
[2026-10-15 14:40:25] [config] keep-best: false
[2026-10-15 14:40:25] [config] label-smoothing: 0
[2026-10-15 14:40:25] [config] layer-normalization: false
[2026-10-15 14:40:25] [config] learn-rate: 0.0003
[2026-10-15 14:40:25] [config] lemma-dependency: ""
[2026-10-15 14:40:25] [config] lemma-dim-emb: 0
[2026-10-15 14:40:25] [config] log: ""
[2026-10-15 14:40:25] [config] log-level: info
[2026-10-15 14:40:25] [config] log-time-zone: ""
[2026-10-15 14:40:25] [config] logical-epoch:
[2026-10-15 14:40:25] [config]   - 1e
[2026-10-15 14:40:25] [config]   - 0
[2026-10-15 14:40:25] [config] lr-decay: 0
[2026-10-15 14:40:25] [config] lr-decay-freq: 50000
[2026-10-15 14:40:25] [config] lr-decay-inv-sqrt:
[2026-10-15 14:40:25] [config]   - 0
[2026-10-15 14:40:25] [config] lr-decay-repeat-warmup: false
[2026-10-15 14:40:25] [config] lr-decay-reset-optimizer: false
[2026-10-15 14:40:25] [config] lr-decay-start:
[2026-10-15 14:40:25] [config]   - 10
[2026-10-15 14:40:25] [config]   - 1
[2026-10-15 14:40:25] [config] lr-decay-strategy: epoch+stalled
[2026-10-15 14:40:25] [config] lr-report: false
[2026-10-15 14:40:25] [config] lr-warmup: 500
[2026-10-15 14:40:25] [config] lr-warmup-at-reload: false
[2026-10-15 14:40:25] [config] lr-warmup-cycle: false
[2026-10-15 14:40:25] [config] lr-warmup-start-rate: 0
[2026-10-15 14:40:25] [config] max-length: 50
[2026-10-15 14:40:25] [config] max-length-crop: false
[2026-10-15 14:40:25] [config] max-length-factor: 3
[2026-10-15 14:40:25] [config] maxi-batch: 100
[2026-10-15 14:40:25] [config] maxi-batch-sort: trg
[2026-10-15 14:40:25] [config] mini-batch: 64
[2026-10-15 14:40:25] [config] mini-batch-fit: false
[2026-10-15 14:40:25] [config] mini-batch-fit-step: 10
[2026-10-15 14:40:25] [config] mini-batch-round-up: true
[2026-10-15 14:40:25] [config] mini-batch-track-lr: false
[2026-10-15 14:40:25] [config] mini-batch-warmup: 0
[2026-10-15 14:40:25] [config] mini-batch-words: 2048
[2026-10-15 14:40:25] [config] mini-batch-words-ref: 0
[2026-10-15 14:40:25] [config] model: /kaggle/working/models/seq2seq/my-hi-rnn.npz
[2026-10-15 14:40:25] [config] multi-loss-type: sum
[2026-10-15 14:40:25] [config] n-best: false
[2026-10-15 14:40:25] [config] no-nccl: false
[2026-10-15 14:40:25] [config] no-optimizer-reload: false
[2026-10-15 14:40:25] [config] no-reload: false
[2026-10-15 14:40:25] [config] no-restore-corpus: false
[2026-10-15 14:40:25] [config] no-spm-encode: false
[2026-10-15 14:40:25] [config] normalize: 0
[2026-10-15 14:40:25] [config] normalize-gradient: false
[2026-10-15 14:40:25] [config] normalize-gradient-by-ratio: false
[2026-10-15 14:40:25] [config] optimizer: adam
[2026-10-15 14:40:25] [config] optimizer-delay: 1
[2026-10-15 14:40:25] [config] optimizer-params:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] output-omit-bias: false
[2026-10-15 14:40:25] [config] overwrite: false
[2026-10-15 14:40:25] [config] overwrite-checkpoint: true
[2026-10-15 14:40:25] [config] precision:
[2026-10-15 14:40:25] [config]   - float32
[2026-10-15 14:40:25] [config]   - float32
[2026-10-15 14:40:25] [config] pretrained-model: ""
[2026-10-15 14:40:25] [config] quantize-biases: false
[2026-10-15 14:40:25] [config] quantize-bits: 0
[2026-10-15 14:40:25] [config] quantize-log-based: false
[2026-10-15 14:40:25] [config] quantize-optimization-steps: 0
[2026-10-15 14:40:25] [config] quiet: false
[2026-10-15 14:40:25] [config] quiet-translation: false
[2026-10-15 14:40:25] [config] quiet-validation: false
[2026-10-15 14:40:25] [config] relative-paths: false
[2026-10-15 14:40:25] [config] right-left: false
[2026-10-15 14:40:25] [config] save-freq: 10000u
[2026-10-15 14:40:25] [config] seed: 0
[2026-10-15 14:40:25] [config] sentencepiece-alphas:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] sentencepiece-max-lines: 2000000
[2026-10-15 14:40:25] [config] sentencepiece-options: ""
[2026-10-15 14:40:25] [config] separator-symbol: "[eos]"
[2026-10-15 14:40:25] [config] sharding: global
[2026-10-15 14:40:25] [config] shuffle: data
[2026-10-15 14:40:25] [config] shuffle-in-ram: false
[2026-10-15 14:40:25] [config] sigterm: save-and-exit
[2026-10-15 14:40:25] [config] skip: false
[2026-10-15 14:40:25] [config] sqlite: ""
[2026-10-15 14:40:25] [config] sqlite-drop: false
[2026-10-15 14:40:25] [config] sync-freq: 200u
[2026-10-15 14:40:25] [config] sync-sgd: false
[2026-10-15 14:40:25] [config] tempdir: /tmp
[2026-10-15 14:40:25] [config] throw-on-divergence:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] tied-embeddings: false
[2026-10-15 14:40:25] [config] tied-embeddings-all: false
[2026-10-15 14:40:25] [config] tied-embeddings-src: false
[2026-10-15 14:40:25] [config] train-embedder-rank:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] train-sets:
[2026-10-15 14:40:25] [config]   - /kaggle/working/data/train.my.spm
[2026-10-15 14:40:25] [config]   - /kaggle/working/data/train.hi.spm
[2026-10-15 14:40:25] [config] transformer-aan-activation: swish
[2026-10-15 14:40:25] [config] transformer-aan-depth: 2
[2026-10-15 14:40:25] [config] transformer-aan-nogate: false
[2026-10-15 14:40:25] [config] transformer-alibi-shift: false
[2026-10-15 14:40:25] [config] transformer-alibi-trainable: false
[2026-10-15 14:40:25] [config] transformer-attention-mask: default
[2026-10-15 14:40:25] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 14:40:25] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 14:40:25] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 14:40:25] [config] transformer-depth-scaling: false
[2026-10-15 14:40:25] [config] transformer-dim-aan: 2048
[2026-10-15 14:40:25] [config] transformer-dim-ffn: 2048
[2026-10-15 14:40:25] [config] transformer-disable-position-embeddings: false
[2026-10-15 14:40:25] [config] transformer-dropout: 0
[2026-10-15 14:40:25] [config] transformer-dropout-attention: 0
[2026-10-15 14:40:25] [config] transformer-dropout-ffn: 0
[2026-10-15 14:40:25] [config] transformer-ffn-activation: swish
[2026-10-15 14:40:25] [config] transformer-ffn-depth: 2
[2026-10-15 14:40:25] [config] transformer-guided-alignment-layer: last
[2026-10-15 14:40:25] [config] transformer-heads: 8
[2026-10-15 14:40:25] [config] transformer-no-affine: false
[2026-10-15 14:40:25] [config] transformer-no-bias: false
[2026-10-15 14:40:25] [config] transformer-no-projection: false
[2026-10-15 14:40:25] [config] transformer-pool: false
[2026-10-15 14:40:25] [config] transformer-postprocess: dan
[2026-10-15 14:40:25] [config] transformer-postprocess-emb: d
[2026-10-15 14:40:25] [config] transformer-postprocess-top: ""
[2026-10-15 14:40:25] [config] transformer-preprocess: ""
[2026-10-15 14:40:25] [config] transformer-rnn-projection: false
[2026-10-15 14:40:25] [config] transformer-tied-layers:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] transformer-train-position-embeddings: false
[2026-10-15 14:40:25] [config] tsv: false
[2026-10-15 14:40:25] [config] tsv-fields: 0
[2026-10-15 14:40:25] [config] type: s2s
[2026-10-15 14:40:25] [config] ulr: false
[2026-10-15 14:40:25] [config] ulr-dim-emb: 0
[2026-10-15 14:40:25] [config] ulr-dropout: 0
[2026-10-15 14:40:25] [config] ulr-keys-vectors: ""
[2026-10-15 14:40:25] [config] ulr-query-vectors: ""
[2026-10-15 14:40:25] [config] ulr-softmax-temperature: 1
[2026-10-15 14:40:25] [config] ulr-trainable-transformation: false
[2026-10-15 14:40:25] [config] unlikelihood-loss: false
[2026-10-15 14:40:25] [config] valid-freq: 100
[2026-10-15 14:40:25] [config] valid-log: ""
[2026-10-15 14:40:25] [config] valid-max-length: 1000
[2026-10-15 14:40:25] [config] valid-metrics:
[2026-10-15 14:40:25] [config]   - cross-entropy
[2026-10-15 14:40:25] [config]   - bleu
[2026-10-15 14:40:25] [config] valid-mini-batch: 32
[2026-10-15 14:40:25] [config] valid-reset-all: false
[2026-10-15 14:40:25] [config] valid-reset-stalled: false
[2026-10-15 14:40:25] [config] valid-script-args:
[2026-10-15 14:40:25] [config]   []
[2026-10-15 14:40:25] [config] valid-script-path: ""
[2026-10-15 14:40:25] [config] valid-sets:
[2026-10-15 14:40:25] [config]   - /kaggle/working/data/valid.my.spm
[2026-10-15 14:40:25] [config]   - /kaggle/working/data/valid.hi.spm
[2026-10-15 14:40:25] [config] valid-translation-output: ""
[2026-10-15 14:40:25] [config] vocabs:
[2026-10-15 14:40:25] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 14:40:25] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 14:40:25] [config] word-penalty: 0
[2026-10-15 14:40:25] [config] word-scores: false
[2026-10-15 14:40:25] [config] workspace: 4096
[2026-10-15 14:40:25] [config] Model is being created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 14:40:25] [training] Using single-device training
[2026-10-15 14:40:25] [comm] Compiled without MPI support. Running as a single process on f2fe76130532
[2026-10-15 14:40:25] Synced seed 1792075225
[2026-10-15 14:40:25] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 14:40:25] [data] Setting vocabulary size for input 0 to 6,014
[2026-10-15 14:40:25] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 14:40:25] [data] Setting vocabulary size for input 1 to 2,988
[2026-10-15 14:40:25] [memory] Extending reserved space to 4096 MB (device gpu0)
[2026-10-15 14:40:25] [comm] Using NCCL 2.8.3 for GPU communication
[2026-10-15 14:40:25] [comm] Using global sharding
[2026-10-15 14:40:25] [comm] NCCLCommunicators constructed successfully
[2026-10-15 14:40:25] [training] Using 1 GPUs
[2026-10-15 14:40:25] Training started
[2026-10-15 14:40:25] [data] Shuffling data
[2026-10-15 14:40:25] [data] Done reading 8,500 sentences
[2026-10-15 14:40:25] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:25] [training] Batches are processed as 1 process(es) x 1 devices/process
[2026-10-15 14:40:25] [logits] Applying loss function for 1 factor(s)
[2026-10-15 14:40:25] [memory] Reserving 152 MB, device gpu0
[2026-10-15 14:40:25] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 14:40:25] [memory] Reserving 152 MB, device gpu0
[2026-10-15 14:40:26] Parameter type float32, optimization type float32, casting types false
[2026-10-15 14:40:26] Allocating memory for Adam-specific shards
[2026-10-15 14:40:26] [memory] Reserving 305 MB, device gpu0
[2026-10-15 14:40:27] Seen 8,500 samples
[2026-10-15 14:40:27] Starting data epoch 2 in logical epoch 2
[2026-10-15 14:40:27] [data] Shuffling data
[2026-10-15 14:40:27] [data] Done reading 8,500 sentences
[2026-10-15 14:40:27] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:28] Seen 8,500 samples
[2026-10-15 14:40:28] Starting data epoch 3 in logical epoch 3
[2026-10-15 14:40:28] [data] Shuffling data
[2026-10-15 14:40:28] [data] Done reading 8,500 sentences
[2026-10-15 14:40:28] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:30] Seen 8,500 samples
[2026-10-15 14:40:30] Starting data epoch 4 in logical epoch 4
[2026-10-15 14:40:30] [data] Shuffling data
[2026-10-15 14:40:30] [data] Done reading 8,500 sentences
[2026-10-15 14:40:30] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:31] Seen 8,500 samples
[2026-10-15 14:40:31] Starting data epoch 5 in logical epoch 5
[2026-10-15 14:40:31] [data] Shuffling data
[2026-10-15 14:40:31] [data] Done reading 8,500 sentences
[2026-10-15 14:40:31] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:33] Seen 8,500 samples
[2026-10-15 14:40:33] Starting data epoch 6 in logical epoch 6
[2026-10-15 14:40:33] [data] Shuffling data
[2026-10-15 14:40:33] [data] Done reading 8,500 sentences
[2026-10-15 14:40:33] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:34] Seen 8,500 samples
[2026-10-15 14:40:34] Starting data epoch 7 in logical epoch 7
[2026-10-15 14:40:34] [data] Shuffling data
[2026-10-15 14:40:34] [data] Done reading 8,500 sentences
[2026-10-15 14:40:34] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:35] [valid] Ep. 7 : Up. 100 : cross-entropy : 26.0549 : new best
[2026-10-15 14:40:35] Translating validation set...
[2026-10-15 14:40:35] [valid] References contain unknown word, metric scores may be inaccurate
[2026-10-15 14:40:35] [valid] First sentence's tokens as scored:
[2026-10-15 14:40:35] [valid] DefaultVocab keeps original segments for scoring
[2026-10-15 14:40:35] [valid]   Hyp:
[2026-10-15 14:40:35] [valid]   Ref: ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓏭𓄿𓈎 <unk> <unk> 𓆑𓏭
[2026-10-15 14:40:35] Best translation 0 :
[2026-10-15 14:40:35] Best translation 1 :
[2026-10-15 14:40:35] Best translation 2 :
[2026-10-15 14:40:35] Best translation 3 :
[2026-10-15 14:40:35] Best translation 4 :
[2026-10-15 14:40:35] Best translation 5 :
[2026-10-15 14:40:35] Best translation 10 :
[2026-10-15 14:40:35] Best translation 20 :
[2026-10-15 14:40:35] Best translation 40 :
[2026-10-15 14:40:35] Best translation 80 :
[2026-10-15 14:40:35] Best translation 160 :
[2026-10-15 14:40:36] Best translation 320 :
[2026-10-15 14:40:36] Best translation 640 :
[2026-10-15 14:40:36] Total translation time: 0.26298s
[2026-10-15 14:40:36] [valid] Ep. 7 : Up. 100 : bleu : 0 : new best
[2026-10-15 14:40:37] Seen 8,500 samples
[2026-10-15 14:40:37] Starting data epoch 8 in logical epoch 8
[2026-10-15 14:40:37] [data] Shuffling data
[2026-10-15 14:40:37] [data] Done reading 8,500 sentences
[2026-10-15 14:40:37] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:38] Seen 8,500 samples
[2026-10-15 14:40:38] Starting data epoch 9 in logical epoch 9
[2026-10-15 14:40:38] [data] Shuffling data
[2026-10-15 14:40:38] [data] Done reading 8,500 sentences
[2026-10-15 14:40:38] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:40] Seen 8,500 samples
[2026-10-15 14:40:40] Starting data epoch 10 in logical epoch 10
[2026-10-15 14:40:40] [data] Shuffling data
[2026-10-15 14:40:40] [data] Done reading 8,500 sentences
[2026-10-15 14:40:40] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:41] Seen 8,500 samples
[2026-10-15 14:40:41] Starting data epoch 11 in logical epoch 11
[2026-10-15 14:40:41] [data] Shuffling data
[2026-10-15 14:40:41] [data] Done reading 8,500 sentences
[2026-10-15 14:40:41] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:43] Seen 8,500 samples
[2026-10-15 14:40:43] Starting data epoch 12 in logical epoch 12
[2026-10-15 14:40:43] [data] Shuffling data
[2026-10-15 14:40:43] [data] Done reading 8,500 sentences
[2026-10-15 14:40:43] [data] Done shuffling 8,500 sentences to temp files
[2026-10-15 14:40:44] Seen 8,500 samples
[2026-10-15 14:40:44] Starting data epoch 13 in logical epoch 13
[2026-10-15 14:40:44] [data] Shuffling data
[2026-10-15 14:40:44] [data] Done reading 8,500 sentences
[2026-10-15 14:40:44] [data] Done shuffling 8,500 sentences to temp files

In [14]:
MARIAN_DECODER="/kaggle/working/marian-dev/build/marian-decoder"

!{MARIAN_DECODER} \
  --models /kaggle/working/models/seq2seq/hi-my-rnn.npz \
  --vocabs /kaggle/working/data/hi.vocab.yml /kaggle/working/data/my.vocab.yml \
  --beam-size 12 \
  --normalize 1.0 \
  < /kaggle/working/data/test.hi.spm \
  > /kaggle/working/output/seq2seq/test.output.my.spm

!{MARIAN_DECODER} \
  --models /kaggle/working/models/seq2seq/my-hi-rnn.npz \
  --vocabs /kaggle/working/data/my.vocab.yml /kaggle/working/data/hi.vocab.yml \
  --beam-size 12 \
  --normalize 1.0 \
  < /kaggle/working/data/test.my.spm \
  > /kaggle/working/output/seq2seq/test.output.hi.spm

[2026-10-15 15:06:23] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:06:23] [marian] Running on f2fe76130532 as process 18495 with command line:
[2026-10-15 15:06:23] [marian] /kaggle/working/marian-dev/build/marian-decoder --models /kaggle/working/models/seq2seq/hi-my-rnn.npz --vocabs /kaggle/working/data/hi.vocab.yml /kaggle/working/data/my.vocab.yml --beam-size 12 --normalize 1.0
[2026-10-15 15:06:24] [config] alignment: ""
[2026-10-15 15:06:24] [config] allow-special: false
[2026-10-15 15:06:24] [config] allow-unk: false
[2026-10-15 15:06:24] [config] authors: false
[2026-10-15 15:06:24] [config] beam-size: 12
[2026-10-15 15:06:24] [config] bert-class-symbol: "[CLS]"
[2026-10-15 15:06:24] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 15:06:24] [config] bert-masking-fraction: 0.15
[2026-10-15 15:06:24] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 15:06:24] [config] bert-train-type-embeddings: true
[2026-10-15 15:06:24] [config] bert-type-vocab-size: 2
[2026-10-15 15:06:24] [config] best-deep: false
[2026-10-15 15:06:24] [config] build-info: ""
[2026-10-15 15:06:24] [config] check-nan: false
[2026-10-15 15:06:24] [config] cite: false
[2026-10-15 15:06:24] [config] comet-augment-bad: 0
[2026-10-15 15:06:24] [config] comet-dropout: 0.1
[2026-10-15 15:06:24] [config] comet-final-sigmoid: false
[2026-10-15 15:06:24] [config] comet-mix: false
[2026-10-15 15:06:24] [config] comet-mix-norm: false
[2026-10-15 15:06:24] [config] comet-mix-transformation: softmax
[2026-10-15 15:06:24] [config] comet-mixup: 0
[2026-10-15 15:06:24] [config] comet-mixup-reg: false
[2026-10-15 15:06:24] [config] comet-pool: avg
[2026-10-15 15:06:24] [config] comet-pooler-ffn:
[2026-10-15 15:06:24] [config]   - 2048
[2026-10-15 15:06:24] [config]   - 1024
[2026-10-15 15:06:24] [config] comet-prepend-zero: false
[2026-10-15 15:06:24] [config] comet-stop-grad: false
[2026-10-15 15:06:24] [config] comet-use-separator: false
[2026-10-15 15:06:24] [config] cpu-threads: 0
[2026-10-15 15:06:24] [config] data-threads: 8
[2026-10-15 15:06:24] [config] dec-cell: gru
[2026-10-15 15:06:24] [config] dec-cell-base-depth: 2
[2026-10-15 15:06:24] [config] dec-cell-high-depth: 1
[2026-10-15 15:06:24] [config] dec-depth: 1
[2026-10-15 15:06:24] [config] devices:
[2026-10-15 15:06:24] [config]   - 0
[2026-10-15 15:06:24] [config] dim-emb: 512
[2026-10-15 15:06:24] [config] dim-rnn: 1024
[2026-10-15 15:06:24] [config] dim-vocabs:
[2026-10-15 15:06:24] [config]   - 2988
[2026-10-15 15:06:24] [config]   - 6014
[2026-10-15 15:06:24] [config] dump-config: ""
[2026-10-15 15:06:24] [config] enc-cell: gru
[2026-10-15 15:06:24] [config] enc-cell-depth: 1
[2026-10-15 15:06:24] [config] enc-depth: 1
[2026-10-15 15:06:24] [config] enc-type: bidirectional
[2026-10-15 15:06:24] [config] factors-combine: sum
[2026-10-15 15:06:24] [config] factors-dim-emb: 0
[2026-10-15 15:06:24] [config] force-decode: false
[2026-10-15 15:06:24] [config] gemm-type: float32
[2026-10-15 15:06:24] [config] ignore-model-config: false
[2026-10-15 15:06:24] [config] input:
[2026-10-15 15:06:24] [config]   - stdin
[2026-10-15 15:06:24] [config] input-join-fields: false
[2026-10-15 15:06:24] [config] input-reorder:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] input-types:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] interpolate-env-vars: false
[2026-10-15 15:06:24] [config] layer-normalization: false
[2026-10-15 15:06:24] [config] lemma-dependency: ""
[2026-10-15 15:06:24] [config] lemma-dim-emb: 0
[2026-10-15 15:06:24] [config] log: ""
[2026-10-15 15:06:24] [config] log-level: info
[2026-10-15 15:06:24] [config] log-time-zone: ""
[2026-10-15 15:06:24] [config] max-length: 1000
[2026-10-15 15:06:24] [config] max-length-crop: false
[2026-10-15 15:06:24] [config] max-length-factor: 3
[2026-10-15 15:06:24] [config] maxi-batch: 1
[2026-10-15 15:06:24] [config] maxi-batch-sort: none
[2026-10-15 15:06:24] [config] mini-batch: 1
[2026-10-15 15:06:24] [config] mini-batch-words: 0
[2026-10-15 15:06:24] [config] model-mmap: false
[2026-10-15 15:06:24] [config] models:
[2026-10-15 15:06:24] [config]   - /kaggle/working/models/seq2seq/hi-my-rnn.npz
[2026-10-15 15:06:24] [config] n-best: false
[2026-10-15 15:06:24] [config] no-spm-decode: false
[2026-10-15 15:06:24] [config] no-spm-encode: false
[2026-10-15 15:06:24] [config] normalize: 1
[2026-10-15 15:06:24] [config] optimize: false
[2026-10-15 15:06:24] [config] output: stdout
[2026-10-15 15:06:24] [config] output-approx-knn:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] output-omit-bias: false
[2026-10-15 15:06:24] [config] output-sampling:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] precision:
[2026-10-15 15:06:24] [config]   - float32
[2026-10-15 15:06:24] [config] quantize-range: 0
[2026-10-15 15:06:24] [config] quiet: false
[2026-10-15 15:06:24] [config] quiet-translation: false
[2026-10-15 15:06:24] [config] relative-paths: false
[2026-10-15 15:06:24] [config] right-left: false
[2026-10-15 15:06:24] [config] seed: 0
[2026-10-15 15:06:24] [config] separator-symbol: "[eos]"
[2026-10-15 15:06:24] [config] shortlist:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] skip: false
[2026-10-15 15:06:24] [config] skip-cost: false
[2026-10-15 15:06:24] [config] stat-freq: 0
[2026-10-15 15:06:24] [config] tied-embeddings: false
[2026-10-15 15:06:24] [config] tied-embeddings-all: false
[2026-10-15 15:06:24] [config] tied-embeddings-src: false
[2026-10-15 15:06:24] [config] transformer-aan-activation: swish
[2026-10-15 15:06:24] [config] transformer-aan-depth: 2
[2026-10-15 15:06:24] [config] transformer-aan-nogate: false
[2026-10-15 15:06:24] [config] transformer-alibi-shift: false
[2026-10-15 15:06:24] [config] transformer-alibi-trainable: false
[2026-10-15 15:06:24] [config] transformer-attention-mask: default
[2026-10-15 15:06:24] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 15:06:24] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 15:06:24] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 15:06:24] [config] transformer-depth-scaling: false
[2026-10-15 15:06:24] [config] transformer-dim-aan: 2048
[2026-10-15 15:06:24] [config] transformer-dim-ffn: 2048
[2026-10-15 15:06:24] [config] transformer-disable-position-embeddings: false
[2026-10-15 15:06:24] [config] transformer-ffn-activation: swish
[2026-10-15 15:06:24] [config] transformer-ffn-depth: 2
[2026-10-15 15:06:24] [config] transformer-guided-alignment-layer: last
[2026-10-15 15:06:24] [config] transformer-heads: 8
[2026-10-15 15:06:24] [config] transformer-no-affine: false
[2026-10-15 15:06:24] [config] transformer-no-bias: false
[2026-10-15 15:06:24] [config] transformer-no-projection: false
[2026-10-15 15:06:24] [config] transformer-pool: false
[2026-10-15 15:06:24] [config] transformer-postprocess: dan
[2026-10-15 15:06:24] [config] transformer-postprocess-emb: d
[2026-10-15 15:06:24] [config] transformer-postprocess-top: ""
[2026-10-15 15:06:24] [config] transformer-preprocess: ""
[2026-10-15 15:06:24] [config] transformer-rnn-projection: false
[2026-10-15 15:06:24] [config] transformer-tied-layers:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] transformer-train-position-embeddings: false
[2026-10-15 15:06:24] [config] tsv: false
[2026-10-15 15:06:24] [config] tsv-fields: 0
[2026-10-15 15:06:24] [config] type: s2s
[2026-10-15 15:06:24] [config] ulr: false
[2026-10-15 15:06:24] [config] ulr-dim-emb: 0
[2026-10-15 15:06:24] [config] ulr-trainable-transformation: false
[2026-10-15 15:06:24] [config] version: v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:06:24] [config] vocabs:
[2026-10-15 15:06:24] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:06:24] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 15:06:24] [config] weights:
[2026-10-15 15:06:24] [config]   []
[2026-10-15 15:06:24] [config] word-penalty: 0
[2026-10-15 15:06:24] [config] word-scores: false
[2026-10-15 15:06:24] [config] workspace: 512
[2026-10-15 15:06:24] [config] Loaded model has been created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 15:06:24] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 15:06:24] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 15:06:24] Loading model from /kaggle/working/models/seq2seq/hi-my-rnn.npz
[2026-10-15 15:06:24] [memory] Extending reserved space to 512 MB (device gpu0)
[2026-10-15 15:06:24] Loaded model config
[2026-10-15 15:06:24] Loading scorer of type s2s as feature F0
[2026-10-15 15:06:24] [memory] Reserving 158 MB, device gpu0
[2026-10-15 15:06:24] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 15:06:24] Best translation 0 : ▁ကျွန်မ ▁ပြောနေတာ
[2026-10-15 15:06:24] Best translation 1 : ▁ကျွန်မမှာ ▁အစားအစာ ရှိတယ်
[2026-10-15 15:06:24] Best translation 2 : ▁ဘယ်သူမှ ▁ကျွန်မကို ▁မမြင်ခဲ့ဘူး။
[2026-10-15 15:06:24] Best translation 3 : ▁အေး မနေဘူးလား။
[2026-10-15 15:06:24] Best translation 4 : ▁ကျွန်တော်တို့ မှာ ▁ဘာရှိလဲ။
[2026-10-15 15:06:24] Best translation 5 : ▁ခရီး ကောင်းပါ
[2026-10-15 15:06:24] Best translation 6 : ▁ဘယ်လို ▁အဆုံးသတ် ခဲ့လဲ။
[2026-10-15 15:06:24] Best translation 7 : ▁အစားအစာက ▁အေးနေပြီ။
[2026-10-15 15:06:25] Best translation 8 : ▁သူဟာ ▁မလုံခြုံဘူး။
[2026-10-15 15:06:25] Best translation 9 : ▁ဒါအားလုံးက ▁ဘာလဲ။
[2026-10-15 15:06:25] Best translation 10 : ▁မင်းက ▁မကောင်းဘူး
[2026-10-15 15:06:25] Best translation 11 : ▁ရှင်းပြပါရစေ။
[2026-10-15 15:06:25] Best translation 12 : ▁ " ဟင် "
[2026-10-15 15:06:25] Best translation 13 : ▁ပိုများ မယ်လို့ ▁မျှော်လင့် ခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 14 : ▁တွေ့ရတာ ▁ဝမ်းသာပါတယ်။
[2026-10-15 15:06:25] Best translation 15 : ▁အံ့သြစရာတွေကို ▁ကြိုက်တယ်။
[2026-10-15 15:06:25] Best translation 16 : ▁သူမ ▁နောက်ကျနေပြီ။
[2026-10-15 15:06:25] Best translation 17 : ▁ကျွန်မလုပ်တာကို ▁ကြိုက်တယ်။
[2026-10-15 15:06:25] Best translation 18 : ▁ရယ်မောသံ ▁ကြားရတယ်။
[2026-10-15 15:06:25] Best translation 19 : ▁အလင်း တစ်ခု ▁မြင်တယ်။
[2026-10-15 15:06:25] Best translation 20 : ▁ဒါက ▁ခွေးတစ်ကောင် ပါ။
[2026-10-15 15:06:25] Best translation 21 : ▁နွားနို့ သောက်ခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 22 : ▁သူ့မှာ ▁ခွေးတစ်ကောင် ရှိတယ်။
[2026-10-15 15:06:25] Best translation 23 : ▁ကျွန်မတို့ဟာ ▁မိသားစု ပါ။
[2026-10-15 15:06:25] Best translation 24 : ▁သူမက ▁သူ့ကို ▁ချစ်တယ်။
[2026-10-15 15:06:25] Best translation 25 : ▁သူနာကျင် နေတယ်။
[2026-10-15 15:06:25] Best translation 26 : ▁ဝမ်းနည်း နေခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 27 : ▁ကျွန်တော် ပေးပါရစေ။
[2026-10-15 15:06:25] Best translation 28 : ▁သိပ် ကောင်းပါတယ်။
[2026-10-15 15:06:25] Best translation 29 : ▁Tom ▁ကို ▁မုန်းတယ်။
[2026-10-15 15:06:25] Best translation 30 : ▁ပြောတာကို ▁လုပ်ပါ။
[2026-10-15 15:06:25] Best translation 31 : ▁ဒါက ▁အချစ်လား။
[2026-10-15 15:06:25] Best translation 32 : ▁ကျွန်မတို့ဟာ ▁မိတ်ဆွေ တွေပါ။
[2026-10-15 15:06:25] Best translation 33 : ▁မင်းက ▁အရမ်းမြင့် တယ်
[2026-10-15 15:06:25] Best translation 34 : ▁ဒါကို ▁မသုံး နိုင်ဘူး။
[2026-10-15 15:06:25] Best translation 35 : ▁သူက ▁မြန်မြန် ဆန်ဆန် ▁လုပ်ဆောင် တယ်။
[2026-10-15 15:06:25] Best translation 36 : ▁အမှောင် ဆဲပါ။
[2026-10-15 15:06:25] Best translation 37 : ▁ချိန်းဆို သူကို ▁ခေါ်လာပါ။
[2026-10-15 15:06:25] Best translation 38 : ▁သူလုပ်တာ ▁သိတယ်။
[2026-10-15 15:06:25] Best translation 39 : ▁သူတို့ဟာ ▁ကျောင်းသား တွေပါ။
[2026-10-15 15:06:25] Best translation 40 : ▁ဆူညံသံတွေ ▁အများကြီးပါ။
[2026-10-15 15:06:25] Best translation 41 : ▁မင်းက ▁အေးဆေးတယ်
[2026-10-15 15:06:25] Best translation 42 : ▁စိတ်ဝင်စား စရာပါ။
[2026-10-15 15:06:25] Best translation 43 : ▁ဒါက ▁မိုက်လိုက်တာ
[2026-10-15 15:06:25] Best translation 44 : ▁ကျွန်မက ▁ရိုးစင်းခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 45 : ▁ထလိုက်ပါ
[2026-10-15 15:06:25] Best translation 46 : ▁သူက ▁ကျွန်မအ ရွယ် ပဲရှိပါသေးတယ်။
[2026-10-15 15:06:25] Best translation 47 : ▁သူမဟာ ▁အရမ်း ချစ်တယ်။
[2026-10-15 15:06:25] Best translation 48 : ▁သူကျွန်မ ကို ▁လွှတ် ပေးခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 49 : ▁သူက ▁တင်းနစ်ကစား တယ်။
[2026-10-15 15:06:25] Best translation 50 : ▁သူဟာ ▁ချွေးထွက် လာခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 51 : ▁ကျွန်မ ▁အဆင်သင့်ဖြစ် နေပြီလို့ ▁ခံစားမိတယ်။
[2026-10-15 15:06:25] Best translation 52 : ▁ကျွန်တော် ▁သူနဲ့ ▁သဘောတူပါတယ်။
[2026-10-15 15:06:25] Best translation 53 : ▁အားလုံးက ▁နားတွေပဲ
[2026-10-15 15:06:25] Best translation 54 : ▁ကျွန်တော်က ▁တိုကျို ကပါ။
[2026-10-15 15:06:25] Best translation 55 : ▁အိမ်မှာလား။
[2026-10-15 15:06:25] Best translation 56 : ▁ကျွန်မပြော သလို ▁လုပ်ပါ။
[2026-10-15 15:06:25] Best translation 57 : ▁အားလုံး ▁အဆင်ပြေပါတယ်။
[2026-10-15 15:06:25] Best translation 58 : ▁ဆေးလိပ်သောက်တာ ▁ရပ်လိုက်ပါ
[2026-10-15 15:06:25] Best translation 59 : ▁Tom ▁က ▁ရက်စက်တယ်။
[2026-10-15 15:06:25] Best translation 60 : ▁ပဟေ ဠ ိတွေကို ▁ကြိုက်တယ်။
[2026-10-15 15:06:25] Best translation 61 : ▁သူ ▁ဖတ် လို့မရဘူး။
[2026-10-15 15:06:25] Best translation 62 : ▁ဘာပြောလဲ။
[2026-10-15 15:06:25] Best translation 63 : ▁လက်ဖက်ရည် သောက်ပါ။
[2026-10-15 15:06:25] Best translation 64 : ▁ကျွန်မတို့က ▁ဆရာမတွေပါ။
[2026-10-15 15:06:25] Best translation 65 : ▁ကော် လိုတယ်။
[2026-10-15 15:06:25] Best translation 66 : ▁နေ့လည်စာ ▁အသင့်ရှိ ပြီလား။
[2026-10-15 15:06:25] Best translation 67 : ▁ကျွန်မတို့ဟာ ▁မိသားစု ပါ။
[2026-10-15 15:06:25] Best translation 68 : ▁မင်းက ▁မော်ဒယ် လား
[2026-10-15 15:06:25] Best translation 69 : ▁တံခါးဖွင့် ထားလား။
[2026-10-15 15:06:25] Best translation 70 : ▁သူတို့အားလုံး ▁သိ ခဲ့ကြတယ်။
[2026-10-15 15:06:25] Best translation 71 : ▁နေ့ကောင်း တစ်ခုရှိပါစေ။
[2026-10-15 15:06:25] Best translation 72 : ▁ဘယ်သူမှ ▁မကျန်းမာ ခဲ့ဘူး။
[2026-10-15 15:06:25] Best translation 73 : ▁ကျွန်မက ▁အကြီးအကဲ မဟုတ်ဘူး။
[2026-10-15 15:06:25] Best translation 74 : ▁ကျွန်တော်နားလည် လာပြီ
[2026-10-15 15:06:25] Best translation 75 : ▁ကျွန်တော်ကတော့ ▁ဆန့်ကျင်ပါတယ်။
[2026-10-15 15:06:25] Best translation 76 : ▁ပါးစပ်က ▁တုံပြန် နေပြီ။
[2026-10-15 15:06:25] Best translation 77 : ▁ကျွန်တော်တို့ ▁အဆင်သင့်ဖြစ် ပြီလား။
[2026-10-15 15:06:25] Best translation 78 : ▁Tom ▁ဟာ ▁မြန်မြန်ပြေး နိုင်တယ်
[2026-10-15 15:06:25] Best translation 79 : ▁ကျွန်မက ▁လိမ်ညာသူ ▁မဟုတ်ဘူး။
[2026-10-15 15:06:25] Best translation 80 : ▁သူအောင် မြင်ခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 81 : ▁ဘယ်အချိန် ▁စားကြလဲ။
[2026-10-15 15:06:25] Best translation 82 : ▁ကျွန်မ ▁အများကြီး ▁စားတယ်။
[2026-10-15 15:06:25] Best translation 83 : ▁Toms ▁ဟာ ▁ဒေါသထွက်တယ်။
[2026-10-15 15:06:25] Best translation 84 : ▁ခင်ဗျားတို့ ▁သဘောတူ မယ်လို့ ▁မျှော်လင့် ပါတယ်။
[2026-10-15 15:06:25] Best translation 85 : ▁သူဟာ ▁မြန်မြန် ကူးနိုင်တယ်
[2026-10-15 15:06:25] Best translation 86 : ▁ကြိုးကို ▁ဖြတ်လိုက်တယ်။
[2026-10-15 15:06:25] Best translation 87 : ▁ဒါကို ▁လုပ်နိုင်လား။
[2026-10-15 15:06:25] Best translation 88 : ▁ချက်ချင်းလာပါ
[2026-10-15 15:06:25] Best translation 89 : ▁သူဟာ ▁ဆိုးယုတ် တဲ့လူပါ။
[2026-10-15 15:06:25] Best translation 90 : ▁ရှင်း ရှင်းလင်းလင်း ▁ပြော ထားလား။
[2026-10-15 15:06:25] Best translation 91 : ▁မျက်နှာကို ▁ခြောက်သွေ့ သွားခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 92 : ▁ဒါက ▁ကျွန်မကို ▁စိတ်ဝင်စား စေတယ်။
[2026-10-15 15:06:25] Best translation 93 : ▁ကျွန်မ ▁မပြီးသေးဘူး။
[2026-10-15 15:06:25] Best translation 94 : ▁ကျွန်တော် ▁စောင့်ကြည့်မယ်။
[2026-10-15 15:06:25] Best translation 95 : ▁ကျွန်မတို့က ▁အကောင်းဆုံးပါ။
[2026-10-15 15:06:25] Best translation 96 : ▁အချိန်ကုန် သွားပြီ။
[2026-10-15 15:06:25] Best translation 97 : ▁သူတို့အားလုံး ▁လက်တွဲ ကြတယ်
[2026-10-15 15:06:25] Best translation 98 : ▁ကျွန်မက ▁အစာချေနေတာပါ။
[2026-10-15 15:06:25] Best translation 99 : ▁ဒါက ▁ပျော်စရာ မဟုတ်ဘူး။
[2026-10-15 15:06:25] Best translation 100 : ▁မင်းကို ▁ယုံကြည်တယ်။
[2026-10-15 15:06:25] Best translation 101 : ▁Tom ▁မှာ ▁နှုတ်ခမ်း ▁မုန်းတယ်။
[2026-10-15 15:06:25] Best translation 102 : ▁ B os t o n ▁မှာလား။
[2026-10-15 15:06:25] Best translation 103 : ▁သူတို့က ▁ကျွန်တော်တို့ ကို ▁ရှာတွေ့ လိမ့်မယ်။
[2026-10-15 15:06:25] Best translation 104 : ▁ပါးစပ်က ▁တုံပြန် နေပြီ။
[2026-10-15 15:06:25] Best translation 105 : ▁လာ လို့ရတယ်
[2026-10-15 15:06:25] Best translation 106 : ▁အချိန်မ ကြာပါနဲ့။
[2026-10-15 15:06:25] Best translation 107 : ▁ဒါက ▁ဟိုက် ဘရစ်ပါ။
[2026-10-15 15:06:25] Best translation 108 : ▁ကူညီချင်တယ်။
[2026-10-15 15:06:25] Best translation 109 : ▁သူက ▁အမဲလိုက်တာကို ▁ကြိုက်တယ်။
[2026-10-15 15:06:25] Best translation 110 : ▁ဒါကို ▁ရှင်းပစ် လိုက်တယ်
[2026-10-15 15:06:25] Best translation 111 : ▁ခွေးက ▁ကျွန်တော့ရဲ့
[2026-10-15 15:06:25] Best translation 112 : ▁ဘတ်စ်ကား တိုင်း ▁ပြည့် နေတယ်။
[2026-10-15 15:06:25] Best translation 113 : ▁ဘယ်အချိန် လောက်မှာလဲ။
[2026-10-15 15:06:25] Best translation 114 : ▁ ၆ ▁နာရီအထိ ▁စောင့်ပါ။
[2026-10-15 15:06:25] Best translation 115 : ▁ဒါကို ▁ကျော်လ ွှားခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 116 : ▁နေ့လည်စာ မှာ ▁တွေ့ကြမယ်။
[2026-10-15 15:06:25] Best translation 117 : ▁မင်း ▁အဆင်ပြေသွားမှာ
[2026-10-15 15:06:25] Best translation 118 : ▁ပြတင်းပေါက် ကို ▁ပိတ်လိုက်ပါ
[2026-10-15 15:06:25] Best translation 119 : ▁ပျော်ခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 120 : ▁ကျွန်မ ▁အအေးမိတယ်။
[2026-10-15 15:06:25] Best translation 121 : ▁နောက်ကျ တာအတွက် ▁စိတ်မကောင်း ပါဘူး။
[2026-10-15 15:06:25] Best translation 122 : ▁Tom ▁က ▁ဒါကို ▁လိုချင်ခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 123 : ▁သူက ▁ဒီမှာရှိတယ်
[2026-10-15 15:06:25] Best translation 124 : ▁ရှင်တို့ ▁တစ်ယောက်တည်း လား။
[2026-10-15 15:06:25] Best translation 125 : ▁ကျွန်မမှာ ▁သံသယ တွေရှိတယ်
[2026-10-15 15:06:25] Best translation 126 : ▁ကျွန်တော် ▁အနိုင်ရခဲ့တယ်။
[2026-10-15 15:06:25] Best translation 127 : ▁ပျော်နေပြီ ▁မဟုတ်လား။
[2026-10-15 15:06:25] Best translation 128 : ▁ကျွန်မ ▁အများကြီး ပြောတယ်။
[2026-10-15 15:06:25] Best translation 129 : ▁ကျွန်မက ▁အသားကျဉ်း တယ်။
[2026-10-15 15:06:25] Best translation 130 : ▁အိမ် ရောက်ပြီ ▁Tom
[2026-10-15 15:06:25] Best translation 131 : ▁ကျွန်မအတွက် ▁တက္ကစီ လိုတယ်။
[2026-10-15 15:06:25] Best translation 132 : ▁Tom ▁ဟာ ▁စိတ်ပျက်နေတယ်။
[2026-10-15 15:06:25] Best translation 133 : ▁ခွေး မဟုတ်ဘူး။
[2026-10-15 15:06:25] Best translation 134 : ▁အိပ်ရာ ကထွက်လိုက်ပါ
[2026-10-15 15:06:25] Best translation 135 : ▁မင်းနဲ့အတူ ▁မတက်နိုင်ဘူး။
[2026-10-15 15:06:25] Best translation 136 : ▁ကျွန်မ ▁အလုပ်မှ ▁ထုတ်ပယ် ခံရတယ်။
[2026-10-15 15:06:25] Best translation 137 : ▁ကလေးတွေ ▁ဘယ်လိုများလဲ။
[2026-10-15 15:06:25] Best translation 138 : ▁ကံကောင်း ပါစေလို့ ▁ဆုတောင်းပါတယ်။
[2026-10-15 15:06:25] Best translation 139 : ▁ငါ့ရှေ့က ▁လျှောက် လိုက်
[2026-10-15 15:06:25] Best translation 140 : ▁နိုးနေပါ။
[2026-10-15 15:06:25] Best translation 141 : ▁ဒါကို ▁လုပ်နိုင်လား။
[2026-10-15 15:06:25] Best translation 142 : ▁သင်ဟာ ▁အနားယူ ဖို့လိုပါတယ်။
[2026-10-15 15:06:25] Best translation 143 : ▁သူမသွားဘူး။
[2026-10-15 15:06:25] Best translation 144 : ▁ဘယ်သူမှ ▁မပြောနိုင်ဘူး။
[2026-10-15 15:06:25] Best translation 145 : ▁ငါဘယ်မှာလဲ
[2026-10-15 15:06:25] Best translation 146 : ▁Toms ▁ဘေးကင်းပါတယ်။
[2026-10-15 15:06:25] Best translation 147 : ▁ကျွန်မအ ဖြေက ▁မဟုတ်ဘူး။
[2026-10-15 15:06:25] Best translation 148 : ▁ဘာမှ မပြောခဲ့ဘူး။
[2026-10-15 15:06:25] Best translation 149 : ▁နေ့တိုင်း ▁လမ်းလျှောက်တယ်။
[2026-10-15 15:06:25] Best translation 150 : ▁ရေကူးရတာ ▁ကြိုက်တယ်။
[2026-10-15 15:06:25] Best translation 151 : ▁သူက ▁ဒီမှာ နေလား။
[2026-10-15 15:06:25] Best translation 152 : ▁မြင်နိုင်လား။
[2026-10-15 15:06:25] Best translation 153 : ▁ကျွန်မက ▁တော်တော် ရှက်တတ်တယ်။
[2026-10-15 15:06:25] Best translation 154 : ▁စောင့် သင့်လား။
[2026-10-15 15:06:25] Best translation 155 : ▁ဒါပေမဲ့ ▁ကျွန်တော် ▁သတိထားမိတယ်။
[2026-10-15 15:06:25] Best translation 156 : ▁ဒါက ▁ငွေတစ်လုံး တည်းပါ။
[2026-10-15 15:06:25] Best translation 157 : ▁ကျွန်တော် ▁ဒေါသထွက်တယ်။
[2026-10-15 15:06:25] Best translation 158 : ▁ကျွန်မ ▁အလုပ်များတယ်။
[2026-10-15 15:06:26] Best translation 159 : ▁Tom ▁က ▁ဒါကို ▁မုန်းတယ်။
[2026-10-15 15:06:26] Best translation 160 : ▁ဒါဟာ ▁အဓိပ္ပါယ် မရှိပါဘူး။
[2026-10-15 15:06:26] Best translation 161 : ▁ကျွန်မတို့ကို ▁သနားပါ။

In [15]:
import sentencepiece as spm

my_spm = spm.SentencePieceProcessor(model_file="my_spm.model")
hi_spm = spm.SentencePieceProcessor(model_file="hi_spm.model")

with open(
    "/kaggle/working/output/seq2seq/test.output.my.spm", "r", encoding="utf-8"
) as f_in, open("/kaggle/working/output/seq2seq/test.output.my", "w", encoding="utf-8") as f_out:
  for line in f_in:
    pieces = line.strip().split()
    decoded_text = my_spm.decode(pieces)
    f_out.write(decoded_text + "\n")

with open(
    "/kaggle/working/output/seq2seq/test.output.hi.spm", "r", encoding="utf-8"
) as f_in, open("/kaggle/working/output/seq2seq/test.output.hi", "w", encoding="utf-8") as f_out:
  for line in f_in:
    pieces = line.strip().split()
    decoded_text = hi_spm.decode(pieces)
    f_out.write(decoded_text + "\n")

print("Test set successfully detokenized!")

Test set successfully detokenized!

In [17]:
print("--- Scoring Hieroglyph -> Burmese RNN Model ---")
!sacrebleu /kaggle/working/data/test.my -i /kaggle/working/output/seq2seq/test.output.my
print("--- Scoring Burmese -> Hieroglyph RNN Model ---")
!sacrebleu /kaggle/working/data/test.hi -i /kaggle/working/output/seq2seq/test.output.hi

--- Scoring Hieroglyph -> Burmese RNN Model ---
{
 "name": "BLEU",
 "score": 19.8,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.6.0",
 "verbose_score": "27.7/13.6/12.4/33.3 (BP = 1.000 ratio = 1.024 hyp_len = 979 ref_len = 956)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.6.0"
}
--- Scoring Burmese -> Hieroglyph RNN Model ---
{
 "name": "BLEU",
 "score": 11.8,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.6.0",
 "verbose_score": "39.3/17.7/7.7/3.7 (BP = 1.000 ratio = 1.067 hyp_len = 1678 ref_len = 1573)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.6.0"
}

In [18]:
import pandas as pd

# Define paths to your test dataset files
src_file = "/kaggle/working/data/test.my"
ref_file = "/kaggle/working/data/test.hi"
pred_file = "/kaggle/working/output/seq2seq/test.output.hi"

# Read lines from all three files
with open(src_file, "r", encoding="utf-8") as f_src, open(
    ref_file, "r", encoding="utf-8"
) as f_ref, open(pred_file, "r", encoding="utf-8") as f_pred:
  src_lines = [line.strip() for line in f_src]
  ref_lines = [line.strip() for line in f_ref]
  pred_lines = [line.strip() for line in f_pred]

# Select 10 sample indices to inspect
sample_indices = [0, 1, 2, 5, 10, 20, 40, 80, 160, 320]

samples = []
for idx in sample_indices:
  if idx < len(src_lines):
    samples.append({
        "Index": idx,
        "Source (Burmese)": src_lines[idx],
        "Reference (Hieroglyphs)": ref_lines[idx],
        "Prediction (Hieroglyphs)": pred_lines[idx],
    })

# Format as a clean Pandas DataFrame for easy viewing
df_samples = pd.DataFrame(samples)
pd.set_option("display.max_colwidth", None)
display(df_samples)

,Index,Source (Burmese),Reference (Hieroglyphs),Prediction (Hieroglyphs)
0,0,အချစ်က နာကျင်စေတယ်။,𓂋𓐍𓎼𓂝 𓊪𓎡𓋴𓈎𓈙,𓈎𓊪𓆑𓈙 𓆑𓈙 𓉔𓂧 𓆑𓇌𓂝𓄿
1,1,ကျွန်မမှာ အစားအစာမရှိဘူး။,𓆑 𓊪𓄿𓎼𓂝 𓎜𓀀 𓅲𓀀𓐍𓇌,𓆑 𓊪𓄿𓇌 𓎜𓀀 𓅲𓀀𓐍𓇌
2,2,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။,𓎜𓀀 𓐍𓎛𓂝 𓈙𓄿𓏏 𓉔𓂝,𓎜𓀀𓇋𓐍𓇌𓂧 𓈙𓄿𓏏 𓉔𓂝
3,5,ခရီးကောင်းပါ,𓊪𓄿𓎼𓂝 𓄿 𓎛𓆑𓏭𓂝 𓈎𓋴𓆑𓄡,𓊪𓄿𓎼𓂝 𓄿 𓈙𓄿𓅱𓂝 𓈎𓋴𓆑𓄡
4,10,နင့်နံ့က ကောင်းတယ်,𓂨𓀀𓎡 𓈙𓉔𓂝𓂋𓂋 𓃀𓐍𓐍𓇌,𓆑𓈙 𓈎𓐍𓉔 𓄿𓎛 𓂝𓂋𓈖
5,20,ဒါက ကြီးမားပါတယ်။,𓈎𓊪𓆑𓈙 𓆑𓈙 𓊪𓎡𓃀𓂝,𓈎𓊪𓆑𓈙 𓆑𓈙 𓇋𓆑𓃀
6,40,ကံမကောင်းခဲ့ဘူး။,𓆑𓈎 𓏏𓄿𓈙𓎛𓈎 𓂋𓎡𓏭𓈖,𓏏𓂝 𓏏𓂝𓋴𓂝𓎛𓈎 𓂋𓎡𓏭𓈖𓂧
7,80,သူတွေ့တယ်။,𓊪𓂝 𓅲𓀀𓎡𓎛𓇌 𓆑𓈎,𓊪𓂝 𓇌𓆑𓇌 𓆑𓈎 𓄿𓃀𓄿𓆑𓎛
8,160,ပိုဆိုးလာတယ်,𓆑𓈎 𓃀𓂝𓈎𓈙 𓏏𓐍𓋴𓈙𓂝,𓆑𓉔 𓈙𓎡𓏭𓊪 𓄿 𓅲𓀀𓐍𓂋
9,320,ကျွန်တော် အလုပ်ကြိုးစားတယ်။,𓆑𓂋𓂋 𓏏𓐍𓋴𓈖 𓊪𓄿𓋴𓇌,𓆑𓉔 𓊪𓄿𓋴𓇌𓏏𓐍𓋴𓈖𓆑𓎛𓃀

In [19]:
import pandas as pd

# Define paths to your test dataset files
src_file = "/kaggle/working/data/test.hi"
ref_file = "/kaggle/working/data/test.my"
pred_file = "/kaggle/working/output/seq2seq/test.output.my"

# Read lines from all three files
with open(src_file, "r", encoding="utf-8") as f_src, open(
    ref_file, "r", encoding="utf-8"
) as f_ref, open(pred_file, "r", encoding="utf-8") as f_pred:
  src_lines = [line.strip() for line in f_src]
  ref_lines = [line.strip() for line in f_ref]
  pred_lines = [line.strip() for line in f_pred]

# Select 10 sample indices to inspect
sample_indices = [0, 1, 2, 5, 10, 20, 40, 80, 160, 320]

samples = []
for idx in sample_indices:
  if idx < len(src_lines):
    samples.append({
        "Index": idx,
        "Source (Hieroglyphs)": src_lines[idx],
        "Reference (Burmese)": ref_lines[idx],
        "Prediction (Burmese)": pred_lines[idx],
    })

# Format as a clean Pandas DataFrame for easy viewing
df_samples = pd.DataFrame(samples)
pd.set_option("display.max_colwidth", None)
display(df_samples)

,Index,Source (Hieroglyphs),Reference (Burmese),Prediction (Burmese)
0,0,𓂋𓐍𓎼𓂝 𓊪𓎡𓋴𓈎𓈙,အချစ်က နာကျင်စေတယ်။,ကျွန်မ ပြောနေတာ
1,1,𓆑 𓊪𓄿𓎼𓂝 𓎜𓀀 𓅲𓀀𓐍𓇌,ကျွန်မမှာ အစားအစာမရှိဘူး။,ကျွန်မမှာ အစားအစာရှိတယ်
2,2,𓎜𓀀 𓐍𓎛𓂝 𓈙𓄿𓏏 𓉔𓂝,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။
3,5,𓊪𓄿𓎼𓂝 𓄿 𓎛𓆑𓏭𓂝 𓈎𓋴𓆑𓄡,ခရီးကောင်းပါ,ခရီးကောင်းပါ
4,10,𓂨𓀀𓎡 𓈙𓉔𓂝𓂋𓂋 𓃀𓐍𓐍𓇌,နင့်နံ့က ကောင်းတယ်,မင်းက မကောင်းဘူး
5,20,𓈎𓊪𓆑𓈙 𓆑𓈙 𓊪𓎡𓃀𓂝,ဒါက ကြီးမားပါတယ်။,ဒါက ခွေးတစ်ကောင်ပါ။
6,40,𓆑𓈎 𓏏𓄿𓈙𓎛𓈎 𓂋𓎡𓏭𓈖,ကံမကောင်းခဲ့ဘူး။,ဆူညံသံတွေ အများကြီးပါ။
7,80,𓊪𓂝 𓅲𓀀𓎡𓎛𓇌 𓆑𓈎,သူတွေ့တယ်။,သူအောင်မြင်ခဲ့တယ်။
8,160,𓆑𓈎 𓃀𓂝𓈎𓈙 𓏏𓐍𓋴𓈙𓂝,ပိုဆိုးလာတယ်,ဒါဟာ အဓိပ္ပါယ်မရှိပါဘူး။
9,320,𓆑𓂋𓂋 𓏏𓐍𓋴𓈖 𓊪𓄿𓋴𓇌,ကျွန်တော် အလုပ်ကြိုးစားတယ်။,Tom က ငိုလိမ့်မယ်။

In [32]:
MARIAN_DECODER="/kaggle/working/marian-dev/build/marian-decoder"

!{MARIAN_DECODER} \
  --models /kaggle/working/models/transformer/hi-my.npz /kaggle/working/models/seq2seq/hi-my-rnn.npz \
  --weights 0.6 0.4 \
  --vocabs /kaggle/working/data/hi.vocab.yml /kaggle/working/data/my.vocab.yml \
  --beam-size 12 \
  --normalize 1.0 \
  < /kaggle/working/data/test.hi.spm \
  > /kaggle/working/output/ensemble/test.output.my.ensemble.spm

[2026-10-15 16:28:06] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:28:06] [marian] Running on f2fe76130532 as process 18916 with command line:
[2026-10-15 16:28:06] [marian] /kaggle/working/marian-dev/build/marian-decoder --models /kaggle/working/models/transformer/hi-my.npz /kaggle/working/models/seq2seq/hi-my-rnn.npz --weights 0.6 0.4 --vocabs /kaggle/working/data/hi.vocab.yml /kaggle/working/data/my.vocab.yml --beam-size 12 --normalize 1.0
[2026-10-15 16:28:07] [config] alignment: ""
[2026-10-15 16:28:07] [config] allow-special: false
[2026-10-15 16:28:07] [config] allow-unk: false
[2026-10-15 16:28:07] [config] authors: false
[2026-10-15 16:28:07] [config] beam-size: 12
[2026-10-15 16:28:07] [config] bert-class-symbol: "[CLS]"
[2026-10-15 16:28:07] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 16:28:07] [config] bert-masking-fraction: 0.15
[2026-10-15 16:28:07] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 16:28:07] [config] bert-train-type-embeddings: true
[2026-10-15 16:28:07] [config] bert-type-vocab-size: 2
[2026-10-15 16:28:07] [config] best-deep: false
[2026-10-15 16:28:07] [config] build-info: ""
[2026-10-15 16:28:07] [config] check-nan: false
[2026-10-15 16:28:07] [config] cite: false
[2026-10-15 16:28:07] [config] comet-augment-bad: 0
[2026-10-15 16:28:07] [config] comet-dropout: 0.1
[2026-10-15 16:28:07] [config] comet-final-sigmoid: false
[2026-10-15 16:28:07] [config] comet-mix: false
[2026-10-15 16:28:07] [config] comet-mix-norm: false
[2026-10-15 16:28:07] [config] comet-mix-transformation: softmax
[2026-10-15 16:28:07] [config] comet-mixup: 0
[2026-10-15 16:28:07] [config] comet-mixup-reg: false
[2026-10-15 16:28:07] [config] comet-pool: avg
[2026-10-15 16:28:07] [config] comet-pooler-ffn:
[2026-10-15 16:28:07] [config]   - 2048
[2026-10-15 16:28:07] [config]   - 1024
[2026-10-15 16:28:07] [config] comet-prepend-zero: false
[2026-10-15 16:28:07] [config] comet-stop-grad: false
[2026-10-15 16:28:07] [config] comet-use-separator: false
[2026-10-15 16:28:07] [config] cpu-threads: 0
[2026-10-15 16:28:07] [config] data-threads: 8
[2026-10-15 16:28:07] [config] dec-cell: gru
[2026-10-15 16:28:07] [config] dec-cell-base-depth: 2
[2026-10-15 16:28:07] [config] dec-cell-high-depth: 1
[2026-10-15 16:28:07] [config] dec-depth: 4
[2026-10-15 16:28:07] [config] devices:
[2026-10-15 16:28:07] [config]   - 0
[2026-10-15 16:28:07] [config] dim-emb: 512
[2026-10-15 16:28:07] [config] dim-rnn: 1024
[2026-10-15 16:28:07] [config] dim-vocabs:
[2026-10-15 16:28:07] [config]   - 2988
[2026-10-15 16:28:07] [config]   - 6014
[2026-10-15 16:28:07] [config] dump-config: ""
[2026-10-15 16:28:07] [config] enc-cell: gru
[2026-10-15 16:28:07] [config] enc-cell-depth: 1
[2026-10-15 16:28:07] [config] enc-depth: 4
[2026-10-15 16:28:07] [config] enc-type: bidirectional
[2026-10-15 16:28:07] [config] factors-combine: sum
[2026-10-15 16:28:07] [config] factors-dim-emb: 0
[2026-10-15 16:28:07] [config] force-decode: false
[2026-10-15 16:28:07] [config] gemm-type: float32
[2026-10-15 16:28:07] [config] ignore-model-config: false
[2026-10-15 16:28:07] [config] input:
[2026-10-15 16:28:07] [config]   - stdin
[2026-10-15 16:28:07] [config] input-join-fields: false
[2026-10-15 16:28:07] [config] input-reorder:
[2026-10-15 16:28:07] [config]   []
[2026-10-15 16:28:07] [config] input-types:
[2026-10-15 16:28:07] [config]   []
[2026-10-15 16:28:07] [config] interpolate-env-vars: false
[2026-10-15 16:28:07] [config] layer-normalization: false
[2026-10-15 16:28:07] [config] lemma-dependency: ""
[2026-10-15 16:28:07] [config] lemma-dim-emb: 0
[2026-10-15 16:28:07] [config] log: ""
[2026-10-15 16:28:07] [config] log-level: info
[2026-10-15 16:28:07] [config] log-time-zone: ""
[2026-10-15 16:28:07] [config] max-length: 1000
[2026-10-15 16:28:07] [config] max-length-crop: false
[2026-10-15 16:28:07] [config] max-length-factor: 3
[2026-10-15 16:28:07] [config] maxi-batch: 1
[2026-10-15 16:28:07] [config] maxi-batch-sort: none
[2026-10-15 16:28:07] [config] mini-batch: 1
[2026-10-15 16:28:07] [config] mini-batch-words: 0
[2026-10-15 16:28:07] [config] model-mmap: false
[2026-10-15 16:28:07] [config] models:
[2026-10-15 16:28:07] [config]   - /kaggle/working/models/transformer/hi-my.npz
[2026-10-15 16:28:07] [config]   - /kaggle/working/models/seq2seq/hi-my-rnn.npz
[2026-10-15 16:28:07] [config] n-best: false
[2026-10-15 16:28:07] [config] no-spm-decode: false
[2026-10-15 16:28:07] [config] no-spm-encode: false
[2026-10-15 16:28:07] [config] normalize: 1
[2026-10-15 16:28:07] [config] optimize: false
[2026-10-15 16:28:07] [config] output: stdout
[2026-10-15 16:28:07] [config] output-approx-knn:
[2026-10-15 16:28:07] [config]   []
[2026-10-15 16:28:07] [config] output-omit-bias: false
[2026-10-15 16:28:07] [config] output-sampling:
[2026-10-15 16:28:07] [config]   []
[2026-10-15 16:28:07] [config] precision:
[2026-10-15 16:28:07] [config]   - float32
[2026-10-15 16:28:07] [config] quantize-range: 0
[2026-10-15 16:28:07] [config] quiet: false
[2026-10-15 16:28:07] [config] quiet-translation: false
[2026-10-15 16:28:07] [config] relative-paths: false
[2026-10-15 16:28:07] [config] right-left: false
[2026-10-15 16:28:07] [config] seed: 0
[2026-10-15 16:28:07] [config] separator-symbol: "[eos]"
[2026-10-15 16:28:07] [config] shortlist:
[2026-10-15 16:28:07] [config]   []
[2026-10-15 16:28:07] [config] skip: false
[2026-10-15 16:28:07] [config] skip-cost: false
[2026-10-15 16:28:07] [config] stat-freq: 0
[2026-10-15 16:28:07] [config] tied-embeddings: false
[2026-10-15 16:28:07] [config] tied-embeddings-all: false
[2026-10-15 16:28:07] [config] tied-embeddings-src: false
[2026-10-15 16:28:07] [config] transformer-aan-activation: swish
[2026-10-15 16:28:07] [config] transformer-aan-depth: 2
[2026-10-15 16:28:07] [config] transformer-aan-nogate: false
[2026-10-15 16:28:07] [config] transformer-alibi-shift: false
[2026-10-15 16:28:07] [config] transformer-alibi-trainable: false
[2026-10-15 16:28:07] [config] transformer-attention-mask: default
[2026-10-15 16:28:07] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 16:28:07] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 16:28:07] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 16:28:07] [config] transformer-depth-scaling: false
[2026-10-15 16:28:07] [config] transformer-dim-aan: 2048
[2026-10-15 16:28:07] [config] transformer-dim-ffn: 2048
[2026-10-15 16:28:07] [config] transformer-disable-position-embeddings: false
[2026-10-15 16:28:07] [config] transformer-ffn-activation: swish
[2026-10-15 16:28:07] [config] transformer-ffn-depth: 2
[2026-10-15 16:28:07] [config] transformer-guided-alignment-layer: last
[2026-10-15 16:28:07] [config] transformer-heads: 4
[2026-10-15 16:28:07] [config] transformer-no-affine: false
[2026-10-15 16:28:07] [config] transformer-no-bias: false
[2026-10-15 16:28:07] [config] transformer-no-projection: false
[2026-10-15 16:28:07] [config] transformer-pool: false
[2026-10-15 16:28:07] [config] transformer-postprocess: dan
[2026-10-15 16:28:07] [config] transformer-postprocess-emb: d
[2026-10-15 16:28:07] [config] transformer-postprocess-top: ""
[2026-10-15 16:28:07] [config] transformer-preprocess: ""
[2026-10-15 16:28:07] [config] transformer-rnn-projection: false
[2026-10-15 16:28:07] [config] transformer-tied-layers:
[2026-10-15 16:28:07] [config]   []
[2026-10-15 16:28:07] [config] transformer-train-position-embeddings: false
[2026-10-15 16:28:07] [config] tsv: false
[2026-10-15 16:28:07] [config] tsv-fields: 0
[2026-10-15 16:28:07] [config] type: transformer
[2026-10-15 16:28:07] [config] ulr: false
[2026-10-15 16:28:07] [config] ulr-dim-emb: 0
[2026-10-15 16:28:07] [config] ulr-trainable-transformation: false
[2026-10-15 16:28:07] [config] version: v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:28:07] [config] vocabs:
[2026-10-15 16:28:07] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 16:28:07] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 16:28:07] [config] weights:
[2026-10-15 16:28:07] [config]   - 0.6
[2026-10-15 16:28:07] [config]   - 0.4
[2026-10-15 16:28:07] [config] word-penalty: 0
[2026-10-15 16:28:07] [config] word-scores: false
[2026-10-15 16:28:07] [config] workspace: 512
[2026-10-15 16:28:07] [config] Loaded model has been created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:28:07] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 16:28:07] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 16:28:07] Loading model from /kaggle/working/models/transformer/hi-my.npz
[2026-10-15 16:28:07] Loading model from /kaggle/working/models/seq2seq/hi-my-rnn.npz
[2026-10-15 16:28:07] [memory] Extending reserved space to 512 MB (device gpu0)
[2026-10-15 16:28:07] Loaded model config
[2026-10-15 16:28:07] Loading scorer of type transformer as feature F0
[2026-10-15 16:28:07] Loaded model config
[2026-10-15 16:28:07] Loading scorer of type s2s as feature F1
[2026-10-15 16:28:07] [memory] Reserving 300 MB, device gpu0
[2026-10-15 16:28:08] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 16:28:08] Best translation 0 : ▁ကျွန်မ ▁နိုင်တာကို ▁ကြိုက်တယ်။
[2026-10-15 16:28:08] Best translation 1 : ▁ကျွန်မမှာ ▁အစားအစာ ရှိတယ်
[2026-10-15 16:28:08] Best translation 2 : ▁ဘယ်သူမှ ▁ကျွန်မကို ▁မမြင်ခဲ့ဘူး။
[2026-10-15 16:28:08] Best translation 3 : ▁စောင့်ကြည့် နေသူပါ။
[2026-10-15 16:28:08] Best translation 4 : ▁အသင်း တစ်သင်း ဖြစ်ခဲ့
[2026-10-15 16:28:08] Best translation 5 : ▁ခရီး ကောင်းပါ
[2026-10-15 16:28:08] Best translation 6 : ▁ဘယ်လို ပဲဖြစ်ဖြစ် ▁သွားမယ်။
[2026-10-15 16:28:08] Best translation 7 : ▁အခန်းက ▁ပူနေတယ်။
[2026-10-15 16:28:08] Best translation 8 : ▁သူဟာ ▁မြန်မြန် ▁လျှောက် တတ်တယ်။
[2026-10-15 16:28:08] Best translation 9 : ▁ဒါပဲ
[2026-10-15 16:28:08] Best translation 10 : ▁မင်းက ▁ကောင်းကောင်း ▁ခံစားရတယ်။
[2026-10-15 16:28:08] Best translation 11 : ▁ကျွန်တော် ပေးပါရစေ။
[2026-10-15 16:28:08] Best translation 12 : ▁ကျွန်မ ▁တာဝန်ရှိနေတယ်။
[2026-10-15 16:28:08] Best translation 13 : ▁ပိုများ မယ်လို့ ▁မျှော်လင့် ခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 14 : ▁မင်းကို ▁စိတ်ပျက် စေခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 15 : ▁အံ့သြစရာတွေကို ▁ကြိုက်တယ်။
[2026-10-15 16:28:08] Best translation 16 : ▁သူမက ▁ကြိုးစားခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 17 : ▁ကျွန်မ ▁ဟာသ ဇာတ်လမ်း တွေကို ▁ကြိုက်တယ်။
[2026-10-15 16:28:08] Best translation 18 : ▁တစ်ခုခုကို ▁မြင်ခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 19 : ▁ကျွန်မမှာ ▁တစ်ခုခု ရှိတယ်
[2026-10-15 16:28:08] Best translation 20 : ▁ဒါက ▁ခွေးတစ်ကောင် ပါ။
[2026-10-15 16:28:08] Best translation 21 : ▁နွားနို့ ကို ▁မုန်းတယ်။
[2026-10-15 16:28:08] Best translation 22 : ▁သူ့မှာ ▁ခွေးတစ်ကောင် ရှိတယ်။
[2026-10-15 16:28:08] Best translation 23 : ▁ကျွန်မတို့ဟာ ▁မိသားစု ပါ။
[2026-10-15 16:28:08] Best translation 24 : ▁သူမက ▁သူ့ကို ▁ချစ်တယ်။
[2026-10-15 16:28:08] Best translation 25 : ▁သူနာကျင် နေခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 26 : ▁လမ်းလျှောက်တာ ▁ပိုကြိုက်တယ်။
[2026-10-15 16:28:08] Best translation 27 : ▁ကျွန်မက ▁ပေး နိုင်တယ်
[2026-10-15 16:28:08] Best translation 28 : ▁သိပ် ကောင်းပါတယ်။
[2026-10-15 16:28:08] Best translation 29 : ▁Tom ▁ကို ▁မသိနားမလည် ခဲ့ဘူး။
[2026-10-15 16:28:08] Best translation 30 : ▁ပြောတာကို ▁လုပ်ပါ။
[2026-10-15 16:28:08] Best translation 31 : ▁ဒါက ▁အချစ်လား။
[2026-10-15 16:28:08] Best translation 32 : ▁အားလုံး ▁ထွက်လိုက် ကြပြီ။
[2026-10-15 16:28:08] Best translation 33 : ▁မင်း ▁အရမ်းနောက်ကျ နေပြီ
[2026-10-15 16:28:08] Best translation 34 : ▁ဒါကို ▁မသုံး နိုင်ဘူး။
[2026-10-15 16:28:08] Best translation 35 : ▁သူက ▁မင်းသား
[2026-10-15 16:28:08] Best translation 36 : ▁အမှောင် ဆဲပါ။
[2026-10-15 16:28:08] Best translation 37 : ▁ဒါက ▁ချိန်းဆို မှု မဟုတ်ဘူး။
[2026-10-15 16:28:08] Best translation 38 : ▁ဒါကို ▁ငါလေး ခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 39 : ▁သူတို့က ▁ကျွန်တော်တို့ ▁ဘယ်မှာလဲ။
[2026-10-15 16:28:08] Best translation 40 : ▁အဲဒါက ▁ငါ့ဟာ ▁မဟုတ် ခဲ့ဘူး။
[2026-10-15 16:28:08] Best translation 41 : ▁မင်းက ▁ကောင်းတယ်။
[2026-10-15 16:28:08] Best translation 42 : ▁စိတ်ဝင်စား စရာပါ။
[2026-10-15 16:28:08] Best translation 43 : ▁ဒါက ▁မိုက်လိုက်တာ
[2026-10-15 16:28:08] Best translation 44 : ▁ကျွန်မက ▁ရိုးစင်းခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 45 : ▁အနားယူ ချိန်များ ▁ပြီးဆုံး
[2026-10-15 16:28:08] Best translation 46 : ▁သူက ▁ကျွန်မအ ရွယ် ပဲရှိပါသေးတယ်။
[2026-10-15 16:28:08] Best translation 47 : ▁ကျွန်မ ▁လိမ် ခဲ့တယ်။
[2026-10-15 16:28:08] Best translation 48 : ▁သူထွက်သွားပြီ
[2026-10-15 16:28:09] Best translation 49 : ▁ဖြစ်ပျက် ခဲ့တယ်။
[2026-10-15 16:28:09] Best translation 50 : ▁သူဟာ ▁ချွေးထွက် လာခဲ့တယ်။
[2026-10-15 16:28:09] Best translation 51 : ▁ကျွန်မ ▁အဆင်သင့်ဖြစ် နေပြီလို့ ▁ခံစားမိတယ်။
[2026-10-15 16:28:09] Best translation 52 : ▁သူ့ကို ▁လိုက်ခဲ့
[2026-10-15 16:28:09] Best translation 53 : ▁အားလုံးက ▁ရူးကြောင်ကြောင်
[2026-10-15 16:28:09] Best translation 54 : ▁ကျွန်တော်က ▁ငတုံးမဟုတ်ဘူး။
[2026-10-15 16:28:09] Best translation 55 : ▁သူအိမ် မှာလား။
[2026-10-15 16:28:09] Best translation 56 : ▁ကျွန်မပြော သလို ▁လုပ်ပါ။
[2026-10-15 16:28:09] Best translation 57 : ▁အားလုံး ▁အဆင်ပြေပါတယ်။
[2026-10-15 16:28:09] Best translation 58 : ▁အော်ဟစ်တာ ▁ရပ်လိုက်ပါ
[2026-10-15 16:28:09] Best translation 59 : ▁Tom ▁က ▁ရက်စက်တယ်။
[2026-10-15 16:28:09] Best translation 60 : ▁ပဟေ ဠ ိတွေကို ▁ကြိုက်တယ်။
[2026-10-15 16:28:09] Best translation 61 : ▁သူ ▁ဖတ် လို့မရဘူး။
[2026-10-15 16:28:09] Best translation 62 : ▁ကျွန်မမှာ ▁ဘာရှိလဲ။
[2026-10-15 16:28:09] Best translation 63 : ▁လက်ဖက်ရည် သောက်ပါ။
[2026-10-15 16:28:09] Best translation 64 : ▁ကျွန်မတို့က ▁အကောင်းဆုံး တွေပါ။
[2026-10-15 16:28:09] Best translation 65 : ▁ရေခဲ တစ်လုံး ▁လိုတယ်။
[2026-10-15 16:28:09] Best translation 66 : ▁နေ့လည်စာ ▁အသင့်ရှိ ပြီလား။
[2026-10-15 16:28:09] Best translation 67 : ▁မိသားစု မရှိဘူး။
[2026-10-15 16:28:09] Best translation 68 : ▁မင်းက ▁အဆိုတော် မဟုတ်ဘူး။
[2026-10-15 16:28:09] Best translation 69 : ▁တံခါးဖွင့် ထားလား။
[2026-10-15 16:28:09] Best translation 70 : ▁သူက ▁ကျွန်မ အတန်း ထဲမှာပါ။
[2026-10-15 16:28:09] Best translation 71 : ▁နေ့ကောင်း တစ်ခုရှိပါစေ။
[2026-10-15 16:28:09] Best translation 72 : ▁ဘယ်သူမှ ▁မကျန်းမာ ခဲ့ဘူး။
[2026-10-15 16:28:09] Best translation 73 : ▁တီဗွီကို ▁ဖွင့်လိုက်ပါ
[2026-10-15 16:28:09] Best translation 74 : ▁အချိန်ကုန် သွားပြီ။
[2026-10-15 16:28:09] Best translation 75 : ▁ကျွန်တော်ကတော့ ▁ဆန့်ကျင်ပါတယ်။
[2026-10-15 16:28:09] Best translation 76 : ▁ပါးစပ်က ▁တုံပြန် နေပြီ။
[2026-10-15 16:28:09] Best translation 77 : ▁ကျွန်မတို့ ▁ချွတ် နေပြီလား။
[2026-10-15 16:28:09] Best translation 78 : ▁Tom ▁ဟာ ▁မြန်မြန်ပြေး နိုင်တယ်
[2026-10-15 16:28:09] Best translation 79 : ▁Tom ▁က ▁တောင်းပန် တယ်။
[2026-10-15 16:28:09] Best translation 80 : ▁သူအောင် မြင်ခဲ့တယ်။
[2026-10-15 16:28:09] Best translation 81 : ▁Tom ▁က ▁ငြင်းမယ်။
[2026-10-15 16:28:09] Best translation 82 : ▁ကျွန်မ ▁အများကြီး ▁စားတယ်။
[2026-10-15 16:28:09] Best translation 83 : ▁Toms ▁ဟာ ▁ဒေါသထွက်တယ်။
[2026-10-15 16:28:09] Best translation 84 : ▁ကျွန်တော်လုပ် နိုင်တယ် လို့ထင်တယ်။
[2026-10-15 16:28:09] Best translation 85 : ▁သူဟာ ▁မြန်မြန် ကူးနိုင်တယ်
[2026-10-15 16:28:09] Best translation 86 : ▁ကြိုးကို ▁ဖြတ်လိုက်တယ်။
[2026-10-15 16:28:09] Best translation 87 : ▁ဒါကို ▁သိလား။
[2026-10-15 16:28:09] Best translation 88 : ▁ချက်ချင်းလာပါ
[2026-10-15 16:28:09] Best translation 89 : ▁သူဟာ ▁ပါရီကို ▁ပျံသန်း ခဲ့တယ်။
[2026-10-15 16:28:09] Best translation 90 : ▁ရှင်း ပြီလား။
[2026-10-15 16:28:09] Best translation 91 : ▁သူမျက် နှာကို ▁မော့ ထားတယ်။
[2026-10-15 16:28:09] Best translation 92 : ▁ဒါက ▁ကျွန်မပါ။
[2026-10-15 16:28:09] Best translation 93 : ▁ကျွန်မ ▁မပြီးသေးဘူး။
[2026-10-15 16:28:09] Best translation 94 : ▁ကျွန်တော် ▁ဘာလုပ်ပေး နိုင်လဲ။
[2026-10-15 16:28:09] Best translation 95 : ▁ငါက ▁အကောင်းဆုံးပါ။
[2026-10-15 16:28:09] Best translation 96 : ▁အချိန်ကုန် သွားပြီ။
[2026-10-15 16:28:09] Best translation 97 : ▁အားလုံး ▁ထွက်လိုက် ကြပြီ။
[2026-10-15 16:28:09] Best translation 98 : ▁ကျွန်မက ▁အစာချေနေတာပါ။
[2026-10-15 16:28:09] Best translation 99 : ▁ဒါက ▁ပျော်စရာ မဟုတ်ဘူး။
[2026-10-15 16:28:09] Best translation 100 : ▁မင်းကို ▁စိတ်ပျက် စေခဲ့တယ်။
[2026-10-15 16:28:09] Best translation 101 : ▁Tom ▁က ▁ပြေးရတာ ▁ကြိုက်တယ်။
[2026-10-15 16:28:09] Best translation 102 : ▁ခင်ဗျားက ▁ B os t o n ▁မှာလား။
[2026-10-15 16:28:09] Best translation 103 : ▁လာပြီး ▁ကျွန်မတို့ နဲ့အတူပါ
[2026-10-15 16:28:09] Best translation 104 : ▁အင်္ဂ ါဂြိုဟ်ဟာ ▁ဂြိုဟ် တစ်လုံးပါ။
[2026-10-15 16:28:09] Best translation 105 : ▁လာ လို့ရတယ်
[2026-10-15 16:28:09] Best translation 106 : ▁ ဈ ေးနှ ုန်းတွေက ▁မြင့်တယ်။
[2026-10-15 16:28:09] Best translation 107 : ▁ဒါက ▁ကျွန်တော့ ခွေးက ▁စားခဲ့တယ်။
[2026-10-15 16:28:09] Best translation 108 : ▁ကူညီချင်တယ်။
[2026-10-15 16:28:09] Best translation 109 : ▁သူက ▁အမဲလိုက်တာကို ▁ကြိုက်တယ်။
[2026-10-15 16:28:10] Best translation 110 : ▁ဒါကို ▁ကျွန်မသိပါတယ်။
[2026-10-15 16:28:10] Best translation 111 : ▁ဒီခွေးက ▁ငါ့ခွေး
[2026-10-15 16:28:10] Best translation 112 : ▁ဘတ်စ်ကား တိုင်း ▁ပြည့် နေတယ်။
[2026-10-15 16:28:10] Best translation 113 : ▁ဘယ်အချိန် လောက်မှာလဲ။
[2026-10-15 16:28:10] Best translation 114 : ▁ ၎ င်းရဲ့ ▁ရှုပ် ထွေးမှု
[2026-10-15 16:28:10] Best translation 115 : ▁ဒါကို ▁ကျော်လ ွှားခဲ့တယ်။
[2026-10-15 16:28:10] Best translation 116 : ▁နေ့လည်စာ မှာ ▁တွေ့ကြမယ်။
[2026-10-15 16:28:10] Best translation 117 : ▁မင်းက ▁ပင်ပန်း ပုံပေါက်တယ်။
[2026-10-15 16:28:10] Best translation 118 : ▁တံခါးက ▁ဖွင့်ထားတယ်။
[2026-10-15 16:28:10] Best translation 119 : ▁ပျော်ခဲ့တယ်။
[2026-10-15 16:28:10] Best translation 120 : ▁မလုပ်ချင်ဘူး။
[2026-10-15 16:28:10] Best translation 121 : ▁နောက်ကျ တာအတွက် ▁စိတ်မကောင်း ပါဘူး။
[2026-10-15 16:28:10] Best translation 122 : ▁Tom ▁က ▁ဒါကို ▁လိုချင်ခဲ့တယ်။
[2026-10-15 16:28:10] Best translation 123 : ▁ဒီမှာ ▁ဘယ်သူ များရှိလဲ။
[2026-10-15 16:28:10] Best translation 124 : ▁မင်း ▁တစ်ယောက်တည်း လား။
[2026-10-15 16:28:10] Best translation 125 : ▁ကျွန်မမှာ ▁သံသယ တွေရှိတယ်
[2026-10-15 16:28:10] Best translation 126 : ▁ကျွန်တော် ▁အနိုင်ရခဲ့တယ်။
[2026-10-15 16:28:10] Best translation 127 : ▁မင်းက ▁ပျော် နေခဲ့တာ
[2026-10-15 16:28:10] Best translation 128 : ▁ကျွန်မ ▁အများကြီး ▁စားတယ်။
[2026-10-15 16:28:10] Best translation 129 : ▁ကျွန်မက ▁အသားကျဉ်း တယ်။
[2026-10-15 16:28:10] Best translation 130 : ▁Tom ▁ကို ▁ရိုက် မိတယ်။
[2026-10-15 16:28:10] Best translation 131 : ▁ကျွန်မအတွက် ▁တက္ကစီ လိုတယ်။
[2026-10-15 16:28:10] Best translation 132 : ▁Tom ▁ဟာ ▁အရမ်း ဆိုးတယ်။
[2026-10-15 16:28:10] Best translation 133 : ▁ဒါဟာ ▁ကစားပွဲ မဟုတ်ဘူး။
[2026-10-15 16:28:10] Best translation 134 : ▁စိတ်ကူး တွေက ုန်သွားပြီ။
[2026-10-15 16:28:10] Best translation 135 : ▁မင်းနဲ့အတူ ▁မတက်နိုင်ဘူး။
[2026-10-15 16:28:10] Best translation 136 : ▁ကျွန်မ ▁ကြောက်လန့် ခဲ့တယ်။
[2026-10-15 16:28:10] Best translation 137 : ▁ကလေးတွေ ▁ဘယ်လိုများလဲ။
[2026-10-15 16:28:10] Best translation 138 : ▁ကံကောင်း ပါစေလို့ ▁ဆုတောင်းပါတယ်။
[2026-10-15 16:28:10] Best translation 139 : ▁Tom ▁က ▁ကျွန်မကို ▁စွန့်ခွာ သွားခဲ့တယ်။
[2026-10-15 16:28:10] Best translation 140 : ▁နိုးနေပြီ
[2026-10-15 16:28:10] Best translation 141 : ▁ဒါကို ▁သိလား။
[2026-10-15 16:28:10] Best translation 142 : ▁သင်ဟာ ▁အနားယူ ဖို့လိုပါတယ်။
[2026-10-15 16:28:10] Best translation 143 : ▁သူမသွားဘူး။
[2026-10-15 16:28:10] Best translation 144 : ▁ဘယ်သူမှ ▁မလာခဲ့ဘူး။
[2026-10-15 16:28:10] Best translation 145 : ▁ငါဘယ်မှာလဲ
[2026-10-15 16:28:10] Best translation 146 : ▁Toms ▁ဘေးကင်းပါတယ်။
[2026-10-15 16:28:10] Best translation 147 : ▁Tom ▁က ▁ဂျင်းဘ ောင်းဘီ ဝတ်ထားတယ်။
[2026-10-15 16:28:10] Best translation 148 : ▁ဘာမှ မပြောခဲ့ဘူး။
[2026-10-15 16:28:10] Best translation 149 : ▁နေ့တိုင်း လာတယ်
[2026-10-15 16:28:10] Best translation 150 : ▁ဒါကို ▁မြှုပ် လိုက်တယ်။
[2026-10-15 16:28:10] Best translation 151 : ▁သူက ▁ဒီမှာ နေလား။
[2026-10-15 16:28:10] Best translation 152 : ▁မြင်နိုင်လား။
[2026-10-15 16:28:10] Best translation 153 : ▁ကျွန်မက ▁တော်တော် ရှက်တတ်တယ်။
[2026-10-15 16:28:10] Best translation 154 : ▁စောင့် သင့်လား။
[2026-10-15 16:28:10] Best translation 155 : ▁သတိထားမိတယ်။

In [33]:
!{MARIAN_DECODER} \
  --models /kaggle/working/models/transformer/my-hi.npz /kaggle/working/models/seq2seq/my-hi-rnn.npz \
  --weights 0.6 0.4 \
  --vocabs /kaggle/working/data/my.vocab.yml /kaggle/working/data/hi.vocab.yml \
  --beam-size 12 \
  --normalize 1.0 \
  < /kaggle/working/data/test.my.spm \
  > /kaggle/working/output/ensemble/test.output.hi.ensemble.spm

[2026-10-15 16:34:54] [marian] Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:34:54] [marian] Running on f2fe76130532 as process 18937 with command line:
[2026-10-15 16:34:54] [marian] /kaggle/working/marian-dev/build/marian-decoder --models /kaggle/working/models/transformer/my-hi.npz /kaggle/working/models/seq2seq/my-hi-rnn.npz --weights 0.6 0.4 --vocabs /kaggle/working/data/my.vocab.yml /kaggle/working/data/hi.vocab.yml --beam-size 12 --normalize 1.0
[2026-10-15 16:34:54] [config] alignment: ""
[2026-10-15 16:34:54] [config] allow-special: false
[2026-10-15 16:34:54] [config] allow-unk: false
[2026-10-15 16:34:54] [config] authors: false
[2026-10-15 16:34:54] [config] beam-size: 12
[2026-10-15 16:34:54] [config] bert-class-symbol: "[CLS]"
[2026-10-15 16:34:54] [config] bert-mask-symbol: "[MASK]"
[2026-10-15 16:34:54] [config] bert-masking-fraction: 0.15
[2026-10-15 16:34:54] [config] bert-sep-symbol: "[SEP]"
[2026-10-15 16:34:54] [config] bert-train-type-embeddings: true
[2026-10-15 16:34:54] [config] bert-type-vocab-size: 2
[2026-10-15 16:34:54] [config] best-deep: false
[2026-10-15 16:34:54] [config] build-info: ""
[2026-10-15 16:34:54] [config] check-nan: false
[2026-10-15 16:34:54] [config] cite: false
[2026-10-15 16:34:54] [config] comet-augment-bad: 0
[2026-10-15 16:34:54] [config] comet-dropout: 0.1
[2026-10-15 16:34:54] [config] comet-final-sigmoid: false
[2026-10-15 16:34:54] [config] comet-mix: false
[2026-10-15 16:34:54] [config] comet-mix-norm: false
[2026-10-15 16:34:54] [config] comet-mix-transformation: softmax
[2026-10-15 16:34:54] [config] comet-mixup: 0
[2026-10-15 16:34:54] [config] comet-mixup-reg: false
[2026-10-15 16:34:54] [config] comet-pool: avg
[2026-10-15 16:34:54] [config] comet-pooler-ffn:
[2026-10-15 16:34:54] [config]   - 2048
[2026-10-15 16:34:54] [config]   - 1024
[2026-10-15 16:34:54] [config] comet-prepend-zero: false
[2026-10-15 16:34:54] [config] comet-stop-grad: false
[2026-10-15 16:34:54] [config] comet-use-separator: false
[2026-10-15 16:34:54] [config] cpu-threads: 0
[2026-10-15 16:34:54] [config] data-threads: 8
[2026-10-15 16:34:54] [config] dec-cell: gru
[2026-10-15 16:34:54] [config] dec-cell-base-depth: 2
[2026-10-15 16:34:54] [config] dec-cell-high-depth: 1
[2026-10-15 16:34:54] [config] dec-depth: 4
[2026-10-15 16:34:54] [config] devices:
[2026-10-15 16:34:54] [config]   - 0
[2026-10-15 16:34:54] [config] dim-emb: 512
[2026-10-15 16:34:54] [config] dim-rnn: 1024
[2026-10-15 16:34:54] [config] dim-vocabs:
[2026-10-15 16:34:54] [config]   - 6014
[2026-10-15 16:34:54] [config]   - 2988
[2026-10-15 16:34:54] [config] dump-config: ""
[2026-10-15 16:34:54] [config] enc-cell: gru
[2026-10-15 16:34:54] [config] enc-cell-depth: 1
[2026-10-15 16:34:54] [config] enc-depth: 4
[2026-10-15 16:34:54] [config] enc-type: bidirectional
[2026-10-15 16:34:54] [config] factors-combine: sum
[2026-10-15 16:34:54] [config] factors-dim-emb: 0
[2026-10-15 16:34:54] [config] force-decode: false
[2026-10-15 16:34:54] [config] gemm-type: float32
[2026-10-15 16:34:54] [config] ignore-model-config: false
[2026-10-15 16:34:54] [config] input:
[2026-10-15 16:34:54] [config]   - stdin
[2026-10-15 16:34:54] [config] input-join-fields: false
[2026-10-15 16:34:54] [config] input-reorder:
[2026-10-15 16:34:54] [config]   []
[2026-10-15 16:34:54] [config] input-types:
[2026-10-15 16:34:54] [config]   []
[2026-10-15 16:34:54] [config] interpolate-env-vars: false
[2026-10-15 16:34:54] [config] layer-normalization: false
[2026-10-15 16:34:54] [config] lemma-dependency: ""
[2026-10-15 16:34:54] [config] lemma-dim-emb: 0
[2026-10-15 16:34:54] [config] log: ""
[2026-10-15 16:34:54] [config] log-level: info
[2026-10-15 16:34:54] [config] log-time-zone: ""
[2026-10-15 16:34:54] [config] max-length: 1000
[2026-10-15 16:34:54] [config] max-length-crop: false
[2026-10-15 16:34:54] [config] max-length-factor: 3
[2026-10-15 16:34:54] [config] maxi-batch: 1
[2026-10-15 16:34:54] [config] maxi-batch-sort: none
[2026-10-15 16:34:54] [config] mini-batch: 1
[2026-10-15 16:34:54] [config] mini-batch-words: 0
[2026-10-15 16:34:54] [config] model-mmap: false
[2026-10-15 16:34:54] [config] models:
[2026-10-15 16:34:54] [config]   - /kaggle/working/models/transformer/my-hi.npz
[2026-10-15 16:34:54] [config]   - /kaggle/working/models/seq2seq/my-hi-rnn.npz
[2026-10-15 16:34:54] [config] n-best: false
[2026-10-15 16:34:54] [config] no-spm-decode: false
[2026-10-15 16:34:54] [config] no-spm-encode: false
[2026-10-15 16:34:54] [config] normalize: 1
[2026-10-15 16:34:54] [config] optimize: false
[2026-10-15 16:34:54] [config] output: stdout
[2026-10-15 16:34:54] [config] output-approx-knn:
[2026-10-15 16:34:54] [config]   []
[2026-10-15 16:34:54] [config] output-omit-bias: false
[2026-10-15 16:34:54] [config] output-sampling:
[2026-10-15 16:34:54] [config]   []
[2026-10-15 16:34:54] [config] precision:
[2026-10-15 16:34:54] [config]   - float32
[2026-10-15 16:34:54] [config] quantize-range: 0
[2026-10-15 16:34:54] [config] quiet: false
[2026-10-15 16:34:54] [config] quiet-translation: false
[2026-10-15 16:34:54] [config] relative-paths: false
[2026-10-15 16:34:54] [config] right-left: false
[2026-10-15 16:34:54] [config] seed: 0
[2026-10-15 16:34:54] [config] separator-symbol: "[eos]"
[2026-10-15 16:34:54] [config] shortlist:
[2026-10-15 16:34:54] [config]   []
[2026-10-15 16:34:54] [config] skip: false
[2026-10-15 16:34:54] [config] skip-cost: false
[2026-10-15 16:34:54] [config] stat-freq: 0
[2026-10-15 16:34:54] [config] tied-embeddings: false
[2026-10-15 16:34:54] [config] tied-embeddings-all: false
[2026-10-15 16:34:54] [config] tied-embeddings-src: false
[2026-10-15 16:34:54] [config] transformer-aan-activation: swish
[2026-10-15 16:34:54] [config] transformer-aan-depth: 2
[2026-10-15 16:34:54] [config] transformer-aan-nogate: false
[2026-10-15 16:34:54] [config] transformer-alibi-shift: false
[2026-10-15 16:34:54] [config] transformer-alibi-trainable: false
[2026-10-15 16:34:54] [config] transformer-attention-mask: default
[2026-10-15 16:34:54] [config] transformer-decoder-autoreg: self-attention
[2026-10-15 16:34:54] [config] transformer-decoder-dim-ffn: 0
[2026-10-15 16:34:54] [config] transformer-decoder-ffn-depth: 0
[2026-10-15 16:34:54] [config] transformer-depth-scaling: false
[2026-10-15 16:34:54] [config] transformer-dim-aan: 2048
[2026-10-15 16:34:54] [config] transformer-dim-ffn: 2048
[2026-10-15 16:34:54] [config] transformer-disable-position-embeddings: false
[2026-10-15 16:34:54] [config] transformer-ffn-activation: swish
[2026-10-15 16:34:54] [config] transformer-ffn-depth: 2
[2026-10-15 16:34:54] [config] transformer-guided-alignment-layer: last
[2026-10-15 16:34:54] [config] transformer-heads: 4
[2026-10-15 16:34:54] [config] transformer-no-affine: false
[2026-10-15 16:34:54] [config] transformer-no-bias: false
[2026-10-15 16:34:54] [config] transformer-no-projection: false
[2026-10-15 16:34:54] [config] transformer-pool: false
[2026-10-15 16:34:54] [config] transformer-postprocess: dan
[2026-10-15 16:34:54] [config] transformer-postprocess-emb: d
[2026-10-15 16:34:54] [config] transformer-postprocess-top: ""
[2026-10-15 16:34:54] [config] transformer-preprocess: ""
[2026-10-15 16:34:54] [config] transformer-rnn-projection: false
[2026-10-15 16:34:54] [config] transformer-tied-layers:
[2026-10-15 16:34:54] [config]   []
[2026-10-15 16:34:54] [config] transformer-train-position-embeddings: false
[2026-10-15 16:34:54] [config] tsv: false
[2026-10-15 16:34:54] [config] tsv-fields: 0
[2026-10-15 16:34:54] [config] type: transformer
[2026-10-15 16:34:54] [config] ulr: false
[2026-10-15 16:34:54] [config] ulr-dim-emb: 0
[2026-10-15 16:34:54] [config] ulr-trainable-transformation: false
[2026-10-15 16:34:54] [config] version: v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:34:54] [config] vocabs:
[2026-10-15 16:34:54] [config]   - /kaggle/working/data/my.vocab.yml
[2026-10-15 16:34:54] [config]   - /kaggle/working/data/hi.vocab.yml
[2026-10-15 16:34:54] [config] weights:
[2026-10-15 16:34:54] [config]   - 0.6
[2026-10-15 16:34:54] [config]   - 0.4
[2026-10-15 16:34:54] [config] word-penalty: 0
[2026-10-15 16:34:54] [config] word-scores: false
[2026-10-15 16:34:54] [config] workspace: 512
[2026-10-15 16:34:54] [config] Loaded model has been created with Marian v1.12.43 c9f287db 2025-06-23 19:47:45 +0000
[2026-10-15 16:34:54] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/my.vocab.yml
[2026-10-15 16:34:54] [data] Loading vocabulary from JSON/Yaml file /kaggle/working/data/hi.vocab.yml
[2026-10-15 16:34:54] Loading model from /kaggle/working/models/transformer/my-hi.npz
[2026-10-15 16:34:54] Loading model from /kaggle/working/models/seq2seq/my-hi-rnn.npz
[2026-10-15 16:34:54] [memory] Extending reserved space to 512 MB (device gpu0)
[2026-10-15 16:34:55] Loaded model config
[2026-10-15 16:34:55] Loading scorer of type transformer as feature F0
[2026-10-15 16:34:55] Loaded model config
[2026-10-15 16:34:55] Loading scorer of type s2s as feature F1
[2026-10-15 16:34:55] [memory] Reserving 288 MB, device gpu0
[2026-10-15 16:34:55] [gpu] 16-bit TensorCores enabled for float32 matrix operations
[2026-10-15 16:34:55] Best translation 0 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓎜𓀀𓈎 ▁𓂋𓐍𓎼𓂝
[2026-10-15 16:34:55] Best translation 1 : ▁𓆑 ▁𓊪𓄿𓇌 ▁𓎜𓀀 ▁𓅲𓀀𓐍𓇌
[2026-10-15 16:34:55] Best translation 2 : ▁𓎜𓀀𓇋𓐍𓇌𓂧 ▁𓈙𓄿𓏏 ▁𓉔𓂝
[2026-10-15 16:34:55] Best translation 3 : ▁𓂨𓀀𓎡𓋴𓂝 ▁𓏭𓋴𓂝𓄿𓈎𓆑𓎼𓂝
[2026-10-15 16:34:55] Best translation 4 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓆑𓈎
[2026-10-15 16:34:55] Best translation 5 : ▁𓊪𓄿𓎼𓂝 ▁𓄿 ▁𓈙𓄿𓅱𓂝 ▁𓈎𓋴𓆑𓄡
[2026-10-15 16:34:55] Best translation 6 : ▁𓆑𓂋𓂋 ▁𓃀𓐍 ▁𓄿𓎛𓂧𓏏𓄿𓂧
[2026-10-15 16:34:55] Best translation 7 : ▁𓊪𓂝 ▁𓆑𓈙 ▁𓅲𓀀𓃀𓃀𓂧
[2026-10-15 16:34:55] Best translation 8 : ▁𓈙𓊪𓂝 ▁𓄿𓂋𓏏𓄿𓂧𓈙 ▁𓏏𓄿𓂋𓈖
[2026-10-15 16:34:55] Best translation 9 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓄿𓂋𓂋 ▁𓆑𓈎
[2026-10-15 16:34:55] Best translation 10 : ▁𓆑𓈙 ▁𓈎𓐍𓉔 ▁𓂨𓀀𓎡𓋴 ▁𓊪𓄿𓎛𓇌
[2026-10-15 16:34:55] Best translation 11 : ▁𓆑𓂋𓂋 ▁𓇋𓂝 ▁𓂋𓄿𓈎𓂝
[2026-10-15 16:34:55] Best translation 12 : ▁𓆑 ▁𓄿𓉔 ▁𓐍𓎛 ▁𓇌𓎡𓈎𓂧 ▁𓎜𓀀𓏏
[2026-10-15 16:34:55] Best translation 13 : ▁𓆑 ▁𓊪𓐍𓄡𓂝 ▁𓎜𓀀𓈎 ▁𓇌𓎡𓉔𓇋
[2026-10-15 16:34:55] Best translation 14 : ▁𓂋𓂝𓈎 ▁𓉔𓂝 ▁𓊪𓂝𓂋𓄡 ▁𓂨𓀀𓎡
[2026-10-15 16:34:55] Best translation 15 : ▁𓆑 ▁𓂋𓆑𓈖𓂝 ▁𓈙𓎡𓋴𓄡𓋴𓆑𓈙𓂝𓈙
[2026-10-15 16:34:55] Best translation 16 : ▁𓈙𓊪𓂝 ▁𓈎𓋴𓆑𓂝𓇌
[2026-10-15 16:34:55] Best translation 17 : ▁𓆑 ▁𓂋𓐍𓎼𓂝 ▁𓇋𓐍𓐍𓈖𓈙
[2026-10-15 16:34:55] Best translation 18 : ▁𓆑 ▁𓏮𓀀𓉔𓄡𓂋𓄿𓆑𓎛 ▁𓄿 ▁𓊪𓎡𓃀
[2026-10-15 16:34:55] Best translation 19 : ▁𓆑 ▁𓈙𓂝𓂝 ▁𓈚𓀀𓉔𓂝𓈎𓊪𓆑𓎛𓃀
[2026-10-15 16:34:55] Best translation 20 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓇋𓆑𓃀
[2026-10-15 16:34:55] Best translation 21 : ▁𓆑 ▁𓊪𓄿𓈎𓂝 ▁𓉔𓆑𓂋𓈖
[2026-10-15 16:34:55] Best translation 22 : ▁𓊪𓂝 ▁𓊪𓄿𓈙 ▁𓄿 ▁𓇌𓐍𓃀
[2026-10-15 16:34:55] Best translation 23 : ▁𓏏𓂝 ▁𓏏𓄿𓎛𓈎 ▁𓄿 ▁𓅱𓄿𓉔𓆑𓂋𓂧
[2026-10-15 16:34:56] Best translation 24 : ▁𓈙𓊪𓂝 ▁𓂋𓐍𓎼𓂝𓈙 ▁𓊪𓆑𓉔
[2026-10-15 16:34:56] Best translation 25 : ▁𓊪𓂝 ▁𓆑𓈙 ▁𓈙𓆑𓏭𓈖
[2026-10-15 16:34:56] Best translation 26 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓐍 ▁𓇌𓆑𓂝
[2026-10-15 16:34:56] Best translation 27 : ▁𓊪𓐍𓏏 ▁𓉔𓎡𓏭𓊪 ▁𓆑𓈙 ▁𓆑𓈎
[2026-10-15 16:34:56] Best translation 28 : ▁𓆑𓈎 ▁𓏏𓄿𓈙 ▁𓎼𓂝𓋴𓂧 ▁𓃀𓐍𓐍𓇌
[2026-10-15 16:34:56] Best translation 29 : ▁𓆑 ▁𓊪𓄿𓎼𓂝 ▁𓄿𓈙𓈖𓂝𓇌 ▁𓈎𓐍𓉔
[2026-10-15 16:34:56] Best translation 30 : ▁𓇌𓐍 ▁𓄿𓈙 ▁𓂨𓀀𓎡 ▁𓏏𓄿𓎛𓈎
[2026-10-15 16:34:56] Best translation 31 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓎜𓀀𓈎 ▁𓂋𓐍𓎼𓂝
[2026-10-15 16:34:56] Best translation 32 : ▁𓏏𓂝 ▁𓄿𓂋𓂋 ▁𓂋𓆑𓂝
[2026-10-15 16:34:56] Best translation 33 : ▁𓂨𓀀𓎡 ▁𓉔𓎡𓈙𓈎 ▁𓇋𓂝 ▁𓈙𓆑𓏭𓈖
[2026-10-15 16:34:56] Best translation 34 : ▁𓆑 ▁𓏭𓄿𓎛𓈎 ▁𓎡𓈙𓂝 ▁𓆑𓈎
[2026-10-15 16:34:56] Best translation 35 : ▁𓏏𓄿𓂋𓈖 ▁𓈙𓂋𓐍𓏏𓂋𓂧
[2026-10-15 16:34:56] Best translation 36 : ▁𓆑𓈎𓈙 ▁𓈙𓈎𓆑𓂋𓂋 ▁𓇌𓄿𓋴𓈖
[2026-10-15 16:34:56] Best translation 37 : ▁𓏭𓊪𓐍𓐍𓈙𓂝 ▁𓐍𓎛𓂝
[2026-10-15 16:34:56] Best translation 38 : ▁𓆑 ▁𓈙𓎡𓄡𓄡𓐍𓋴𓈎 ▁𓊪𓆑𓉔
[2026-10-15 16:34:56] Best translation 39 : ▁𓏏𓊪𓂝𓋴𓂝 ▁𓄿𓋴𓂝 ▁𓈎𓊪𓂝𓂧
[2026-10-15 16:34:56] Best translation 40 : ▁𓏏𓂝 ▁𓏏𓂝𓋴𓂝𓎛𓈎 ▁𓂋𓎡𓏭𓈖𓂧
[2026-10-15 16:34:56] Best translation 41 : ▁𓂨𓀀𓎡𓋴𓂝 ▁𓎛𓆑𓏭𓂝
[2026-10-15 16:34:56] Best translation 42 : ▁𓆑𓉔 ▁𓃀𓎡𓂋𓂋 𓆑𓇋𓂋𓂝
[2026-10-15 16:34:56] Best translation 43 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓄿𓏏𓂝𓈚𓀀𓉔𓂝
[2026-10-15 16:34:56] Best translation 44 : ▁𓉔𓂝𓎛 ▁𓄿𓋴𓂝 ▁𓈙𓆑𓉔𓄡𓂋𓂝
[2026-10-15 16:34:56] Best translation 45 : ▁𓏏𓂝 ▁𓏏𓂝𓎛𓈎 ▁𓎡𓄡
[2026-10-15 16:34:56] Best translation 46 : ▁𓊪𓂝 ▁𓆑𓈙 ▁𓅓𓎡𓈙𓈎 ▁𓄿 ▁𓈖𓆑𓇌
[2026-10-15 16:34:56] Best translation 47 : ▁𓆑 ▁𓂋𓐍𓎼𓂝 ▁𓈎𓐍𓉔
[2026-10-15 16:34:56] Best translation 48 : ▁𓊪𓂝 ▁𓅓𓎡𓈙𓈎 ▁𓏭𓄿𓉔𓂝 ▁𓐍𓎡𓈎
[2026-10-15 16:34:56] Best translation 49 : ▁𓆑 ▁𓋴𓂝𓃀𓋴𓂝 𓈎 ▁𓎜𓀀𓈎𓊪𓆑𓎛𓃀
[2026-10-15 16:34:56] Best translation 50 : ▁𓊪𓂝 ▁𓏭𓄿𓉔𓂝 ▁𓈎𓐍 ▁𓋴𓎡𓎛
[2026-10-15 16:34:56] Best translation 51 : ▁𓆑𓉔 ▁𓄿𓇋𓐍𓎡𓈎 ▁𓋴𓂝𓄿𓇌𓂧
[2026-10-15 16:34:56] Best translation 52 : ▁𓆑 ▁𓅲𓀀𓂋𓂋𓐍𓏏 ▁𓊪𓆑𓉔
[2026-10-15 16:34:56] Best translation 53 : ▁𓏏𓂝𓋴𓂝 ▁𓄿𓂋𓂋 ▁𓎡𓎛 𓆑𓊃𓎡𓂝
[2026-10-15 16:34:56] Best translation 54 : ▁𓏏𓂝 ▁𓊪𓄿𓎼𓂝 ▁𓆑𓎛 𓅓𓎡𓋴𓆑𓂝𓈙
[2026-10-15 16:34:56] Best translation 55 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓊪𓐍𓉔𓂝
[2026-10-15 16:34:56] Best translation 56 : ▁𓇌𓐍 ▁𓄿𓈙 ▁𓆑 ▁𓈎𓐍𓂋𓇌 ▁𓂨𓀀𓎡
[2026-10-15 16:34:56] Best translation 57 : ▁𓄿𓂋𓂋 ▁𓆑𓈙 ▁𓏏𓂝𓂋𓂋
[2026-10-15 16:34:56] Best translation 58 : ▁𓇌𓐍𓎛𓈎 ▁𓂋𓆑𓈖𓂝 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:34:56] Best translation 59 : ▁𓈎𓐍𓉔 ▁𓆑𓈙 ▁𓏭𓋴𓎡𓂝𓂋
[2026-10-15 16:34:56] Best translation 60 : ▁𓆑 ▁𓂋𓆑𓈖𓂝 ▁𓄡𓎡𓆓𓆓 𓂋𓂝𓈙
[2026-10-15 16:34:56] Best translation 61 : ▁𓊪𓂝 ▁𓏭𓄿𓎛 ▁𓇌𓋴𓆑𓎼𓂝
[2026-10-15 16:34:56] Best translation 62 : ▁𓏏𓊪𓄿𓈎𓎼𓂝 ▁𓂨𓀀𓎡 ▁𓃀𓐍𓈎
[2026-10-15 16:34:56] Best translation 63 : ▁𓆑 ▁𓇌𓋴𓄿𓎛𓈖 ▁𓈎𓊪𓂝 ▁𓏏𓆑𓎛𓂝
[2026-10-15 16:34:56] Best translation 64 : ▁𓏭𓄿𓎛 ▁𓏏𓂝 ▁𓈎𓋴𓂧
[2026-10-15 16:34:56] Best translation 65 : ▁𓆑𓂋𓂋 ▁𓃀𓂝𓈎 ▁𓆑𓏭𓂝
[2026-10-15 16:34:56] Best translation 66 : ▁𓆑𓉔 ▁𓋴𓂝𓄿𓇌𓂧 ▁𓈎𓐍 ▁𓃀𓐍
[2026-10-15 16:34:56] Best translation 67 : ▁𓆑𓈎𓈙 ▁𓎜𓀀𓈎 ▁𓄿 ▁𓅱𓄿𓉔𓆑𓂋𓂧
[2026-10-15 16:34:56] Best translation 68 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓄿 ▁𓈙𓆑𓎛𓃀𓂝𓋴
[2026-10-15 16:34:56] Best translation 69 : ▁𓆑𓉔 ▁𓄿 ▁𓇋𓄿𓎛𓈖 ▁𓏭𓂋𓂝𓋴𓈖
[2026-10-15 16:34:56] Best translation 70 : ▁𓊪𓐍𓏏 ▁𓇌𓐍 ▁𓂨𓀀𓎡 ▁𓇌𓐍 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:34:56] Best translation 71 : ▁𓆑𓈎𓈙 ▁𓄿 ▁𓃀𓐍𓐍𓇌 ▁𓇌𓄿𓂧
[2026-10-15 16:34:56] Best translation 72 : ▁𓎜𓀀 ▁𓐍𓎛𓂝 ▁𓏭𓄿𓋴𓂝𓇌
[2026-10-15 16:34:56] Best translation 73 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓊪𓂝 ▁𓅱𓄿𓎛
[2026-10-15 16:34:56] Best translation 74 : ▁𓆑 ▁𓏏𓆑𓂋𓂋 ▁𓋴𓂝𓈙𓏭𓊪𓂝𓇌𓎡𓂋𓂝
[2026-10-15 16:34:56] Best translation 75 : ▁𓄿𓉔 ▁𓆑 ▁𓅱𓆑𓋴𓂝𓇌
[2026-10-15 16:34:56] Best translation 76 : ▁𓆑𓈎𓈙 ▁𓎼𓂝𓋴𓂧 ▁𓇌𓋴𓂧
[2026-10-15 16:34:56] Best translation 77 : ▁𓄿𓋴𓂝 ▁𓏏𓂝 ▁𓋴𓂝𓄿𓇌𓂧
[2026-10-15 16:34:56] Best translation 78 : ▁𓈎𓐍𓉔 ▁𓄿𓈎𓂝 ▁𓊃𓎡𓆑𓏭𓈖𓂋𓂧
[2026-10-15 16:34:56] Best translation 79 : ▁𓆑 ▁𓊪𓄿𓎼𓂝 ▁𓈙𓈎𓄿𓎛𓇌 𓄿𓋴𓇌𓈙
[2026-10-15 16:34:56] Best translation 80 : ▁𓊪𓂝 ▁𓇌𓋴𓐍𓄡𓄡𓂝𓇌 ▁𓆑𓈎
[2026-10-15 16:34:56] Best translation 81 : ▁𓂋𓂝𓈎 ▁𓉔𓂝 ▁𓐍𓎛 ▁𓉔𓂝
[2026-10-15 16:34:57] Best translation 82 : ▁𓆑 ▁𓐍𓏏𓂝 ▁𓂨𓀀𓎡 ▁𓄿 ▁𓂋𓐍𓈎
[2026-10-15 16:34:57] Best translation 83 : ▁𓈎𓐍𓉔𓈙 ▁𓄿𓎛𓃀𓋴𓂧
[2026-10-15 16:34:57] Best translation 84 : ▁𓆑 ▁𓄿𓃀𓋴𓂝𓂝 ▁𓏏𓆑𓈎𓊪 ▁𓂨𓀀𓎡
[2026-10-15 16:34:57] Best translation 85 : ▁𓊪𓂝 ▁𓏭𓄿𓎛 ▁𓈙𓏏𓆑𓉔 ▁𓅱𓄿𓈙𓈎
[2026-10-15 16:34:57] Best translation 86 : ▁𓏭𓎡𓈎 ▁𓈎𓊪𓂝 ▁𓄡𓐍𓏏𓂝𓋴
[2026-10-15 16:34:57] Best translation 87 : ▁𓇌𓆑𓇌 ▁𓂨𓀀𓎡 ▁𓇌𓐍 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:34:57] Best translation 88 : ▁𓏮𓀀𓉔𓂝 ▁𓆑𓉔𓉔𓂝𓇌 𓆑𓄿𓈎𓂝𓂋𓂧
[2026-10-15 16:34:57] Best translation 89 : ▁𓊪𓂝 ▁𓊪𓄿𓈙 ▁𓄿 ▁𓇋𓐍𓐍𓈖
[2026-10-15 16:34:57] Best translation 90 : ▁𓆑𓈙 ▁𓆑𓈎 ▁𓏭𓂋𓂝𓄿𓋴
[2026-10-15 16:34:57] Best translation 91 : ▁𓊪𓂝 ▁𓏭𓋴𓄿 𓏭𓈖𓂝𓇌 ▁𓎡𓄡
[2026-10-15 16:34:57] Best translation 92 : ▁𓆑𓈎𓈙 ▁𓆑𓉔𓄡𓋴𓐍 𓇋𓄿𓇋𓂋𓂝
[2026-10-15 16:34:57] Best translation 93 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓅱𓆑𓎛𓆑𓈙𓊪𓂝𓇌
[2026-10-15 16:34:57] Best translation 94 : ▁𓂋𓂝𓈎 ▁𓉔𓂝 ▁𓇌𓐍 ▁𓄿𓎛𓂧𓈎𓊪𓆑𓎛𓃀
[2026-10-15 16:34:57] Best translation 95 : ▁𓏏𓂝𓋴𓂝 ▁𓈎𓊪𓂝 ▁𓇋𓂝𓈙𓈎
[2026-10-15 16:34:57] Best translation 96 : ▁𓆑 ▁𓊪𓄿𓇌 ▁𓈎𓐍 ▁𓏏𓐍𓋴𓈖
[2026-10-15 16:34:57] Best translation 97 : ▁𓏏𓂝 ▁𓄿𓂋𓂋 ▁𓈙𓎡𓅱𓅱𓂝 𓋴𓂝𓇌
[2026-10-15 16:34:57] Best translation 98 : ▁𓆑𓉔 ▁𓇌𓆑𓂝𓈎𓆑𓎛𓃀
[2026-10-15 16:34:57] Best translation 99 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓎜𓀀 ▁𓅱𓎡𓎛
[2026-10-15 16:34:57] Best translation 100 : ▁𓆑 ▁𓂋𓂝𓈎 ▁𓂨𓀀𓎡 ▁𓇌𓐍𓏏𓎛
[2026-10-15 16:34:57] Best translation 101 : ▁𓈎𓐍𓉔 ▁𓂋𓆑𓈖𓂝𓈙 ▁𓐍𓄡𓂝𓋴𓄿
[2026-10-15 16:34:57] Best translation 102 : ▁𓏏𓆑𓂋𓂋 ▁𓂨𓀀𓎡 ▁𓈖𓆑𓂋𓂋 ▁𓉔𓂝
[2026-10-15 16:34:57] Best translation 103 : ▁𓏮𓀀𓉔𓂝 ▁𓅓𓐍𓆑𓎛 ▁𓎡𓈙
[2026-10-15 16:34:57] Best translation 104 : ▁𓈎𓐍𓉔 ▁𓆑𓈙 ▁𓄿 ▁𓃀𓎡𓂝𓈙𓈎
[2026-10-15 16:34:57] Best translation 105 : ▁𓏭𓄿𓎛 ▁𓂨𓀀𓎡 ▁𓏮𓀀𓉔𓂝
[2026-10-15 16:34:57] Best translation 106 : ▁𓆑 ▁𓊪𓄿𓎼𓂝 ▁𓉔𓐍𓋴𓂝 𓂝𓋴
[2026-10-15 16:34:57] Best translation 107 : ▁𓈎𓊪𓆑𓈙 ▁𓆑𓈙 ▁𓄿 ▁𓂋𓆒𓀀𓎛
[2026-10-15 16:34:57] Best translation 108 : ▁𓏏𓂝 ▁𓎛𓂝𓂝𓇌 ▁𓊪𓂝𓂋𓄡
[2026-10-15 16:34:57] Best translation 109 : ▁𓊪𓂝 ▁𓂋𓐍𓎼𓂝𓈙 ▁𓋴𓎡𓎛𓎛𓆑𓎛𓃀
[2026-10-15 16:34:57] Best translation 110 : ▁𓆑 ▁𓈖𓎜𓀀𓏏 ▁𓈎𓊪𓂝 ▁𓇋𓐍𓂧
[2026-10-15 16:34:57] Best translation 111 : ▁𓈎𓊪𓆑𓈙 ▁𓇌𓐍𓃀 ▁𓆑𓈙 ▁𓉔𓆑𓎛𓂝
[2026-10-15 16:34:57] Best translation 112 : ▁𓈎𓊪𓂝 ▁𓇋𓎡𓈙 ▁𓆑𓈙 ▁𓅱𓎡𓂋𓂋
[2026-10-15 16:34:57] Best translation 113 : ▁𓆑𓈎𓈙 ▁𓄿𓂋𓂋 ▁𓈎𓆑𓉔𓂝
[2026-10-15 16:34:57] Best translation 114 : ▁𓆑 ▁𓄿𓉔 ▁𓄿𓈎 ▁𓈙𓆑𓍿
[2026-10-15 16:34:57] Best translation 115 : ▁𓆑𓈙𓎛𓈎 ▁𓈎𓊪𓄿𓈎 ▁𓋴𓆑𓃀𓊪𓈎
[2026-10-15 16:34:57] Best translation 116 : ▁𓏭𓄿𓎛 ▁𓏏𓂝 ▁𓂝𓄿𓈎 ▁𓂧𓂝𓈎
[2026-10-15 16:34:57] Best translation 117 : ▁𓂨𓀀𓎡 ▁𓈚𓀀𓎡𓎛𓇌 ▁𓈎𓆑𓋴𓂝𓇌
[2026-10-15 16:34:57] Best translation 118 : ▁𓈎𓊪𓂝 ▁𓄡𓄿𓆑𓎛 ▁𓆑𓈙 ▁𓂝𓄿𓈙𓂧
[2026-10-15 16:34:57] Best translation 119 : ▁𓏏𓂝𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓊪𓄿𓄡𓄡𓂧
[2026-10-15 16:34:57] Best translation 120 : ▁𓆑 ▁𓏏𓄿𓎛𓈎 ▁𓈎𓐍 ▁𓈙𓈎𓄿𓂧
[2026-10-15 16:34:57] Best translation 121 : ▁𓈚𓀀𓋴𓋴𓂧 ▁𓈎𓐍 ▁𓇋𓂝 ▁𓂋𓄿𓈎𓂝
[2026-10-15 16:34:57] Best translation 122 : ▁𓈎𓐍𓉔 ▁𓏏𓄿𓎛𓈎𓂝𓇌 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:34:57] Best translation 123 : ▁𓈙𓊪𓐍𓎡𓂋𓇌 ▁𓆑 ▁𓃀𓐍
[2026-10-15 16:34:57] Best translation 124 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓄿𓂋𓂋 ▁𓄿𓂋𓐍𓎛𓂝
[2026-10-15 16:34:57] Best translation 125 : ▁𓆑 ▁𓊪𓄿𓇌 ▁𓉔𓂧 ▁𓇌𓐍𓎡𓇋𓈎𓈙
[2026-10-15 16:34:57] Best translation 126 : ▁𓆑 ▁𓉔𓄿𓇌𓂝 ▁𓈎𓊪𓂝 ▁𓇋𓂝𓈎
[2026-10-15 16:34:57] Best translation 127 : ▁𓄿𓋴𓂝 ▁𓂨𓀀𓎡 ▁𓄿𓂋𓂋 ▁𓊪𓄿𓄡𓄡𓂧
[2026-10-15 16:34:57] Best translation 128 : ▁𓆑 ▁𓉔𓄿𓇌𓂝 ▁𓄿 ▁𓂋𓐍𓈎
[2026-10-15 16:34:57] Best translation 129 : ▁𓂨𓀀𓎡 ▁𓂋𓐍𓐍𓈖 ▁𓃀𓋴𓂝𓄿𓈎
[2026-10-15 16:34:57] Best translation 130 : ▁𓆑 ▁𓊪𓎡𓋴𓈎 ▁𓉔𓂧 ▁𓅲𓀀𓐍𓈎
[2026-10-15 16:34:57] Best translation 131 : ▁𓏏𓂝 ▁𓎛𓂝𓂝𓇌 ▁𓄿 ▁𓏭𓄿𓇋
[2026-10-15 16:34:57] Best translation 132 : ▁𓈎𓐍𓉔 ▁𓏏𓄿𓈙 ▁𓈙𓈖𓂝𓄡𓈎 𓆑𓏭𓄿𓂋
[2026-10-15 16:34:57] Best translation 133 : ▁𓆑 ▁𓐍𓏏𓂝 ▁𓂨𓀀𓎡 ▁𓄿 ▁𓇋𓂝𓂝𓋴
[2026-10-15 16:34:57] Best translation 134 : ▁𓆑𓉔 ▁𓊪𓎡𓎛𓃀 ▁𓐍𓎼𓂝𓋴
[2026-10-15 16:34:57] Best translation 135 : ▁𓏮𓀀𓉔𓂝 ▁𓅓𓐍𓆑𓎛 ▁𓎡𓈙
[2026-10-15 16:34:57] Best translation 136 : ▁𓆑𓉔 ▁𓇌𓂝𓂋𓆑𓃀𓊪𓈎𓂝𓇌
[2026-10-15 16:34:57] Best translation 137 : ▁𓇌𓐍 ▁𓂨𓀀𓎡 ▁𓊪𓄿𓎼𓂝 ▁𓈖𓆑𓇌𓈙
[2026-10-15 16:34:57] Best translation 138 : ▁𓏏𓂝 ▁𓏏𓆑𓈙𓊪 ▁𓂨𓀀𓎡 ▁𓂋𓎡𓏭𓈖
[2026-10-15 16:34:58] Best translation 139 : ▁𓇌𓐍𓎛𓈎 ▁𓈎𓄿𓂋𓈖 ▁𓈎𓐍 ▁𓉔𓂝
[2026-10-15 16:34:58] Best translation 140 : ▁𓆑 ▁𓏏𓐍𓈖𓂝 ▁𓎡𓄡
[2026-10-15 16:34:58] Best translation 141 : ▁𓇌𓆑𓇌 ▁𓂨𓀀𓎡 ▁𓇌𓐍 ▁𓈎𓊪𓄿𓈎
[2026-10-15 16:34:58] Best translation 142 : ▁𓂨𓀀𓎡 ▁𓉔𓎡𓈙𓈎 ▁𓋴𓂝𓈙𓈎
[2026-10-15 16:34:58] Best translation 143 : ▁𓆑𓂋𓂋 ▁𓃀𓐍 ▁𓈎𓊪𓆑𓈙 ▁𓏏𓄿𓂧
[2026-10-15 16:34:58] Best translation 144 : ▁𓊪𓂝𓈙 ▁𓎜𓀀𓈎 ▁𓆑𓎛 ▁𓂧𓂝𓈎
[2026-10-15 16:34:58] Best translation 145 : ▁𓆑 ▁𓏮𓀀𓎡𓂋𓇌𓎛𓈎 ▁𓈙𓈎𓐍𓄡
[2026-10-15 16:34:58] Best translation 146 : ▁𓈎𓐍𓉔𓈙 ▁𓈙𓄿𓅱𓂝
[2026-10-15 16:34:58] Best translation 147 : ▁𓊪𓂝 ▁𓊪𓄿𓇌 ▁𓅓𓂝𓄿𓎛𓈙 ▁𓐍𓎛
[2026-10-15 16:34:58] Best translation 148 : ▁𓎜𓀀 ▁𓐍𓎛𓂝 ▁𓏭𓊪𓂝𓄿𓈎𓂝𓇌
[2026-10-15 16:34:58] Best translation 149 : ▁𓆑 ▁𓏭𓋴𓂧 ▁𓂝𓎼𓂝𓋴𓂧 ▁𓇌𓄿𓂧
[2026-10-15 16:34:58] Best translation 150 : ▁𓆑 ▁𓋴𓄿𓎛 ▁𓊪𓐍𓉔𓂝
[2026-10-15 16:34:58] Best translation 151 : ▁𓇌𓐍𓂝𓈙 ▁𓊪𓂝 ▁𓂋𓆑𓎼𓂝 ▁𓊪𓂝𓋴𓂝
[2026-10-15 16:34:58] Best translation 152 : ▁𓇌𓆑𓇌 ▁𓂨𓀀𓎡 ▁𓈙𓂝𓂝 ▁𓆑𓈎
[2026-10-15 16:34:58] Best translation 153 : ▁𓆑𓉔 ▁𓋴𓄿𓈎𓊪𓂝𓋴 ▁𓈙𓊪𓂧
[2026-10-15 16:34:58] Best translation 154 : ▁𓏏𓂝 ▁𓈙𓊪𓐍𓎡𓂋𓇌 ▁𓏏𓄿𓆑𓈎
[2026-10-15 16:34:58] Best translation 155 : ▁𓆑 ▁𓏏𓐍𓎡𓂋𓇌 ▁𓏭𓄿𓋴𓂝
[2026-10-15 16:34:58] Best translation 156 : ▁𓆑𓈎𓈙 ▁𓐍𓎛𓂋𓂧 ▁𓉔𓐍𓎛𓂝𓂧
[2026-10-15 16:34:58] Best translation 157 : ▁𓆑𓉔 ▁𓅱𓎡𓋴𓆒𓀀𓎡𓈙
[2026-10-15 16:34:58] Best translation 158 : ▁𓆑𓉔 ▁𓇋𓎡𓈙𓂧
[2026-10-15 16:34:58] Best translation 159 : ▁𓈎𓐍𓉔 ▁𓈖𓎜𓀀𓏏 ▁𓈎𓐍𓉔
[2026-10-15 16:34:58] Best translation 160 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓂝𓎼𓆑𓂋
[2026-10-15 16:34:58] Best translation 161 : ▁𓊪𓐍𓏏 ▁𓄿𓇋𓐍𓎡𓈎 ▁𓄿 ▁𓇌𓋴𓆑𓎛𓈖
[2026-10-15 16:34:58] Best translation 162 : ▁𓈎𓊪𓄿𓈎𓈙 ▁𓄡𓂝𓏭𓎡𓂋 𓆑𓄿𓋴
[2026-10-15 16:34:58] Best translation 163 : ▁𓆑𓉔 ▁𓇋𓄿𓏭𓈖
[2026-10-15 16:34:58] Best translation 164 : ▁𓆑𓉔 ▁𓉔𓂧 ▁𓄡𓄿𓋴𓈎𓎛𓂝𓋴
[2026-10-15 16:34:58] Best translation 165 : ▁𓆑 ▁𓇌𓆑𓇌𓎛𓈎 ▁𓅱𓂋𓎡𓎛𓈖
[2026-10-15 16:34:58] Best translation 166 : ▁𓆑𓂋𓂋 ▁𓈎𓋴𓂧 ▁𓄿𓃀𓄿𓆑𓎛
[2026-10-15 16:34:58] Best translation 167 : ▁𓆑𓉔 ▁𓎜𓀀𓈎 ▁𓋴𓆑𓏭𓊪
[2026-10-15 16:34:58] Best translation 168 : ▁𓏏𓂝 ▁𓄿𓄡𓐍𓂋𓐍𓃀𓆑𓆓𓂝
[2026-10-15 16:34:58] Best translation 169 : ▁𓂝𓎼𓂝𓋴𓂧𓇋𓐍𓇌𓂧𓈙 ▁𓊪𓄿𓄡𓄡𓂧
[2026-10-15 16:34:58] Best translation 170 : ▁𓊪𓂝𓈙 ▁𓄿 ▁𓃀𓂝𓎛𓈎𓂋𓂝 𓉔𓄿𓎛
[2026-10-15 16:34:58] Best translation 171 : ▁𓈎𓐍𓉔 ▁𓈙𓂝𓂝𓉔𓈙 ▁𓄿𓎛𓃀𓋴𓂧
[2026-10-15 16:34:58] Best translation 172 : ▁𓊪𓂝 ▁𓏭𓄿𓎛𓈎 ▁𓏮𓀀𓎡𓎛𓈎

In [34]:
import sentencepiece as spm

my_spm = spm.SentencePieceProcessor(model_file="my_spm.model")
hi_spm = spm.SentencePieceProcessor(model_file="hi_spm.model")

with open(
    "/kaggle/working/output/ensemble/test.output.my.ensemble.spm", "r", encoding="utf-8"
) as f_in, open("/kaggle/working/output/ensemble/test.output.my", "w", encoding="utf-8") as f_out:
  for line in f_in:
    pieces = line.strip().split()
    decoded_text = my_spm.decode(pieces)
    f_out.write(decoded_text + "\n")

with open(
    "/kaggle/working/output/ensemble/test.output.hi.ensemble.spm", "r", encoding="utf-8"
) as f_in, open("/kaggle/working/output/ensemble/test.output.hi", "w", encoding="utf-8") as f_out:
  for line in f_in:
    pieces = line.strip().split()
    decoded_text = hi_spm.decode(pieces)
    f_out.write(decoded_text + "\n")

print("Test set successfully detokenized!")

Test set successfully detokenized!

In [36]:
print("----Scoring Burmese -> Hieroglyph Ensemble Model----")
!sacrebleu /kaggle/working/data/test.my -i /kaggle/working/output/ensemble/test.output.my

print("----Scoring Hieroglyph -> Burmese Ensemble Model----")
!sacrebleu /kaggle/working/data/test.hi -i /kaggle/working/output/ensemble/test.output.hi

----Scoring Burmese -> Hieroglyph Ensemble Model----
{
 "name": "BLEU",
 "score": 19.1,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.6.0",
 "verbose_score": "32.0/15.7/11.4/23.1 (BP = 1.000 ratio = 1.044 hyp_len = 998 ref_len = 956)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.6.0"
}
----Scoring Hieroglyph -> Burmese Ensemble Model----
{
 "name": "BLEU",
 "score": 17.2,
 "signature": "nrefs:1|case:mixed|eff:no|tok:13a|smooth:exp|version:2.6.0",
 "verbose_score": "45.4/21.8/11.3/7.8 (BP = 1.000 ratio = 1.041 hyp_len = 1638 ref_len = 1573)",
 "nrefs": "1",
 "case": "mixed",
 "eff": "no",
 "tok": "13a",
 "smooth": "exp",
 "version": "2.6.0"
}

In [37]:
import pandas as pd

# Define paths to your test dataset files
src_file = "/kaggle/working/data/test.my"
ref_file = "/kaggle/working/data/test.hi"
pred_file = "/kaggle/working/output/ensemble/test.output.hi"

# Read lines from all three files
with open(src_file, "r", encoding="utf-8") as f_src, open(
    ref_file, "r", encoding="utf-8"
) as f_ref, open(pred_file, "r", encoding="utf-8") as f_pred:
  src_lines = [line.strip() for line in f_src]
  ref_lines = [line.strip() for line in f_ref]
  pred_lines = [line.strip() for line in f_pred]

# Select 10 sample indices to inspect
sample_indices = [0, 1, 2, 5, 10, 20, 40, 80, 160, 320]

samples = []
for idx in sample_indices:
  if idx < len(src_lines):
    samples.append({
        "Index": idx,
        "Source (Burmese)": src_lines[idx],
        "Reference (Hieroglyphs)": ref_lines[idx],
        "Prediction (Hieroglyphs)": pred_lines[idx],
    })

# Format as a clean Pandas DataFrame for easy viewing
df_samples = pd.DataFrame(samples)
pd.set_option("display.max_colwidth", None)
display(df_samples)

,Index,Source (Burmese),Reference (Hieroglyphs),Prediction (Hieroglyphs)
0,0,အချစ်က နာကျင်စေတယ်။,𓂋𓐍𓎼𓂝 𓊪𓎡𓋴𓈎𓈙,𓈎𓊪𓆑𓈙 𓆑𓈙 𓎜𓀀𓈎 𓂋𓐍𓎼𓂝
1,1,ကျွန်မမှာ အစားအစာမရှိဘူး။,𓆑 𓊪𓄿𓎼𓂝 𓎜𓀀 𓅲𓀀𓐍𓇌,𓆑 𓊪𓄿𓇌 𓎜𓀀 𓅲𓀀𓐍𓇌
2,2,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။,𓎜𓀀 𓐍𓎛𓂝 𓈙𓄿𓏏 𓉔𓂝,𓎜𓀀𓇋𓐍𓇌𓂧 𓈙𓄿𓏏 𓉔𓂝
3,5,ခရီးကောင်းပါ,𓊪𓄿𓎼𓂝 𓄿 𓎛𓆑𓏭𓂝 𓈎𓋴𓆑𓄡,𓊪𓄿𓎼𓂝 𓄿 𓈙𓄿𓅱𓂝 𓈎𓋴𓆑𓄡
4,10,နင့်နံ့က ကောင်းတယ်,𓂨𓀀𓎡 𓈙𓉔𓂝𓂋𓂋 𓃀𓐍𓐍𓇌,𓆑𓈙 𓈎𓐍𓉔 𓂨𓀀𓎡𓋴 𓊪𓄿𓎛𓇌
5,20,ဒါက ကြီးမားပါတယ်။,𓈎𓊪𓆑𓈙 𓆑𓈙 𓊪𓎡𓃀𓂝,𓈎𓊪𓆑𓈙 𓆑𓈙 𓇋𓆑𓃀
6,40,ကံမကောင်းခဲ့ဘူး။,𓆑𓈎 𓏏𓄿𓈙𓎛𓈎 𓂋𓎡𓏭𓈖,𓏏𓂝 𓏏𓂝𓋴𓂝𓎛𓈎 𓂋𓎡𓏭𓈖𓂧
7,80,သူတွေ့တယ်။,𓊪𓂝 𓅲𓀀𓎡𓎛𓇌 𓆑𓈎,𓊪𓂝 𓇌𓋴𓐍𓄡𓄡𓂝𓇌 𓆑𓈎
8,160,ပိုဆိုးလာတယ်,𓆑𓈎 𓃀𓂝𓈎𓈙 𓏏𓐍𓋴𓈙𓂝,𓆑𓉔 𓎜𓀀𓈎 𓂝𓎼𓆑𓂋
9,320,ကျွန်တော် အလုပ်ကြိုးစားတယ်။,𓆑𓂋𓂋 𓏏𓐍𓋴𓈖 𓊪𓄿𓋴𓇌,𓆑𓉔 𓊪𓄿𓋴𓇌𓏏𓐍𓋴𓈖𓆑𓎛𓃀

In [38]:
import pandas as pd

# Define paths to your test dataset files
src_file = "/kaggle/working/data/test.hi"
ref_file = "/kaggle/working/data/test.my"
pred_file = "/kaggle/working/output/ensemble/test.output.my"

# Read lines from all three files
with open(src_file, "r", encoding="utf-8") as f_src, open(
    ref_file, "r", encoding="utf-8"
) as f_ref, open(pred_file, "r", encoding="utf-8") as f_pred:
  src_lines = [line.strip() for line in f_src]
  ref_lines = [line.strip() for line in f_ref]
  pred_lines = [line.strip() for line in f_pred]

# Select 10 sample indices to inspect
sample_indices = [0, 1, 2, 5, 10, 20, 40, 80, 160, 320]

samples = []
for idx in sample_indices:
  if idx < len(src_lines):
    samples.append({
        "Index": idx,
        "Source (Hieroglyphs)": src_lines[idx],
        "Reference (Burmese)": ref_lines[idx],
        "Prediction (Burmese)": pred_lines[idx],
    })

# Format as a clean Pandas DataFrame for easy viewing
df_samples = pd.DataFrame(samples)
pd.set_option("display.max_colwidth", None)
display(df_samples)

,Index,Source (Hieroglyphs),Reference (Burmese),Prediction (Burmese)
0,0,𓂋𓐍𓎼𓂝 𓊪𓎡𓋴𓈎𓈙,အချစ်က နာကျင်စေတယ်။,ကျွန်မ နိုင်တာကို ကြိုက်တယ်။
1,1,𓆑 𓊪𓄿𓎼𓂝 𓎜𓀀 𓅲𓀀𓐍𓇌,ကျွန်မမှာ အစားအစာမရှိဘူး။,ကျွန်မမှာ အစားအစာရှိတယ်
2,2,𓎜𓀀 𓐍𓎛𓂝 𓈙𓄿𓏏 𓉔𓂝,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။,ဘယ်သူမှ ကျွန်မကို မမြင်ခဲ့ဘူး။
3,5,𓊪𓄿𓎼𓂝 𓄿 𓎛𓆑𓏭𓂝 𓈎𓋴𓆑𓄡,ခရီးကောင်းပါ,ခရီးကောင်းပါ
4,10,𓂨𓀀𓎡 𓈙𓉔𓂝𓂋𓂋 𓃀𓐍𓐍𓇌,နင့်နံ့က ကောင်းတယ်,မင်းက ကောင်းကောင်း ခံစားရတယ်။
5,20,𓈎𓊪𓆑𓈙 𓆑𓈙 𓊪𓎡𓃀𓂝,ဒါက ကြီးမားပါတယ်။,ဒါက ခွေးတစ်ကောင်ပါ။
6,40,𓆑𓈎 𓏏𓄿𓈙𓎛𓈎 𓂋𓎡𓏭𓈖,ကံမကောင်းခဲ့ဘူး။,အဲဒါက ငါ့ဟာ မဟုတ်ခဲ့ဘူး။
7,80,𓊪𓂝 𓅲𓀀𓎡𓎛𓇌 𓆑𓈎,သူတွေ့တယ်။,သူအောင်မြင်ခဲ့တယ်။
8,160,𓆑𓈎 𓃀𓂝𓈎𓈙 𓏏𓐍𓋴𓈙𓂝,ပိုဆိုးလာတယ်,ပိုကောင်းလာမယ်။
9,320,𓆑𓂋𓂋 𓏏𓐍𓋴𓈖 𓊪𓄿𓋴𓇌,ကျွန်တော် အလုပ်ကြိုးစားတယ်။,သင်ဟာ ကြိုးစားလုပ်ကိုင်တယ်။

In [40]:
import pandas as pd

print("1. Burmese -> Hieroglyph Translation Pipeline")

data = {
    "Metric / Aspect": [
        "Overall BLEU Score",
        "1-gram Precision",
        "2-gram Precision",
        "3-gram Precision",
        "4-gram Precision",
        "Brevity Penalty (BP)",
        "Length Ratio",
        "Token Lengths (Hyp / Ref)"
    ],
    "RNN Model": [
        "11.8",
        "39.3%",
        "17.7%",
        "7.7%",
        "3.7%",
        "1.000",
        "1.067",
        "1,678 / 1,573"
    ],
    "Transformer Model": [
        "0.0 (Diverged/Collapsed)",
        "0.0%",
        "0.0%",
        "0.0%",
        "0.0%",
        "0.117",
        "0.318",
        "500 / 1,573"
    ],
    "Ensemble Model": [
        "19.1",
        "32.0%",
        "15.7%",
        "11.4%",
        "23.1%",
        "1.000",
        "1.044",
        "998 / 956"
    ]
}

df = pd.DataFrame(data)
display(df)

1. Burmese -> Hieroglyph Translation Pipeline

,Metric / Aspect,RNN Model,Transformer Model,Ensemble Model
0,Overall BLEU Score,11.8,0.0 (Diverged/Collapsed),19.1
1,1-gram Precision,39.3%,0.0%,32.0%
2,2-gram Precision,17.7%,0.0%,15.7%
3,3-gram Precision,7.7%,0.0%,11.4%
4,4-gram Precision,3.7%,0.0%,23.1%
5,Brevity Penalty (BP),1.000,0.117,1.000
6,Length Ratio,1.067,0.318,1.044
7,Token Lengths (Hyp / Ref),"1,678 / 1,573","500 / 1,573",998 / 956

In [41]:
import pandas as pd

print("2. Hieroglyph -> Burmese Translation Pipeline")

data = {
    "Metric / Aspect": [
        "Overall BLEU Score",
        "1-gram Precision",
        "2-gram Precision",
        "3-gram Precision",
        "4-gram Precision",
        "Brevity Penalty (BP)",
        "Length Ratio",
        "Token Lengths (Hyp / Ref)"
    ],
    "RNN Model": [
        "19.8",
        "27.7%",
        "13.6%",
        "12.4%",
        "33.3%",
        "1.000",
        "1.024",
        "979 / 956"
    ],
    "Transformer Model": [
        "15.0",
        "31.0%",
        "14.6%",
        "9.1%",
        "12.5%",
        "1.000",
        "1.026",
        "981 / 956"
    ],
    "Ensemble Model": [
        "17.2",
        "45.4%",
        "21.8%",
        "11.3%",
        "7.8%",
        "1.000",
        "1.041",
        "1,638 / 1,573"
    ]
}

df = pd.DataFrame(data)
display(df)

2. Hieroglyph -> Burmese Translation Pipeline

             Metric / Aspect  RNN Model Transformer Model Ensemble Model
0         Overall BLEU Score       19.8              15.0           17.2
1           1-gram Precision      27.7%             31.0%          45.4%
2           2-gram Precision      13.6%             14.6%          21.8%
3           3-gram Precision      12.4%              9.1%          11.3%
4           4-gram Precision      33.3%             12.5%           7.8%
5       Brevity Penalty (BP)      1.000             1.000          1.000
6               Length Ratio      1.024             1.026          1.041
7  Token Lengths (Hyp / Ref)  979 / 956         981 / 956  1,638 / 1,573